### ISSUE TITLE
terminal becomes unresponsive after socket disconnect

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#1]
Mar 4, 2019 at 5:24:15 PM
**Describe the bug**
When using the IDE and losing focus of the browser window, the terminal seems unresponsive after regaining focus on the window. Nvm was installed on the container.

**Update** this seems related to the WebSocket disconnecting

**To Reproduce**
1. Log in and open the IDE
2. Open the terminal
3. Open a new chrome _window_ and do something else
4. Come back to the window with the IDE and notice that you can no longer type in the terminal 

**Expected behavior**
The terminal remains responsive when coming back to the browser window

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70

**Comment by kylecarbs** [comment]
Should be in relation to the ping/pongs. @coderasher has a fix in the works!

**Comment by kylecarbs** [comment]
Fixed in https://github.com/codercom/code-server/pull/2

**Comment by haryonocisoka** [comment]
Prosess retrn not zero code 1??? notification upload using otg pleas solution.

**Comment by deansheather** [comment]
@haryonocisoka Please open a new issue explaining your issue so we can help you solve it. :smile:

**Comment by haryonocisoka** [comment]
Ok tanks
