### ISSUE TITLE
remove install packages script

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#100]
See https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by nhooyr** [comment]
@kylecarbs marking this as urgent as its leaving a bad impression on contributors

**Comment by mko-x** [comment]
Same issue here - pretty annoying. Wanted to help with some stuff, but if the 'stable' is so unstable at local build it's getting to a problem.

See the logs at my [hastebin](https://paste.m-ko.de/ocobiwihag.sql)

Any insights what to do?

**Comment by lherman-cs** [comment]
same issue too 
![Screenshot_2019-03-09_14-32-55](https://user-images.githubusercontent.com/15654932/54076290-10fc7500-4278-11e9-862a-4b0ada8058b7.png)

**Comment by kylecarbs** [comment]
Will be fixing asap. In the meantime, running yarn multiple times should result in success.
