### ISSUE TITLE
Docker example in README modifies user data as root

### ISSUE THREAD

**Issue by kennylevinsen** [codercom/code-server#102]
The README contains the following docker command:

```bash
docker run -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
```

The result of running this docker command is that code-server accesses the current working directory as *root*, rather than the current user. This is almost certainly not what the user intended.

For this use-case (simply editing the user's workspace), the `--user` option should be used to execute code-server as non-root. However, code-server borks out for various reasons if you try that. The workspace folder, for example, is not world-editable. Those issues should be sorted out, and the Docker example in the README should be updated.

**Comment by Omeryl** [comment]
There's currently discussion in #65 trying to figure out the best way to go about this.

**Comment by kylecarbs** [comment]
Closing in favor of the larger discussion in #65
