### ISSUE TITLE
Binary does not work with WSL

### ISSUE THREAD

**Issue by DiegoBM** [codercom/code-server#11]
- `vscode-remote` version: 1.31.0-20
- OS Version: Windows 10 (rel 1809) - WSL Ubuntu 16.04.4 LTS

#### Steps to Reproduce

1. Run WSL and try to run the executable
2. Error: `-bash: ./code-server: cannot execute binary file: Exec format error`

**Comment by kylecarbs** [comment]
Will look into this. Thanks for the report.

**Comment by nikeinikei** [comment]
can confirm, didn't work for me either

**Comment by kylecarbs** [comment]
Seems like binaries compressed with UPX do not work in WSL.

https://github.com/Microsoft/WSL/issues/2121#issuecomment-302144752

We'll create a version in the CI that isn't compressed. You can try decompressing it, might work.

**Comment by DiegoBM** [comment]
@kylecarbs running the upx -d command on the binary it says that the binary was not packed by upx


<pre>
# upx -d code-server
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: code-server: NotPackedException: not packed by UPX

Unpacked 0 files.
</pre>

**Comment by kylecarbs** [comment]
Ah interesting. We compress the node binary prior to packaging, so that
makes sense. Will add the additional target soon.

**Comment by chintanp** [comment]
Running from docker on WSL good would be good. Right now I use Cloud9 local install through https://github.com/c9/core for Python development. Wonder if Coder can provide better intellisense.

**Comment by DiegoBM** [comment]
Any chance to disable that UPX compression in the next release?

**Comment by SuperSandro2000** [comment]
> Any chance to disable that UPX compression in the next release?

The plan was to add an additional target and not remove an optimization.

**Comment by DiegoBM** [comment]
> The plan was to add an additional target and not remove an optimization.

Any chance to disable that UPX compression, as an additional target as @kylecarbs mentioned above, in the next release? (for the completionists that need full sentences out there...)

**Comment by coderasher** [comment]
We ended up removing compression altogether (from 1.32.0-245 onward): https://github.com/codercom/code-server/commit/8bab787804912306821e50747699ce25ba1d22e9.

**Comment by DiegoBM** [comment]
@coderasher, was compression causing other unexpected problems? Out of curiosity

**Comment by DiegoBM** [comment]
Now it works flawlessly on WSL, thank you! Closing as fixed
