### ISSUE TITLE
Idea for a local client app

### ISSUE THREAD

**Issue by haydennyyy** [codercom/code-server#114]
I had an idea for what the local apps could look like. I took the code from the authenticate page, and just changed it up. All references to `code-server` are `code-client` and it's for a server address.
```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<title>code-client</title>
</head>

<body>
	<div class="login">
		<div class="back">
			<- Back </div>
			<h4 class="title">code-client</h4>
				<h2 class="subtitle">
					Enter server address
				</h2>
				<div class="mdc-text-field">
					<input type="text" id="server-address" class="mdc-text-field__input" required>
					<label class="mdc-floating-label" for="server-address">Server Address</label>
					<div class="mdc-line-ripple"></div>
				</div>
				<button id="submit" class="mdc-button mdc-button--unelevated">
					<span class="mdc-button__label">Next -></span>
				</button>
		</div>
	</div>
</body>

</html>
```
Using this could allow people to log into whatever server they wanted, and it could even be wired up to use this as a login system if needed. Potentially even adding a quick login thing for Coder.com users.

I think this idea could work quite well for an electron app or something similar.

**Comment by kylecarbs** [comment]
Thanks for the idea! We have a thin client in the works. :)

**Comment by nhooyr** [comment]
What is that `HTML` supposed to do? I'm confused about this issue.

**Comment by nhooyr** [comment]
Electron app is being tracked at https://github.com/codercom/code-server/issues/142

Does this need to remain open? @kylecarbs

**Comment by kylecarbs** [comment]
It's a suggestion for simple logic we could contain in a client-app.

Let's update the electron app issue to be native apps (so it'd include platforms like ChromeOS) along with reference this issue in the body.

Continue discussion in https://github.com/codercom/code-server/issues/142
