### ISSUE TITLE
vscode-emmet-helper not being required properly

### ISSUE THREAD

**Issue by haydennyyy** [codercom/code-server#115]
- `code-server` version: Coder.com
- OS Version: Coder.com

#### Steps to Reproduce

1. Open VS Code
2. Open a new HTML file
3. Try and use Emmet snippets (`html` is a seperate snippet)
4. View the console.

Here are my logs: https://cdn.discordapp.com/attachments/467359968421740574/553376779679694868/ide.coder.com-1552005725056.log

**Comment by foresthoffman** [comment]
I saw the same error when trying to use the `ul>li` snippet, which is unavailable.

**Comment by kylecarbs** [comment]
Will fix.

**Comment by kylecarbs** [comment]
Seems like this has been fixed.
