### ISSUE TITLE
no mount command in the vs code command pallet at ide.coder.com

### ISSUE THREAD

**Issue by rholland** [codercom/code-server#118]
The mount command is not available in the command pallet.  It was working before the recent change over to ide.coder.com

**Comment by haydennyyy** [comment]
Yeah, this isn't a bug. That's not an available feature anymore, Coder removed it because it wasn't gonna work properly with this release of code-server, (I think that's what you told me, right @coadler ?) as they now both use the same software. Issue can be closed.

**Comment by nhooyr** [comment]
@nol166

**Comment by NGTmeaty** [comment]
![](https://owo.whats-th.is/7iKtTh8.png)

**Comment by coadler** [comment]
Correct, mounting is no longer available. But, whatever you had mounted previously will still be on your container

**Comment by nhooyr** [comment]
@coadler does that mean these docs are out of date?

https://coder.com/docs/languages

**Comment by coadler** [comment]
Yep

**Comment by nhooyr** [comment]
@nol166

**Comment by ndalliard** [comment]
How do I install npm?

The npm site (https://www.npmjs.com/get-npm) says, that it comes installed with node:
![Screenshot 2019-03-11 at 08 03 14](https://user-images.githubusercontent.com/48350275/54105742-428a5300-43d4-11e9-80f1-eeca613d42d7.png)

**Comment by marceloadsj** [comment]
One easy way is using nvm to install node and npm: https://github.com/creationix/nvm

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`

You can even switch to/from node versions on demand:

`nvm install 8` // install most up to date version 8.x
`nvm install 11` // same, most 11.x updated one
`nvm list` // list all installed versions
`nvm use 11` // change active version to 11.x

and so...

**Comment by foresthoffman** [comment]
I highly recommend https://github.com/tj/n over nvm. It keeps all sessions running on the same node env. It's very convenient.

**Comment by marceloadsj** [comment]
Just a reminder that **n** don't work on Windows, but for code-server, it's fine! haha :smiley:

**Comment by haydennyyy** [comment]
@foresthoffman @marceloadsj @rholland Hey, dunno if this helps at all, but I just put together [code-server-npm](https://github.com/haydennyyy/code-server-npm) which adds a mount-like command using `n` like Forest suggested! Not done a build yet, but I will do

**Comment by foresthoffman** [comment]
Going to mark this down as resolved.

**Comment by nhooyr** [comment]
I kept it as open as the docs are out of date. Waiting for a response from @nol166

**Comment by haydennyyy** [comment]
Okay, first build complete.
https://github.com/haydennyyy/code-server-npm/releases/latest
It's also on the marketplace as `qubedev.code-server-npm`

**Comment by nol166** [comment]
@nhooyr I updated the docs today. Just waiting for approval.

**Comment by nol166** [comment]
Moving this issue to coder/bugs since it doesn't pertain to the open source code-server
