### ISSUE TITLE
Extensions tag search not working.

### ISSUE THREAD

**Issue by jeasonstudio** [codercom/code-server#119]
- `code-server` version: 1.31.1-100
- OS Version: macOS 10.14.3

#### Steps to Reproduce

1. Open extensions tab and search 'tag:icon-theme'

![image](https://user-images.githubusercontent.com/17971291/54002775-b9cca680-418a-11e9-815b-ce14f832afb6.png)

**Comment by kylecarbs** [comment]
Will fix, thanks!

cc: @foresthoffman

**Comment by kylecarbs** [comment]
Is this fixed @foresthoffman ?

**Comment by foresthoffman** [comment]
This appears to be fixed, yes. Closing.
