### ISSUE TITLE
code-server --version reports development in dockerfile

### ISSUE THREAD

**Issue by kennu** [codercom/code-server#131]
First of all, this is an awesome project and I'm already using it to develop some stuff.

#### Version

- `code-server` version: 1.31.1-100
- OS Version: darwin-x64 (Mojave 10.14.2)

#### Steps to Reproduce

1. code-server --version
2. Output looks like

    server/0.0.0 darwin-x64 node-v8.9.3

It probably should show the same version as the downloaded filename.

**Comment by nhooyr** [comment]
@kylecarbs @coderasher

**Comment by kylecarbs** [comment]
Ah that version tag may be incorrect. Not certain we have the default value set for it.

**Comment by coderasher** [comment]
Partially fixed by https://github.com/codercom/code-server/commit/736feaba51c775ed3ad690f95565fde4e8acbb12. The versions come from Travis's build number, so I'm not sure how we'd get the versions in Docker unless we pull the latest binary instead of building it from scratch.

**Comment by nhooyr** [comment]
@coderasher ci needs to build/push the Dockerfile. Shouldn't the version numbers come from the tag/branch?

**Comment by coderasher** [comment]
Is the Docker build supposed to be the latest code rather than the latest release?

**Comment by nhooyr** [comment]
Latest release, so it'd only build/push on a tagged commit.

**Comment by coderasher** [comment]
Ahhh, I see what you're saying.

**Comment by code-asher** [comment]
Closed in favor of #58. We'll have to change the CI to push the Docker image in order to make it report the correct version.
