### ISSUE TITLE
Terminal not loading

### ISSUE THREAD

**Issue by EugeneKallis** [codercom/code-server#137]
#### Steps to Reproduce

1. Open the terminal

This returns just a black screen and a cursor.

I dont know if this is related but i see this in the logs.

`ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'\n    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:84397:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}`

**Comment by kylecarbs** [comment]
That error should be unrelated.

I've seen this before, try resizing the terminal a little bit. We'll fix that bug!

**Comment by NGTmeaty** [comment]
Duplicate of #121 ?

**Comment by kylecarbs** [comment]
We'll continue discussion in https://github.com/codercom/code-server/issues/121

**Comment by EugeneKallis** [comment]
IS that error related to the terminal not showing up? I just posted that just in case. 121 is strictly that error.

**Comment by EugeneKallis** [comment]
Also i tried resizing and it didnt bring the terminal up

**Comment by creativemacmac** [comment]
Hey there folks :) I can't get the terminal to run - thus no live preview. Error message:
The terminal process command '/bin/bash' failed to launch (exit code: 1)
am I missing something?

**Comment by allquixotic** [comment]
I have the same problem. This issue is not fixed in my opinion. Probably something environmental but I don't know for sure.

**Comment by beyera** [comment]
I ran into this same issue using Brave browser. It was resolved by allowing "3rd party device recognition attempts". I would recommend disabling shields all together for whatever URL/IP you're running code-server on.
