### ISSUE TITLE
Add a service-worker to enable caching and desktop PWA

### ISSUE THREAD

**Issue by creativeguy2013** [codercom/code-server#138]
On slow connections code-server takes ages to load the main JS bundle file, as it is multiple megabytes large. When reloading the page the bundle file has to get loaded again unless the browser locally caches it, which is not certain. It would drastically improve the experience if a service-worker would cache all of the necessary html, css, and JS bundles.

In combination with a web-manifest this would also enable code-server to be installed on client devices as PWA's. This is especially useful for desktop as you would not have to install a thin client. Using a PWA would also enable code-server to eventually implement features such as share-target to upload files onto the remote container.

This would require a very minimal amount of work for a very very useful feature, especially when you use [Workbox](https://developers.google.com/web/tools/workbox/).

**Comment by kylecarbs** [comment]
I definitely agree. We'll do this!

**Comment by creativeguy2013** [comment]
If I find some time today I'll look into setting up the manifest file.

**Comment by creativeguy2013** [comment]
#154 should fix this

**Comment by sondresorbye0111** [comment]
This would also make the top bar in chrome dissapear on android devices.

**Comment by creativeguy2013** [comment]
merged in #154
