### ISSUE TITLE
native apps

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#142]
Tracking issue for native apps.

**Comment by avelino** [comment]
It would be interesting to have a previous configuration where we put the URL of the server code-server, with the possibility of editing future

- Support HTTP Basic auth: it's a necessity of mine, more can be from other people too

**Comment by avelino** [comment]
@nhooyr If this issue is to tracking of issues related to **Native App** we can use the github feature of [milestones](https://help.github.com/en/articles/about-milestones)

**Comment by Kiser360** [comment]
This issue and the Readme mention the potential future 'native' apps in the form of electron or chromeos apps. I'd like to suggest just doing the steps necessary to make the served vscode instance a Progressive Web App. This would save the redundancy of converting an electron app to a server hosted webapp, only to wrap it up again in an electron app. Also, the PWA would likely be much less work to provide that 'native' window look and feel. 

Just my two cents as a big PWA fan and a fan of this project 👍. Could submit a simple PR that creates a manifest for the server.

**Comment by sr229** [comment]
+1 for @Kiser360, we do have PR #154 for PWA, and we'll need ChromeOS apps to handle offline support as well if this is the case (I did have a outstanding PR #225 for CrOS, we just need to automate this if they want it installed locally for CrOS machines).

**Comment by kylecarbs** [comment]
Closing in favor of [sshcode](https://github.com/codercom/sshcode) and projects in the works :eyes:

**Comment by nhooyr** [comment]
@kylecarbs sshcode doesn't deal with this issue afaik, we should keep it open.

**Comment by sr229** [comment]
+1 for Reopen

**Comment by k3d3** [comment]
sshcode is deprecated. Is a native app still in the works?

**Comment by jsjoeio** [comment]
@k3d3 no, and we don't have any plans to build one anytime soon. But we do support code-server as a PWA!
