### ISSUE TITLE
how to connect Jupyter notebook server to MS Python extension

### ISSUE THREAD

**Issue by rholland** [codercom/code-server#144]
I am trying to run a Jupyter notebook server that connects to the MS Python extension but the server cannot connect. Essentially, with this extension, VS Code is a Jupyter server front end. 

I have also tried running Jupyter notebook in a terminal.  It generates the error

From a terminal I can run "jupyter notebook" which generates the error:

OSError: [Errno 99] Cannot assign requested address

I can force it to use  '127.0.0.1' or  'coder' and the server provides a token and URL but this does not connect in the extension.

Is there an ip address and port for the jupyter server for the VS Code extension to connect to?  Thanks.

**Comment by NGTmeaty** [comment]
Would this be on Coder.com or the self-hosted version?

**Comment by rholland** [comment]
ide.coder.com

**Comment by NGTmeaty** [comment]
We may want to switch repos for bugs here: https://github.com/codercom/bugs/issues

This also _seems_ to maybe be a jupyter issue. Will have to investigate.

**Comment by NGTmeaty** [comment]
Issue was moved https://github.com/codercom/bugs/issues/353 requesting close?

**Comment by foresthoffman** [comment]
sgtm
