### ISSUE TITLE
Sharing my approach to use VSCode Settings Sync and official extension market

### ISSUE THREAD

**Issue by LER0ever** [codercom/code-server#148]
First, thanks for this great project, this is much easier to use than Che and Theia

Two problems I've come across during my day of use are 
- Extensions are cached and installed from Coder's server, most of which for now are outdated
- Cannot Sync settings with VSCode

### My approach

**So I made a Docker template to automatically configure code-server from Settings Sync Gist.**

Using Docker's multi-stage build, I can directly use the actual Visual Studio Code binary to install extensions from Microsoft's server, and then later copy them to code-server. And VSCode settings are also directly fed into code-server.

### extensions.json parsing and installing
Is done the UNIX way.
```bash
jq -r ".[].metadata.publisherId" extensions.json > extensions.list
```

```bash
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Installing $line using VSCode";
    code --user-data-dir /root/.config/Code --install-extension $line
done < "$1" # extensions.list
```

For those of you who already use Settings Sync, [my configuration](https://github.com/LER0ever/EvDev) might be handy as you only need to change the gist id to make the entire thing work.

Relevant Issues: #30 #145 
My template: https://github.com/LER0ever/EvDev

Screenshot, almost the same as my VSCode: 
![image](https://user-images.githubusercontent.com/10568668/54055751-9d912f80-41b3-11e9-9c0f-f916d50d4c28.png)

**Comment by lsmoura** [comment]
Any chance you can share your docker template? 😊

**Comment by ezh** [comment]
@LER0ever Thank you very much for information.

I updated your solution a bit. Now, everything that I need is only update _extensions_ file.
https://github.com/ezh/code-server/blob/ide/Dockerfile
https://github.com/ezh/code-server/blob/ide/extensions

I get extension id directly from URL of VSCode market.
For example https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby
rebornix.Ruby is extension id.

**Comment by nhooyr** [comment]
Wood love to see this in the https://github.com/codercom/code-server/wiki

**Comment by davefinster** [comment]
I took a somewhat heavier handed approach. I build a docker image containing the real VSCode as per https://github.com/davefinster/coder/blob/master/official-vscode/Dockerfile and then build the real Coder container with https://github.com/davefinster/coder/blob/master/go/Dockerfile.

In my case I'm just installing the Go extensions.

**Comment by kylecarbs** [comment]
Closing for now. [sshcode](https://github.com/codercom/sshcode) supports syncing of settings and extensions.
