### ISSUE TITLE
Adher to the XDG base directory specification

### ISSUE THREAD

**Issue by jfowl** [codercom/code-server#15]
Please use the [XDG data dir](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics) for data and log dirs. 

I just started it and got shown this: `{"data-dir":"/home/jfowl/.code-server","working-dir":"/tmp/code-server-dir","log-dir":"/home/jfowl/.code-server/logs/20190305213428008"}`. I personally don't like apps to create even more dotfils/dotdirs in my /home directory than it already has. Using the XDG basedir spec would be a great step towards using well-established standards in the unix world <3.

**Comment by kylecarbs** [comment]
I agree. We’ll do this.
