### ISSUE TITLE
Custom keybindings don't take effect until the keybindings.json file is saved on every page load

### ISSUE THREAD

**Issue by weikinhuang** [codercom/code-server#150]
- `code-server` version:  1.31.1-100
- OS Version:  Windows 10 desktop, running on remote docker Ubuntu 18.04.1 LTS, downloading the release binary from the releases tab.

#### Steps to Reproduce

1. Create a keyboard shortcut with a `when=!isMac` condition
```
    { "key": "ctrl+d",                "command": "editor.action.deleteLines",
                                         "when": "!isMac" },
```
2. Try to use shortcut in the editor, it does nothing

**Comment by NGTmeaty** [comment]
Are you running with some kind of SSL certificate? (it's ok even if it's self-signed)

**Comment by weikinhuang** [comment]
Yes, I'm running under https. After some more investigation, I realized that with code-server I have to explicitly disable default keybindings to use custom ones.

```
    { "key": "ctrl+d",                "command": "-editor.action.addSelectionToNextFindMatch"},
```

On regular vscode I do not have to do this.

**Comment by weikinhuang** [comment]
Actually, after playing with this some more. I noticed that keyboard bindings do work, but they don't take effect until the keybindings file is saved once/edited. And I would have to do this every time the page is reloaded.

**Comment by kylecarbs** [comment]
Fixed in https://github.com/codercom/code-server/commit/4d576ab4d471fe872ce17f5b7a32ea91d0529cbd. New release coming :rocket:
