### ISSUE TITLE
Unable to use Color Themes

### ISSUE THREAD

**Issue by CargoDankster** [codercom/code-server#157]
I am able to download themes for both Colors and Icons, but only Icons can be applied.

Steps to reproduce:
1 - Download theme
2 - Reload page
3 - Apply theme

Does not fix after I reload the page or restart the server, either.

Server info:
Ubuntu Server 18.04.2 LTS
Xeon E3 1225 V3
12 GB DDR3 1600 MHz

Client info:
Windows 10 1803
Google Chrome 72
Ryzen R7 2700x
16 GB DDR4 2733 MHz

Theme(s) in question: Material Theme

**Comment by creativeguy2013** [comment]
Just tested the exact theme and it seems to work.

@CargoDankster Can you check if there are any errors or warnings in the developer console? Does only this theme not work or does it apply to all themes? Are you using docker or binary or did you build yourself (what version)?

**Comment by sr229** [comment]
@CargoDankster We'll need your system info as well so we can reproduce the bug. As of this writing, I can't replicate it with 1.31.1-100 on 5 Linux targets.

**Comment by gerroon** [comment]
I am on Debian Buster using the release binary. I get no color syntax in Python files. I installed Python extensions (not sure if it really installs or fake installs). I also tried bunch of color themes in there, no nothing to me as well

Debian Buster x64, code-server v1.32.0-245

**Comment by sr229** [comment]
@gerroon its not related, and its a minor bug, but I believe that error can also have a big correlation.

**Comment by kylecarbs** [comment]
Seems to be working in the latest release.

**Comment by sharifahmad2061** [comment]
not working for me either. neither html or python files are color coded.

**Comment by sam0x17** [comment]
can confirm the colors are all a bit off and not working for any color themes on new install on ubuntu 20.04 and using brave web browser with shields disabled

**Comment by nhooyr** [comment]
@sharifahmad2061 Please update to the latest version.

**Comment by JordiBolibar** [comment]
After updating code-server to v4.4.0, I'm having exactly the same issue in a JupyterHub.
