### ISSUE TITLE
Is it possible to use the same VSCode installed in my system?

### ISSUE THREAD

**Issue by unique1o1** [codercom/code-server#158]
#### Description

Is it possible for me to access the same VSCode that I'm running in my system with all the extensions, user snippets, and theme?

**Comment by jeasonstudio** [comment]
For macOS:
```bash
$HOME/.vscode/extensions/* => .code-server/extensions/*
$HOME/Library/Application Support/Code/User/* => .code-server/User/*
```

**Comment by unique1o1** [comment]
Can you elaborate?

**Comment by jeasonstudio** [comment]
You can find `.code-server` in `$HOME` by default.  
Or use `--data-dir=data-dir` when run `code-server xxxx`

**Comment by unique1o1** [comment]
Thanks, I symbolic linked the extensions and user folder
