### ISSUE TITLE
Handle URLs more robustly

### ISSUE THREAD

**Issue by mingjun97** [codercom/code-server#160]
- `code-server` version: docker default version
- OS Version: docker CE inside Debian

#### Steps to Reproduce

1. Establish reverse proxy via nginx with mapping `https://xxxx/ide/` to `http://localhost:8443/`
2. The page showed `GET // Failed`. 

I also tried other configurations. But this configuration seems to be the most correct. I guess the URL handler should be more robust to handle URLs like this.

**Comment by NGTmeaty** [comment]
Open PR #149
