### ISSUE TITLE
Select and paste over

### ISSUE THREAD

**Issue by avelino** [codercom/code-server#161]
Cannot overwrite selected text with copy and paste

- `code-server` version: master branch
- OS Version: Ubuntu

#### Steps to Reproduce

1. Copy (*CMD+C*) any text to clipboard
1. Select text any input (editor or text fields), per example *CMD+A*
1. Paste (*CMD+V*) clipboard

**Comment by Heegreis** [comment]
I also have the problem. Because the text selected will be copy, the origin clipboard was replace.
Even change setting is still unhelpful:
    "editor.copyWithSyntaxHighlighting": false,
    "editor.emptySelectionClipboard": false

**Comment by avelino** [comment]
Thanks, working set 3 config

```
"editor.copyWithSyntaxHighlighting": false,
"editor.emptySelectionClipboard": false,
"editor.selectionClipboard": false,
```

**Comment by Littlejd1997** [comment]
Commenting in here. Why do we need to add these 3 configs? Stock VSCode doesn't have copy-on-select enabled. Why does code-server? Extremely confusing and frustrating

**Comment by avelino** [comment]
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#selectionclipboard

Is VSCode config not code-server config

**Comment by kbrose** [comment]
Maybe this should be left open until the default behavior is to NOT copy on select? Or is the current default the expected behavior?
