### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by rkeene** [codercom/code-server#17]
No build instructions for this software.  It would be helpful to know how to build it from the release tarball.

**Comment by kylecarbs** [comment]
This is planned. For now you can do:
```bash
yarn
yarn task build:server:binary
```
It should output to packages/server/cli-<platform>

**Comment by grant** [comment]
Also use node >=8 and <9.

**Comment by muojp** [comment]
- Required (Ubuntu) packages: https://github.com/codercom/code-server/blob/master/.travis.yml#L10
 - If you're using stock Node.js/npm on some distros, you would need to perform `npm install -g npm` to fetch newer npm which have `npx` binary with it.

**Comment by bketelsen** [comment]
be sure that the node version you have installed has an appropriate release for nexe/nexe, I had node 8.15.1, but there's only 8.15.0 in nexe, so I downgraded node to get this to build.

**Comment by nhooyr** [comment]
Dockerfile is available for those of you who want to dev for linux.

**Comment by nhooyr** [comment]
So lets just document the existence of the Dockerfile and for other platforms, people can look at the .travis.yml.

**Comment by memory-yancy** [comment]
I have tried in `CentOS`, record in https://github.com/codercom/code-server/issues/23#issuecomment-471141576 , hope that help others

**Comment by tvarwig** [comment]
After I run `yarn task build:server:binary` everything builds successfully from what I can see but there are no binaries in `packages/server/cli-` there are no `cli` directories under `packages/server`

**Comment by activatedgeek** [comment]
I was able to get a full build working however on running I get the following error:

`Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found`.

I installed the latest library which contains that version but is on a non-standard path. I updated `LD_LIBRARY_PATH` but to no effect. Any suggestions?

**Comment by activatedgeek** [comment]
I actually realized that I was building from master. When I built from the latest tag, it worked. Thanks!

**Comment by bpmct** [comment]
Is there no way to build from master and get a binary?

**Comment by NGTmeaty** [comment]
I believe there's a yarn task to build and get a binary. 

I'd reference our [Dockerfile](https://github.com/codercom/code-server/blob/master/Dockerfile).

**Comment by wongxingjun** [comment]
> I was able to get a full build working however on running I get the following error:
> 
> `Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found`.
> 
> I installed the latest library which contains that version but is on a non-standard path. I updated `LD_LIBRARY_PATH` but to no effect. Any suggestions?

The same problem I met recently, build instructions are needed for users to run this software in some old versions of OSes.

**Comment by nol166** [comment]
We are adding better documentation to our April to-do list. Sorry it has taken so long 🤕

**Comment by Multishifties** [comment]
A new issue was opened on this https://github.com/codercom/code-server/issues/417

**Comment by code-asher** [comment]
Closing in favor of #417.

**Comment by qinzehua** [comment]
> I believe there's a yarn task to build and get a binary.
> 
> I'd reference our [Dockerfile](https://github.com/codercom/code-server/blob/master/Dockerfile).

hi, the Dockerfile is missing, can you share it?

**Comment by code-asher** [comment]
If you are looking for our release image though (it takes an already-built code-server as input) that can be found here: https://github.com/coder/code-server/blob/main/ci/release-image/Dockerfile

**Comment by qinzehua** [comment]
> We no longer have a Dockerfile that builds code-server but we have documentation for building here: https://github.com/coder/code-server/blob/main/docs/CONTRIBUTING.md#build

I am follow the steps to do building.
When run `node .` in `release` folder.  Got error ``Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/cddev/Downloads/code-server-4.0.1/release/node_modules/argon2/lib/binding/napi-v3/argon2.node)``

My centos 7 mechine's GLIBC version is 2.17. So i  attempt to upgrade  GLIBC  to 2.25. But fail.
Is there any other way to resolve the `GLIBC_2.25` error?

**Comment by jsjoeio** [comment]
What happens if you run `npm_config_build_from_source=true node .` in the release folder? see [here](https://github.com/coder/code-server/pull/3422#pullrequestreview-677765057)

**Comment by codegzx** [comment]
> > We no longer have a Dockerfile that builds code-server but we have documentation for building here: https://github.com/coder/code-server/blob/main/docs/CONTRIBUTING.md#build
> 
> I am follow the steps to do building. When run `node .` in `release` folder. Got error `` Error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/cddev/Downloads/code-server-4.0.1/release/node_modules/argon2/lib/binding/napi-v3/argon2.node) ``
> 
> My centos 7 mechine's GLIBC version is 2.17. So i attempt to upgrade GLIBC to 2.25. But fail. Is there any other way to resolve the `GLIBC_2.25` error?

I meet the same problem, can you tell me how do you fix it?
