### ISSUE TITLE
Installing extensions from command line

### ISSUE THREAD

**Issue by ThorbenJensen** [codercom/code-server#171]
It would be great to be able to script the installation of extensions, 
e.g. after starting code-server in a new container.

A feature similar to VScode's ```code --install-extension``` would be very helpful.
See the example [here](https://stackoverflow.com/a/34339780).

Or am I missing another way to install extensions to code-server from the command line?

**Comment by sr229** [comment]
@ThorbenJensen have you tried using `ext install <package name>`?

**Comment by ThorbenJensen** [comment]
@sr229 
thank you for this idea - I have just tested it.
I have the feeling that ```ext install <package name>``` does not work outside the GUI/browser?
If I am mistaken, please let me know.

I would like to be able to install extensions from the command line - *before* accessing code-server in the browser.
I am looking for something like the VSCode feature of working with extensions from the command line.
How it is done in VSCode is also documented [here](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions).

**Comment by jeasonstudio** [comment]
@ThorbenJensen I guess you want to pre-load some extensions before running.  
`yarn task build:copy-vscode` in `build/tasks.ts#171` may help.

**Comment by ThorbenJensen** [comment]
@jeasonstudio I think this goes into the right direction. 
Unfortunately, my javascript is not good enough to adapt ```build/tasks``` to my needs.

Is there anything I can do (e.g. ```yarn ...``` ) to install an extension after the pre-built container is running?
I would like to enter the running container from ```codercom/code-server```, and run a command for installation of a package.

**Comment by jeasonstudio** [comment]
@ThorbenJensen For now, you can just copy `extension folder` to `$HOME/.code-server/extensions`. It will work.  

```bash
cp -r $HOME/.vscode-insiders/extensions/spywhere.guides-0.9.3 $HOME/.code-server/extensions/spywhere.guides-0.9.3
```

**Comment by ThorbenJensen** [comment]
@jeasonstudio Thank you for the hint.
I suppose this is not an option for my situation, considering that I just want to pull and start the container.
At maximum, I would extend the Dockerfile.

Nonetheless, I will check out code-server again in a few months.
Very impressive and useful so far!

As far as I am concerned, this issue can be closed.
Of course you can leave it open, if you feel like implementing this feature down the road.

**Comment by faustomorales** [comment]
@ThorbenJensen I think you can do this by just extending the Dockerfile as @jeasonstudio suggests. 

For example, the following installs the [Preview](https://marketplace.visualstudio.com/items?itemName=searKing.preview-vscode#overview) extension. I needed it because I couldn't get the built-in Preview functions to work out-of-the-box and also it comes with Mermaid diagram support, which the built-in previewer does not.

```
RUN apt-get update && apt install -y bsdtar curl
RUN mkdir -p /root/.local/share/code-server/extensions
RUN curl -JL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/searKing/vsextensions/preview-vscode/2.0.3/vspackage | bsdtar -xvf - extension
RUN mv extension /root/.local/share/code-server/extensions/searKing.preview-vscode-2.0.3
```

The lines above do the following.

1. Install `bsdtar` and `curl`. We install `bsdtar` because `gnutar`, which is what ships with Ubuntu and Debian doesn't function properly with the archives we get from the Visual Studio web site).
2. Create an `extensions` subdirectory for the `code-server` data directory. The data directory path above (`/root/.local/share/code-server/`) is the default from what I can tell. You can look at the logs to verify that it's the same with your configuration. You'll see something like `INFO  Initializing {"data-dir":"/root/.local/share/code-server","working-dir": ...,"log-dir": ...}` when starting the container.
3. Download and extract the extension file from the Visual Studio web site. The URL follows the form `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/<PUBLISHER>/vsextensions/<EXTENSION-NAME>/<VERSION>/vspackage`. We only extract the `extension` folder.
4. Move the extension folder to a properly named folder of the form `<PUBLISHER>.<EXTENSION-NAME>-<VERSION>` in the `extensions` subdirectory.

If all goes well, you should be able to get the following.

<img width="1197" alt="Screen Shot 2019-03-17 at 1 05 41 PM" src="https://user-images.githubusercontent.com/9735401/54495812-69092c00-48b5-11e9-8cca-82f45dcc13a3.png">

Hope this helps!

**Comment by yohancourbe** [comment]
A lightweight alternative could be to use [workspace recommended extensions].(https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)

**Comment by sabrehagen** [comment]
> A lightweight alternative could be to use [workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)

This is currently not supported. What needs to be done to enable workspace extensions team?

**Comment by ThorbenJensen** [comment]
@faustomorales great ideas, thanks a lot!
It appears that the extension folder in the container I extended from ```codercom/code-server``` is located at ```/root/.code-server/extensions```.

So, heavily inspired by what you suggested, this is the Dockerfile that works for me:
```
FROM codercom/code-server
RUN apt-get update && apt-get -y upgrade

# VSCode extensions
RUN apt-get install -y bsdtar curl
RUN mkdir -p /root/.code-server/extensions
RUN curl -JL https://github.com/Microsoft/vscode-python/releases/download/2019.2.5558/ms-python-release.vsix | bsdtar -xvf - extension
RUN mv extension /root/.code-server/extensions/ms-python.python-vscode-2.0.3

CMD ["code-server", "--allow-http", "--no-auth"]
```
If anyone is interested in testing this Dockerfile:
```
$ sudo docker build . -t code-server-test
$ sudo docker run -p 8443:8443 -v "${PWD}:/root/project" code-server-test
```
Thanks, again :-)

**Comment by coadler** [comment]
Resolved in https://github.com/codercom/code-server/pull/504

**Comment by jagraj** [comment]
> @faustomorales great ideas, thanks a lot!
> It appears that the extension folder in the container I extended from `codercom/code-server` is located at `/root/.code-server/extensions`.
> 
> So, heavily inspired by what you suggested, this is the Dockerfile that works for me:
> 
> ```
> FROM codercom/code-server
> RUN apt-get update && apt-get -y upgrade
> 
> # VSCode extensions
> RUN apt-get install -y bsdtar curl
> RUN mkdir -p /root/.code-server/extensions
> RUN curl -JL https://github.com/Microsoft/vscode-python/releases/download/2019.2.5558/ms-python-release.vsix | bsdtar -xvf - extension
> RUN mv extension /root/.code-server/extensions/ms-python.python-vscode-2.0.3
> 
> CMD ["code-server", "--allow-http", "--no-auth"]
> ```
> 
> If anyone is interested in testing this Dockerfile:
> 
> ```
> $ sudo docker build . -t code-server-test
> $ sudo docker run -p 8443:8443 -v "${PWD}:/root/project" code-server-test
> ```
> 
> Thanks, again :-)

@ThorbenJensen 

I tried your dockerfile above and it fails to build and here is the output from the build.
I am getting permission denied. I want to install extension and could you please provide any reference to doc or Dockerfile which works.?

```
docker build . -t code-server-test
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM codercom/code-server
 ---> 9ea98ff48a65
Step 2/7 : RUN apt-get update && apt-get -y upgrade
 ---> Running in c57c1d8273f9
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
The command '/bin/sh -c apt-get update && apt-get -y upgrade' returned a non-zero code: 100
```

**Comment by deansheather** [comment]
@jagraj The recommended way to install extensions now is to use `code-server --install-extension <value>`. You can give it the path to a `.vsix` file or the ID (looks like `organization.extension-name`).

**Comment by ThorbenJensen** [comment]
@jagrag I can confirm that ```code-server --install-extension <value>``` is the new install mechanism that works. You see an example in the Dockerfile here:
https://github.com/ThorbenJensen/code-server-blueprint/blob/master/Dockerfile

**Comment by mirekphd** [comment]
> @jagraj The recommended way to install extensions now is to use `code-server --install-extension <value>`. You can give it the path to a `.vsix` file or the ID (looks like `organization.extension-name`).

Note that while it this work, it imposes root requirement. It works only for root-owned containers. In non-root trying to RUN this code would break the non-root docker run option (require running as root, i..e `docker run -u 1001` would no longer work). If you installed it as root in Dockerfile, the extension would not be installed (not visible when running as non-root user). So I suppose it's back to the COPY workaround for me:)

**Comment by mirekphd** [comment]
> `RUN mkdir -p /root/.local/share/code-server/extensions`

@faustomorales , I think the default location for VS extensions can be made more general to allow for non-root containers, thus:

`RUN mkdir -p ~/.local/share/code-server/extensions`

@ThorbenJensen  , hard-coding root folder in the default extensions location in the way demonstrated above may be the reason why the new `code-server --install-extension` option works only for containers run as root (`docker run -u 0 img:tag` == `docker run img:tag`) and imposes root requirement on previously non-root containers (which used to work under `docker run -u 1001 img`) (if you put this option in the Dockerfile section following the switch to a non-root user).

**Comment by nailsonlinux** [comment]
Thanks @faustomorales!

**Comment by sanjayme97** [comment]
above solutions are not working? any more solutions? @faustomorales @ThorbenJensen

**Comment by rahulkhanna2** [comment]
@sanjayme97 I needed a container for python data science running on EC2 with code-server up and running. This is my custom dockerfile which builds successfully

```
FROM python:3.7.7-slim

WORKDIR /home

RUN /bin/bash -c "apt-get update -y;apt-get install wget -y"

RUN wget https://github.com/cdr/code-server/releases/download/3.2.0/code-server-3.2.0-linux-x86_64.tar.gz
RUN tar -xzvf code-server-3.2.0-linux-x86_64.tar.gz

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PASSWORD=demo

CMD /bin/bash -c "./code-server-3.2.0-linux-x86_64/code-server --install-extension ms-python.python --force --install-extension ms-azuretools.vscode-docker --force && ./code-server-3.2.0-linux-x86_64/code-server --host 0.0.0.0 --port 8989" 
```

See if this works. extensions can be separated to a single run command too. But I have put this up hastly and haven't tested that approach

**Comment by hgrattenthaler** [comment]
Linking to [this issue](https://github.com/microsoft/vscode-cpptools/discussions/11154), this is still an issue. Some extensions are not found

```
root@5844681dad51:/build# code-server --install-extension ms-vscode.cpptools
Installing extensions...
Extension 'ms-vscode.cpptools' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ms-vscode.cpptools
```

or if you try to install them from .vsix you get something like this

```
root@5844681dad51:/build# code-server --install-extension clang-tidy.vsix 
Installing extensions...
Error: End of central directory record signature not found. Either not a zip file, or file is truncated.
    at v (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:106:2390)
    at /usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:106:3833
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:40:7
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:190:5
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/index.js:712:5
    at /usr/lib/code-server/lib/vscode/node_modules/yauzl/fd-slicer.js:33:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:686:5) {
  code: 'Extract',
  name: 'Extract'
}
Failed Installing Extensions: file:///build/clang-tidy.vsix
```

**Comment by code-asher** [comment]
code-server uses [Open VSX](https://open-vsx.org/) for the extension marketplace and the cpptools extension is not on there so there is unfortunately nothing we can do about it.  https://github.com/microsoft/vscode-cpptools/issues/12269#issuecomment-2088769951

As for the extract error, that makes it seem very likely that the vsix is corrupted.  Are you able to unzip it on the command line?  Might need to download it again.

**Comment by hgrattenthaler** [comment]
Yes, bsdtar is able to unzip the file, however this does not seem to be what code-server uses, so it fails.

**Comment by code-asher** [comment]
Oh interesting.  I think VS Code is using https://github.com/thejoshwolfe/yauzl
