### ISSUE TITLE
Unable to install vs-live-share

### ISSUE THREAD

**Issue by ericmjl** [codercom/code-server#173]
- `code-server` version:  1.31.1-100
- OS Version:  Ubuntu 16.04
- Extension:  https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack

## Description

I am unable to find the extension when searching for it on the code-server hosted version of VSCode.

**Comment by haydennyyy** [comment]
This extension is closed source, Coder can't use extensions that aren't OSS. #92 might change that, but it's not looking likely.

**Comment by haydennyyy** [comment]
Actually, I'm wrong there. https://github.com/MicrosoftDocs/live-share
Could we see this added to Coder's marketplace...?

**Comment by ericmjl** [comment]
Ahh! Okay, thank you for letting me know!

**Comment by NGTmeaty** [comment]
Just for the record, you can use extensions which aren't OSS, as long as you have the installation file. There currently is a issue with installing, but that will definitely be fixed soon :) #92

**Comment by stepri** [comment]
I've installed the extension but when I try to start a session nothing happens.

**Comment by foresthoffman** [comment]
@stepri What errors are you seeing in the developer console?

**Comment by stepri** [comment]
```Error: command 'liveshare.startFromActivityBar' not found```

**Comment by steven4547466** [comment]
I'm having kind of the same problem, but I'm not getting any errors, it just isn't there. It shows that it's installed and enabled just nowhere to start it.
