### ISSUE TITLE
Syntax highlighting initiates slowly on slow connections

### ISSUE THREAD

**Issue by kylecarbs** [codercom/code-server#18]
When using a slow connection, syntax highlighting seems to load slowly.

**Comment by biorisk** [comment]
I don't see any syntax highlighting for html or go code no matter how long I wait. I just installed code-server (using 1.31.0-20 release) on Debian Stretch VM on GCP.

**Comment by kylecarbs** [comment]
@biorisk what browser are you on?

**Comment by biorisk** [comment]
Good question. That is probably the problem. Chromium Version 65.0.3319.0 (Developer Build) (64-bit). In addition, my connection is over an SSH tunnel to my GCP VM. Everything else seems to work though.

**Comment by kylecarbs** [comment]
Hm. Could you try updating chrome? The SSH tunnel should be fine.

**Comment by biorisk** [comment]
Switched over to the current version of Chrome and it looks beautiful. Thanks!
