### ISSUE TITLE
Prereference Settings support 

### ISSUE THREAD

**Issue by justmao945** [codercom/code-server#180]
Does code-server support any settings.json or the perenferen settings menu ? I want to change the editor font and size

**Comment by sr229** [comment]
FWIW it does. The earlier versions won't acknowledge it, but this one seems to acknowledge the manifests.

**Comment by kylecarbs** [comment]
We don't currently detect and inherit your VS Code settings, but code-server settings should work independently.

**Comment by neighthan** [comment]
code-server seems to store `settings.json` in `~/.local/share/code-server/User`. If you keep that file synced with your `settings.json` that you normally use in VS Code, things should work fine.
