### ISSUE TITLE
Ansible Deployments

### ISSUE THREAD

**Issue by sr229** [codercom/code-server#182]
Because not everyone has the expense of doing the same thing per machine.

I made [one](https://github.com/sr229/code-server-ansible) already, I just need feedback before I upstream this.

**Comment by nhooyr** [comment]
Why not use k8s?

**Comment by nhooyr** [comment]
Or even just the docker image?

**Comment by nhooyr** [comment]
Closing regardless as we don't want to maintain this.

**Comment by sr229** [comment]
This is however intended for people who doesn't want to use containers or wants to deploy it pn VMs, I don't think containers can splve that @nhooyr

**Comment by nhooyr** [comment]
Those people can grab the binary themselves and build out their custom playbook. We don't need to handle every use case ourselves.

**Comment by nhooyr** [comment]
Your contribution is appreciated though. I'm happy to add a link to your repo for people wanting to see how its done.

**Comment by nhooyr** [comment]
Added at https://github.com/codercom/code-server/wiki/Deployment
