### ISSUE TITLE
The yarn reports an error at runtime

### ISSUE THREAD

**Issue by 407chendaxia** [codercom/code-server#184]
code-server version: master branch
OS Version: windows10

When I ran the yarn at the root directory,  it reports a error:

INFO  Installing "logger" dependencies...
ERROR Failed to install "logger" dependencies {"error":{"killed":false,"code":1,"signal":null,"cmd":"yarn --network-concurrency 1"},"stdout":"[1/4] Resolving packages...\nsuccess Already up-to-date.\n$ if [ ! -d out ];then npm run build; fi\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n","stderr":"warning ..\\package.json: No license field\n��ʱ��Ӧ�� !��\r\nerror Command failed with exit code 1.\n"}

**Comment by sr229** [comment]
Hey @407chendaxia, I want to know your system info so its easier for us to diagnose the problem, typically `yarn` works without issues, and this seems rare.

**Comment by nhooyr** [comment]
Could you provide the full log?

**Comment by jeasonstudio** [comment]
@407chendaxia 在并行安装依赖的时候会导致这个问题。也可能是GFW  的原因导致的。  
@nhooyr This problem is caused when parallel installation dependencies. It may also be that the Chinese firewall makes the installation fail.  

Maybe fix at #176   

Or add these to your `.npmrc` file:
```bash
registry=https://registry.npm.taobao.org/
electron_mirror=https://npm.taobao.org/mirrors/electron
chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
sass_binary_site=http://cdn.npm.taobao.org/dist/node-sass
disturl=https://npm.taobao.org/mirrors/node
fse_binary_host_mirror=https://npm.taobao.org/mirrors/fsevents
```

**Comment by sr229** [comment]
Sometime I wonder why even that firewall blocks NPM.

China get your crap right.

**Comment by 407chendaxia** [comment]
> Sometime I wonder why even that firewall blocks NPM.
> 
> China get your crap right.

Sorry,this is not a firewall issue but a China Telecom issue. There are three  telecommunications operator in China, only the China Telecom has this issue.

**Comment by 407chendaxia** [comment]
> Could you provide the full log?



> Could you provide the full log?

I used this tool for the first time, I just executed the yarn command in the directory.

**Comment by 407chendaxia** [comment]
> Could you provide the full log?

I followed the log and found that when I executed 'node_modules\.bin>ts-node scripts\install-packages.ts', I get this error.

**Comment by sr229** [comment]
@nhooyr this is network related issue so I don't think it merits a full verbose log during yarn install

**Comment by nhooyr** [comment]
The provided error doesn't indicate anything. How do you know its a network issue?

**Comment by sean256** [comment]
I too am having this

```
ERROR Failed to install "logger" dependencies {"error":{"killed":false,"code":1,"signal":null,"cmd":"yarn --network-concurrency 1"},"stdout":"[1/4] Resolving packages...\nsuccess Already up-to-date.\n$ if [ ! -d out ];then npm run build; fi\n\n> @coder/logger@1.0.3 build /Volumes/gits/code-server/packages/logger\n> tsc -p tsconfig.build.json && cp ./out/packages/logger/src/* ./out && rm -rf out/packages && ../../node_modules/.bin/webpack --config ./webpack.config.js\n\nerror TS5023: Unknown compiler option 'emitDeclarationOnly'.\nerror TS5023: Unknown compiler option 'resolveJsonModule'.\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n","stderr":"warning ../package.json: No license field\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @coder/logger@1.0.3 build: `tsc -p tsconfig.build.json && cp ./out/packages/logger/src/* ./out && rm -rf out/packages && ../../node_modules/.bin/webpack --config ./webpack.config.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @coder/logger@1.0.3 build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/sean/.npm/_logs/2019-03-23T03_12_28_733Z-debug.log\nerror Command failed with exit code 1.\n"}
```

**Comment by sean256** [comment]
Got it! I had a very old version of `tsc` installed. Being brand new to this project I didn't event know I had to have it as a global dependency.

Maybe it would be a good idea to add something to the readme for a developing quick-start guide?

**Comment by sr229** [comment]
We'll see if the developers can provide it, because I'm afraid the developers know more how it works

**Comment by dijiang** [comment]
![image](https://user-images.githubusercontent.com/8736832/56418911-11eae280-62cb-11e9-9aef-c24fc782661b.png)

i have the same proble on win10, how to fix? @sean256

**Comment by dijiang** [comment]
![image](https://user-images.githubusercontent.com/8736832/56419479-f08af600-62cc-11e9-8cb1-cc89a8627776.png)

**Comment by dijiang** [comment]
![image](https://user-images.githubusercontent.com/8736832/56419847-4613d280-62ce-11e9-8e00-3e1be5182fea.png)
ts-node problem?

**Comment by nol166** [comment]
Windows builds are not fully working yet

**Comment by kylecarbs** [comment]
Seems like this yarn error has been fixed since we no longer install dependencies in parallel.
