### ISSUE TITLE
path error on code runner extension for C/C++

### ISSUE THREAD

**Issue by temco** [codercom/code-server#186]
`code-server` version: 0.2 alpha
OS Version: Mac 10.14.3

## Description

When I'd installed the extensions C/C++ and Code Runner, and ran the C++ code with Code Runner, an error `/bin/sh 1:g++: not found` was raised. However, when I copied the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the terminal and ran it, it worked.

## Steps to Reproduce

1. Install the Extensions C/C++ v0.21.0 and Code Runner v0.9.7
2. New Project and create a simple cpp file with a main function
3. Click the `>` button provided by the Code Runner
4. An error shown in the `output-code` window as follows:
```
[Running] cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core
/bin/sh: 1: g++: not found
[Done] exited with code=127 in 0.044 seconds
```
5. Copy the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the `terminal` window and run it, and everything is OK

**Comment by kylecarbs** [comment]
It's possible that `code-server` can't see you have g++ installed. How did you install it?

**Comment by temco** [comment]
> It's possible that `code-server` can't see you have g++ installed. How did you install it?

I created the C++ project just on the `ide.coder.com` website. I didn't install gcc or g++, however in the environment provided by the code-server, I could see the OS (linux), memory (1GB) and disk (3GB). I found the g++ installed in the path `/coder/bin/g++` and I could run it by typing the command inside the `terminal` of the vscode, while I couldn't run it by clicking the `>` button provided by the Code Runner extension since the vscode couldn't find the `g++` command.

**Comment by kylecarbs** [comment]
Closing as it seems this is a path issue. I might be wrong though, feel free to leave a response!

**Comment by JayGhughriwala** [comment]
> `code-server` version: 0.2 alpha
> OS Version: Mac 10.14.3
> 
> ## Description
> When I'd installed the extensions C/C++ and Code Runner, and ran the C++ code with Code Runner, an error `/bin/sh 1:g++: not found` was raised. However, when I copied the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the terminal and ran it, it worked.
> 
> ## Steps to Reproduce
> 1. Install the Extensions C/C++ v0.21.0 and Code Runner v0.9.7
> 2. New Project and create a simple cpp file with a main function
> 3. Click the `>` button provided by the Code Runner
> 4. An error shown in the `output-code` window as follows:
> 
> ```
> [Running] cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core
> /bin/sh: 1: g++: not found
> [Done] exited with code=127 in 0.044 seconds
> ```
> 
> 1. Copy the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the `terminal` window and run it, and everything is OK



> `code-server` version: 0.2 alpha
> OS Version: Mac 10.14.3
> 
> ## Description
> When I'd installed the extensions C/C++ and Code Runner, and ran the C++ code with Code Runner, an error `/bin/sh 1:g++: not found` was raised. However, when I copied the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the terminal and ran it, it worked.
> 
> ## Steps to Reproduce
> 1. Install the Extensions C/C++ v0.21.0 and Code Runner v0.9.7
> 2. New Project and create a simple cpp file with a main function
> 3. Click the `>` button provided by the Code Runner
> 4. An error shown in the `output-code` window as follows:
> 
> ```
> [Running] cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core
> /bin/sh: 1: g++: not found
> [Done] exited with code=127 in 0.044 seconds
> ```
> 
> 1. Copy the command `cd "/projects/cppTest/" && g++ core.cpp -o core && "/projects/cppTest/"core` to the `terminal` window and run it, and everything is OK

Yeah I am Facing This Same Error after that **### **I am Copied My Whole code and Create a new file and then Paste That code here and Now I am Compile with Code-Runner Extension it will Compile For me,**** I don't know Why Happening With this Code Runner Extension, But I am **Trying this Check This Method in Your PC it will Work?**

**Comment by jsjoeio** [comment]
Hi @JayGhughriwala can you please open a separate issue (reference this issue) and we can look into it?  Thank you!

**Comment by JayGhughriwala** [comment]
Yeah
