### ISSUE TITLE
'.' and '..' do not resolve when starting code-server

### ISSUE THREAD

**Issue by scsmithr** [codercom/code-server#19]
The working directory when starting `code-server` with '.' or '..' ends up being '/'.

- `code-server` version: 1.31.0
- OS Version: Arch Linux

#### Steps to Reproduce
1. Start code-server with `code-server .` or `code-server ..`
2. Open in browser, see working directory is /

**Comment by sr229** [comment]
Workaround is use `$(pwd)` for `.`
