### ISSUE TITLE
Use Github Wiki instead of a docs folder

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#191]
Would make it much easier for the community to contribute versus creating PRs.

**Comment by Multishifties** [comment]
Out of curiosity how would this approach compare to a dedicated docs folder in regards to the following:

Ease of maintenance.
Ability/ease of community contributions.
Versioning.
Supporting multiple versions and translations.
Should the worst happen, the ability to roll back a bad release.
Organization.
etc.

**Comment by Multishifties** [comment]
Tagging related existing issues here:
https://github.com/codercom/code-server/issues/187
https://github.com/codercom/code-server/issues/17
https://github.com/codercom/code-server/issues/47
https://github.com/codercom/code-server/issues/145
(ok, really just every issue with a `docs` tag)

**Comment by nhooyr** [comment]
That is a fair point. Versioning/translations would unfortunately not really be possible.

The GitHub wiki is itself a git repo so we could always create a branch on it and document how to clone/read it but that's pretty janky.

So not sure we should go down this route anymore.

**Comment by nol166** [comment]
Just pushed an update for the docs. Once they are reviewed they should be ready for prod.
