### ISSUE TITLE
terminal fails to load

### ISSUE THREAD

**Issue by creativemacmac** [codercom/code-server#194]
Hey there folks
I can't get the terminal to load. I am trying to get the live preview in default browser to work by right clicking on my index.html but it is just giving me:

The terminal process command '/bin/bash' failed to launch (exit code: 1)

**Comment by PhilsLab** [comment]
Can you clarify:
- What OS does your server use?
- Do you use the docker image?
- Is bash installed on your system?

**Comment by creativemacmac** [comment]
Hey there Phil :)
Have I asked this question in the wrong place? visual studio code on my local machine which is pc windows 10 is working just fine. What is am struggling to get to work is:
https://ide.coder.com/

**Comment by PhilsLab** [comment]
This is the on-premise, selfhosted version of that project. You might want to contact the coder.com support, as this is not the same product.

**Comment by creativemacmac** [comment]
thanks a mil for clarifying :) my apologies for the inconvenience

**Comment by nol166** [comment]
moved to: https://github.com/codercom/code-server/issues/194

**Comment by uknowzheng** [comment]
i have a same question that don't open the terminal
