### ISSUE TITLE
Open File Looking bad on dark theme

### ISSUE THREAD

**Issue by andreimc** [codercom/code-server#195]
- `code-server` version: code 1.32.1
- OS Version: Ubuntu 18.04

## Description

The file open menu doesn't look proper

## Steps to Reproduce

1. Set dark theme in settings ```	"workbench.colorTheme": "Solarized Dark",```
2. Open file menu

<img width="1099" alt="Screen Shot 2019-03-11 at 4 56 24 pm" src="https://user-images.githubusercontent.com/1446134/54115297-c701c380-441e-11e9-83c9-73e1455276d9.png">

**Comment by avelino** [comment]
@andreimc set theme URL pls

**Comment by andreimc** [comment]
@avelino what do you mean ?

**Comment by nol166** [comment]
I think he means post a link to the extension for the theme (if you were using one) @andreimc

**Comment by kylecarbs** [comment]
Will be fixed in new release.

**Comment by andreimc** [comment]
has been fixed
