### ISSUE TITLE
Why is --experimental-repl-await flag not allowed in NODE_OPTIONS?

### ISSUE THREAD

**Issue by KSXGitHub** [codercom/code-server#197]
## Description

I set `$NODE_OPTIONS` (environment variable) to contain `--experimental-repl-await` for convenience (when using Node.js repl), but `code-server` complains about it.

Is there any reason why this rule is strictly necessary?

**Comment by kylecarbs** [comment]
Not sure what context this is in.

Are you attempting to run a JS file?

**Comment by KSXGitHub** [comment]
I download the binary and execute that binary. 

For context, I use Linux.

**Comment by sr229** [comment]
@KSXGitHub this is the incorrect place to ask. This should be forwarded to [Node.js](https://github.com/nodejs/nodejs).
