### ISSUE TITLE
Traefik reverse proxy, gateway timeout

### ISSUE THREAD

**Issue by StiviiK** [codercom/code-server#202]
- `code-server` version: latest tag, `server/0.0.0 linux-x64 node-v8.15.0`

## Description
Tried running it behind Traefik reverse proxy. If i browse to my url i get a `gateway timeout`.
In the traefik dashboard it looks correctly configured:
![image](https://user-images.githubusercontent.com/8115642/54154518-58366180-4442-11e9-94fe-dde33787733a.png)
![image](https://user-images.githubusercontent.com/8115642/54154520-5a002500-4442-11e9-8ca8-a22ed23b0313.png)
Running `curl http://172.17.0.2:8443` on the remote host works:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

If i expose the 8443 port publicly and browse to the ip + port it also works fine (with http)

## Steps to Reproduce

1. Create a Traefik reverse proxy (https://github.com/containous/traefik)
2. Try running code-server with following command:
`docker run -d --label traefik.port=8443 --label traefik.frontend.rule=Host:ide.DOMAIN.TLD codercom/code-server --allow-http`

**Comment by StiviiK** [comment]
Nvm. I was just stupid myself, if you are wondering about the issue i missed setting the correct network.

**Comment by umdstu** [comment]
What do you mean by missed setting the correct network? I'm having the same response to GET / with docker nginx egresses.

**Comment by StiviiK** [comment]
I have traefik running in a docker network and i forgot to "put" the `code-server` in the same docker network.

**Comment by warllo54** [comment]
@ would you be willing to share your relevant config for this. My proxy seems to be working as I can access  code-server using my domain name however all https redirects to http. I have several other containers working with traefik.

**Comment by StiviiK** [comment]
@warllo54 this seems like a lot of options you require to get it working, which seems odd. Maybe i'll find my own config because i only evaluated `code-server`.

**Comment by redge76** [comment]
Ok if you come here because you try to use the docker-compose in https://hub.docker.com/r/linuxserver/code-server ... Don't be as stupid as me (or StiviiK  I guess) Don't forget to add the "netword:" directive....... !
