### ISSUE TITLE
Git in docker container. 

### ISSUE THREAD

**Issue by greenfox1505** [codercom/code-server#203]
I believe Git just be installed by default in the docker container. Git integration is a core feature of VSCode. It's easy to add `apt-get install git` without significant complication or inflation of the docker image.

**Comment by jeasonstudio** [comment]
sgtm

**Comment by sr229** [comment]
actually there's some inflation but its not detriminal as git itself is very lightweight.

**Comment by greenfox1505** [comment]
I'M HOME, it's not *significant* inflation.

**Comment by SuperSandro2000** [comment]
Maybe it would be a good idea for future additions to add a bare bone image for people like me that wan't to save drive space and a more featured image.
If we base the more featured image on the barer one we could make the building process really easy.

**Comment by nhooyr** [comment]
Opened #234
