### ISSUE TITLE
Paste does not work when applied to selected text

### ISSUE THREAD

**Issue by PhilipXue** [codercom/code-server#207]
- `code-server` version: ~/code-server-1.31.1-100-linux-x64
- OS Version: Ubuntu 18.04

## Description
The ctrl+v paste or right click paste doesn't work when a string of text is selected, the content in clipboard doesn't replace the text selected.

**Comment by willyarisky** [comment]
Read a reply from avelino on #161

**Comment by kylecarbs** [comment]
I've noticed this as well. This behaviour definitely isn't expected. Will fix.

cc: @coderasher

**Comment by PhilipXue** [comment]
Thanks @willyarisky @kylecarbs , I set the config as avelino commented and it works.
This behavior as default is counterintuitive, hope this will be improved in next version.
Closing this issue.
