### ISSUE TITLE
Page should reload if SSH disconnects

### ISSUE THREAD

**Issue by ammario** [codercom/code-server#216]
Currently, the terminal just freezes forcing the developer to create a new one.

A better UX would be seamless disconnect handling, but that apparently requires changing a lot of VS Code's plumbing which we don't have the bandwidth to do at the moment.

**Comment by ammario** [comment]
Marking this as urgent as it frequently causes the `ide.coder.com` terminal to freeze.

**Comment by sr229** [comment]
I don't agree having the whole page to reload. Just reset the terminal buffer, or if the session is recoverable, reconnect on the session @ammario

**Comment by sr229** [comment]
this is how we do the terminal states in Theia, and clearly the approach you're going for is very detriminal for developer UX

**Comment by ammario** [comment]
Those solutions would be better if they're easily implemented, cc @kylecarbs

**Comment by kylecarbs** [comment]
We can reset the terminals fairly easily, but there arises a larger issue with reconnecting the extension host.

**Comment by kylecarbs** [comment]
We now reconnect :confetti_ball:
