### ISSUE TITLE
default directory of extensions seems to be wrong

### ISSUE THREAD

**Issue by guyuxiang** [codercom/code-server#218]
- `code-server` version: server/development linux-x64 node-v8.15.0
- OS Version: source, ubuntu, Dockerfile

## Description

The default directory of extensions seems to be wrong, 
which is in the file `/packages/vscode/src/fill/products.ts`
`dataFolderName: ".code-server",`

I guess it should be:
``dataFolderName: ".local/share/.code-server",``

## Steps to Reproduce

1. `docker build` using the Dockerfile
2. `docker run`
3. In docker, just `coder-server`, without specifying the data_dir and extensions_dir.
3. Install any extension.
3. The extensions are found in `/root/.code-server/extensions`, not `/root/.local/share/.code-server/extensions`. The data_dir is still the default `/root/.local/share/.code-server`, which is correct.

**Comment by HiZhaoxiaoyang** [comment]
cool。i choose vim.

**Comment by foresthoffman** [comment]
@guyuxiang What are the first-level contents of `.local/share/.code-server` and `.code-server` when this occurs?

**Comment by guyuxiang** [comment]
@foresthoffman 
Thanks. I should have be more clear. 
First level is `/root`. It occurs when I start with `coder-server` without specifying data_dir and extension_dir.

**Comment by coderasher** [comment]
This was fixed in https://github.com/codercom/code-server/commit/e597d49912fc0299877899fe687b69da5214794d#diff-4ae0f28b342b8e36b03041e34e5e3339R11 which is included in version 1.32.0-245, but I'm not sure what version the Docker build is using.

**Comment by foresthoffman** [comment]
[Latest](https://hub.docker.com/r/codercom/code-server/tags) was updated 16 minutes ago.

**Comment by guyuxiang** [comment]
@coderasher @foresthoffman Yes. It is fixed. Thanks. I am closing this issue.
