### ISSUE TITLE
Split Terminal not working

### ISSUE THREAD

**Issue by pjoe** [codercom/code-server#219]
- `code-server` version: Hosted version on coder.com
- OS Version: The terminal says ubuntu 16.04, guessing it's running in docker container

## Description

Clicking the Split Terminal icon in vscode does not work (Windows, Chrome 72.0.3626.121)

## Steps to Reproduce

1. Have vscode Terminal Output open
1. Click Split Terminal
1. Nothing happens, no output in js console :S

**Comment by mitchellurgero** [comment]
I have this running on Cloudron with an 18.04 Docker image. It works for me. Might be specific to coder.com or 16.04. (Assuming this is what you meant, here is a screenshot.

![image](https://user-images.githubusercontent.com/4168998/54288388-6042ee00-4575-11e9-923f-c8342591811c.png)

**Comment by pjoe** [comment]
Yes that is exactly what I meant, is there anyway to determine which code-server version is running on coder.com?

FWIW: Also fails on Chrome 73.0.3683.75

**Comment by mitchellurgero** [comment]
Not that I know of, the "About" option is "Not implemented" yet.

**Comment by mitchellurgero** [comment]
I'd like to point out I have tested only on releases 1.31.1-100 & 1.32.0-245.

**Comment by Rakiah** [comment]
not working for me neither using the codercom/code-server docker image (no tag specified)

**Comment by shi-yan** [comment]
I have this issue too.

I print lsb_release within the vscode terminal:

root@9bd08804e3b8:~/project/code-server# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

**Comment by kylecarbs** [comment]
This doesn't appear to be an issue anymore. Please reopen if you find it to be!
