### ISSUE TITLE
Dependency `spdlog` missing 

### ISSUE THREAD

**Issue by barretlee** [codercom/code-server#22]
- `code-server` version: 1d8da2161f4330e2cf26fd28005729e3b6e21286
- OS Version: Darwin Kernel Version 17.7.0

#### Steps to Reproduce

1. `yarn; yarn start;`, then throw TS Compile Error
2. Missing dependency `spdlog`: https://github.com/codercom/code-server/blob/master/packages/protocol/src/common/helpers.ts#L1

**Comment by kylecarbs** [comment]
Hmm. Did all sub-packages install correctly? `spdlog` is required by `packages/protocol`.

**Comment by barretlee** [comment]
Lost one step in yarn postinstall script, the dependency `microsoft/vscode` is not installed.

**Comment by kylecarbs** [comment]
Interesting. Did you run `yarn` in the root of the repository?

**Comment by barretlee** [comment]
Yeap, i runned in root path.

And i don't think it is necessary to clone the entire repository. You can just clone the tag/1.13.0 branch of `vscode`. I will give you a PR.

**Comment by kylecarbs** [comment]
Ah this makes sense. You'll need to manually run `yarn` inside the cloned vscode for that reference to exist. Will fix!

**Comment by kylecarbs** [comment]
Closing in favor of discussion in PR
