### ISSUE TITLE
Terminal does not load user paths or env variables

### ISSUE THREAD

**Issue by tvarwig** [codercom/code-server#226]
- `code-server` version:1.32.0-245
- OS Version: Ubuntu 18.04

## Description

Custom binary paths are not loading from the users `.profile` or `/etc/profile` on ubuntu. For example, I have `go` installed on the ubuntu machine. In my `~/.profile`, I have the path to `export PATH=$GOPATH/bin:$GOROOT/bin:$PATH`. On a standard ssh terminal the `go` binary loads. The terminal in VSCode does not load any custom paths. I have to run `source ~/.profile`. This has to be done on each load of a new terminal.

## Steps to Reproduce
1. `go` -- Output `Command 'go' not found,`
2. `source ~/.profile`
3. `go version` -- Output: `go version go1.12 linux/amd64`

**Comment by sr229** [comment]
hey @tvarwig, was this running on your own user, yes?

**Comment by tvarwig** [comment]
@sr229 Yes as a non root user

**Comment by sr229** [comment]
FWIW it should load that properly since its user shell bound. Was this in Docker or a bare installation?

**Comment by tvarwig** [comment]
Bare installation with `systemd` on Ubuntu 18.04. I have the `User=myusername` under `System`. The terminal says `mysername@myhostname:`.

**Comment by bketelsen** [comment]
systemd doesn't get your environment.  You need to use the Environment or EnvironmentFile directives to set environment variables. Quick (probably foolish) hack would be to `env > myenv` then add `EnvironmentFile=/path/to/myenv` which would get the currently set environment variables.  Beware, that might be a security risk.

**Comment by tvarwig** [comment]
@bketelsen thank you for the information. I assummed since the terminal in VSCode loaded with my username the envirnment would like like the desktop app.

**Comment by alexfornuto** [comment]
Sorry to comment on such an old thread, but it's the closest I've found to a solution for myself. @bketelsen, could you expand on how someone using code-server as a system service could modify the daemon to use the user's environment?

Context: My instance of code-server is secured via an identity-aware proxy, so I'm not worried about the security risk. The values in my `$PATH` are different between the terminal in code-server and the one I get from an SSH session.
