### ISSUE TITLE
Electron buttons (close, minimize to tray, etc) buttons visible in browser

### ISSUE THREAD

**Issue by avirupdutta** [codercom/code-server#227]
- `code-server` version: 
- OS Version: 

## Description

The window doesn't seems to close, minimize or maximize... NO BUTTONS ARE WORKING!

## Steps to Reproduce

step 1: open the text editor 
step 2: try to close the window using 'X' button at the top right corner.

**Comment by sr229** [comment]
@avirupdutta this is a Electron-specific button, keep in mind `code-server` is quite early (yet usable), so expect some Electron stuff not yet removed during the porting process.

**Comment by avirupdutta** [comment]
Yeahh I can understand your pov... but the matter is I'm super excited to use code-server... so waiting for the bug fixes is intimidating

**Comment by sr229** [comment]
CC @coadler can we reopen this? We need to track this issue to make sure we remove those specific buttons

**Comment by avirupdutta** [comment]
i know they are visible to the browser but they doesn't seem to work when clicked

**Comment by kylecarbs** [comment]
Fixed!
