### ISSUE TITLE
Share same session across multiple computers

### ISSUE THREAD

**Issue by jrpub** [codercom/code-server#228]
Working on computer A, I would like to leave the computer A and find exactly the same environment on my other computer B (opened file, cursor location, console status, etc.). 

It would be a nice feature!

**Comment by nol166** [comment]
This is a great idea

**Comment by kylecarbs** [comment]
This should be fixed now. Workspace state now saves!

**Comment by I0x0I** [comment]
It's still unclear to me how to share workspace states across different browsers/machines. Is it related to #4212 ?

**Comment by code-asher** [comment]
Yeah, that is related.  I do not think it is currently possible to share state.
