### ISSUE TITLE
bare bones docker image

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#234]
https://github.com/codercom/code-server/issues/203#issuecomment-472593417

**Comment by nhooyr** [comment]
Idk if we should do this though, disk space is super cheap.

**Comment by SuperSandro2000** [comment]
Right now the image is 305 MB according to Portainer. I think that is already quite some size and I hope that is not increasing to much in the future.

**Comment by nhooyr** [comment]
How about we just add an alpine variant? I think that'd be reasonable.

**Comment by sr229** [comment]
We'll need to compile releases for Alpine as well or include `libc6-compat` if that's the case

**Comment by SuperSandro2000** [comment]
I am currently building an Alpine image. It just needs some testing if it actually works.

**Comment by sr229** [comment]
@nhooyr we have two ways to make our images smaller:

- use debian-slim/buildpack-deps images
- use Alpine

My image used to be sid-slim but people wanted a Ubuntu image. It's quite small.

**Comment by SuperSandro2000** [comment]
Just FYI theia is 264 MB. I think the size is reasonable but it shouldn't increase to much. I still would love to try squeezing every MB out of it.

**Comment by sr229** [comment]
@nhooyr @SuperSandro2000 We need to keep in mind though, Alpine uses musl libc so package availability is not guranteed.

**Comment by SuperSandro2000** [comment]
@sr229 In the almost 2 years now I use docker images I found one package that wasn't available for alpine. I don't think that will be an issue if we use common packages.

**Comment by SuperSandro2000** [comment]
I did some more testing today and the resulting binary is linked against libc. I am currently trying some comp packages but as far as I can assess it as long as we use nexe we can't really build a alpine image in a reasonable amount of time.

**Comment by milanchotai** [comment]
I've tried to use `code-server` with Alpine, but have run into various issues, so just wanted to check if this thread was still active.

**Comment by SuperSandro2000** [comment]
@milanchotai IIRC The old binary creator linked it against libc from Ubuntu and mot muslc. I don't know about the new packager.

**Comment by kylecarbs** [comment]
I'm opposed to this for now. Alpine builds are still on the roadmap though (coming quite soon)!

**Comment by sweepyoface** [comment]
Status on Alpine builds?

**Comment by deansheather** [comment]
@sweepyoface try out the musl release on Alpine.

**Comment by sweepyoface** [comment]
Thanks, but I was thinking more along the lines of an official Docker image so I don't have to do things like this:

```sh
RUN export CODE_SERVER_VERSION=$(curl -s https://api.github.com/repos/cdr/code-server/releases/latest | jq -r .tag_name) \
    && wget https://github.com/cdr/code-server/releases/download/"$CODE_SERVER_VERSION"/code-server"$CODE_SERVER_VERSION"-musl-x64.tar.gz \
    && tar xzvf code-server*.tar.gz \
    && cp code-server*/code-server /usr/local/bin \
    && chmod +x /usr/local/bin/code-server \
    && rm -r code-server*
```
Because as it stands I don't know how to build the musl version from source.

**Comment by deansheather** [comment]
Something like the following should work, although I haven't tested.
```
export VSCODE_VERSION="1.33.1" MAJOR_VERSION="1" VERSION="$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER-vsc$VSCODE_VERSION" TARGET="alpine"
scripts/build.sh
```
