### ISSUE TITLE
TOTP auth support

### ISSUE THREAD

**Issue by korzq** [codercom/code-server#235]
It would be great to have TOTP auth support for more security.

**Comment by SuperSandro2000** [comment]
Simple fix would be to secure it behind a proxy that supports that.

**Comment by kylecarbs** [comment]
We likely won't implement this into code-server unless highly requested.

**Comment by metorm** [comment]
> Simple fix would be to secure it behind a proxy that supports that.

Could you please give an example? I think reverse proxies such as Caddy usually provide the data as it is.

**Comment by ezrizhu** [comment]
> Could you please give an example? I think reverse proxies such as Caddy usually provide the data as it is.


https://www.authelia.com/
