### ISSUE TITLE
General requirements for installing extensions in hosted version?

### ISSUE THREAD

**Issue by ChristianWeyer** [codercom/code-server#242]
https://ide.coder.com/

What are the general requirements for extensions to be installable in the hosted version ode Coder?

E.g., I tried Azure Functions (ms-azuretools.vscode-azurefunctions) and it failed:
`Cannot read property 'local' of undefined`

Thank you!

**Comment by Multishifties** [comment]
@foresthoffman

**Comment by foresthoffman** [comment]
The general prerequisite is that they are compilable via the `vsce` tool that Microsoft maintains. The current version of this extension (that we're hosting) appears to fail compilation, so I'll dig deeper into this.

**Comment by ChristianWeyer** [comment]
Thanks for looking into this.
Did you already have some time to dig deeper @foresthoffman ?

**Comment by foresthoffman** [comment]
Will look into this today! @ChristianWeyer

**Comment by foresthoffman** [comment]
The version we currently have is in an unusual state, the format is quite broken. I've taken it down for now, will have to debug more tomorrow.

**Comment by foresthoffman** [comment]
@ChristianWeyer The extension should be up in roughly an hour. I was running into some inconsistent issues with packaging the source. I'm curious to know if it functions for your use case.

**Comment by ChristianWeyer** [comment]
Thank you.
Just tried and still get the same error:
![image](https://user-images.githubusercontent.com/888718/54862691-b87cab80-4d3e-11e9-8945-e0d87f8bcfc2.png)

**Comment by kylecarbs** [comment]
The hosted version will be going away soon, if issues exist with installing the azurefunctions extension, another issue should be made for that!
