### ISSUE TITLE
Activating extension 'Dart-Code.dart-code' failed: Cannot find module 'glob'.

### ISSUE THREAD

**Issue by DanTup** [codercom/code-server#244]
I installed the Dart extension (I'm the author of it) in the online version (https://ide.coder.com/) but it failed to activate with the error above. The extension works fine in standard VS Code (glob is an NPM package used by the extension).

Note: I don't really expect the extension to work that much, because it requires a Dart SDK - I was mainly just curious what would happen (I didn't expect it to fail quite this early on :-)).

**Comment by foresthoffman** [comment]
I'll look into this, thanks!

**Comment by sionicion** [comment]
@DanTup, I was just lurking through here and this is a little unrelated, but I'm tinkering right now with getting this working so I can work from my Pixelbook without a massive performance hit compared to my desktop. I was able to install the Flutter and Dart extensions, but the Flutter extension doesn't appear to be kicking in, I manually specified the Flutter SDK but no luck.

If the server has the Flutter and Dart SDK installed, is it possible to get a working configuration currently based off your experiences?

**Comment by DanTup** [comment]
> I was able to install the Flutter and Dart extensions, but the Flutter extension doesn't appear to be kicking in, I manually specified the Flutter SDK but no luck.

Are you just hitting the same issue I mentioned above? If you open the DevTools do you see the same message?

> If the server has the Flutter and Dart SDK installed, is it possible to get a working configuration currently based off your experiences?

My only experience so far was installing the Dart extension and it failing with the error above, so right now it doesn't seem to work. However, I don't see any real reason it couldn't be made to work if bugs like this can be quashed. I'm not sure you'd be able to launch a Flutter app any useful, but I don't see why the editing etc. wouldn't work.

I'm happy to assist if I can, including tweaking the extension (within reason) if there are things preventing it from working here.

**Comment by sionicion** [comment]
I'll have to look at it again and see. It probably was now that I think about it. I think when I first scanned over this issue, I was thinking this affected just the cloud version not the self-hosted version.

But I do see this as extremely useful because the only laptop I have is the Pixelbook. And I'd rather work with that then replace it. Plus I can run apps right on it. I was able to connect to it via ADB in the terminal and then run Flutter in the Coder instance. So like if the code editing features worked, that would be good enough.

**Comment by DanTup** [comment]
> I think when I first scanned over this issue, I was thinking this affected just the cloud version not the self-hosted version.

Ah, I see - I did mention that just as additional info, though I wouldn't expect it to make a difference.

> But I do see this as extremely useful because the only laptop I have is the Pixelbook. And I'd rather work with that then replace it. Plus I can run apps right on it. I was able to connect to it via ADB in the terminal and then run Flutter in the Coder instance.

I'm a little confused about your setup. Are you running this project on your Pixelbook? If so, what advantage does that have over just running VS Code/etc normally?

**Comment by sionicion** [comment]
No I'm running the Coder server on my desktop (Core i7, 16GB RAM, Hackintosh) and accessing it from my Pixelbook over the LAN.

Then I'm using the terminal on the Coder site (which is just my desktop on the LAN) to ADB in to my Pixelbook so I can deploy the APKs to my Pixelbook.

I've done this with VS Code Live Share but that still required the VS Code running in the Linux VM on the Pixelbook. And honestly what stops me from coding on the Pixelbook is this lag when typing, and the suggestions. It takes way too long that I give up essentially. But what I like about this is it eliminates the need for the Linux VM and can do all the heavy lifting on a more powerful computer.

**Comment by DanTup** [comment]
> No I'm running the Coder server on my desktop

Aha, gotcha :-)

I don't have a Pixelbook so I can't vouch for the performance, but I have seen some articles from people running it all locally. Otherwise, what you've done seems like a decent workaround though.

If things don't seem to work once this issue is resolved, feel free to ping me. It'd definitely be neat to have it work :-)

**Comment by sionicion** [comment]
Okay will do, and you are right, I just got around to testing this out again and seeing what is displayed in the devtools and it is this issue stopping the extensions from activating.

**Comment by sionicion** [comment]
In my limited testing, looks like Flutter is working! Haven't had a chance to experiment with actual usage but the Flutter and Dart plugins are working now. I can't get the Flutter SDK installed using the online Coder site but I think that has to do with some other issue, maybe storage constraints?

But I was in fact able to get Coder on my own system working with the Flutter SDK. I'll play around with this soon!

**Comment by DanTup** [comment]
Yeah, looks like this issue is fixed, the extension does activate :)

I also couldn't get Flutter working though. It needs `unzip` so I installed that:

```
git clone https://github.com/flutter/flutter
sudo apt-get install unzip
./flutter/bin/flutter doctor
```

However it seems to hang on "Building Flutter tool". I left it many minutes but it never seemed to complete :(

> maybe storage constraints?

I don't think it's storage, I can see 1.7GB free in the status bar. Apparently it is using 350% CPU and 2/2GB RAM though! :/

**Comment by DanTup** [comment]
Oh, then this happened :(

![fail](https://user-images.githubusercontent.com/1078012/56420407-c79b3e80-6295-11e9-912e-304dd770ad30.png)

**Comment by sionicion** [comment]
Why don't you try running code-server on your own VM? I was able to spend a little more time on this today and I was able to wireless ADB into my Pixel 3 and compile straight from code-server, hot reloading and all! Super excited about this!!

**Comment by DanTup** [comment]
> Why don't you try running code-server on your own VM? 

Mainly just because I have no need, I run everything locally. My attempts to play with this were only out of curiosity (and I wanted to make sure my extensions didn't unnecessarily fail to run here). If there are issues with the Dart/Flutter extensions I'll certainly try to resolve them, but troubleshooting why these containers seem to crash when setting up Flutter is a bit out of scope (and also probably something I couldn't easily debug).

I'll close this since this it seems like the original issue is resolve - but if anyone wants to try and use Flutter and hits the issue I did, it's probably worth opening another issue for it.

**Comment by foresthoffman** [comment]
Thanks @DanTup!

**Comment by tboyce021** [comment]
I'm trying to set up Flutter and everything seems to be working except that VS Code never recognizes my adb device. I can connect over the network via the terminal and use "flutter run", but VS Code still says "No Devices".

Any ideas why that would be or how to debug the VS Code side?

**Comment by DanTup** [comment]
@tboyce021 Great, glad to hear it! :)

If you do have any problems, feel free to open issues in the Dart-Code repo and I'll try and help (I can't make promises as this isn't specifically a supported configuration, but it's in my interests to make things work in many places as possible :-)).
