### ISSUE TITLE
A file shouldn't be opened as a folder

### ISSUE THREAD

**Issue by outloudvi** [codercom/code-server#249]
- `code-server` version: Docker version
- OS Version: Ubuntu 18.10 (docker); Manjaro Linux (host)

## Description
User should not be able to open a file in "Open Folder". This doesn't work and brings about some side-effects (like the terminal won't open with an error of "chdir: not a directory").

## Steps to Reproduce

1. "File" > "Open Folder..."
2. Select a file

**Comment by nol166** [comment]
Interesting. The open folder option seems to be missing on Mac.

**Comment by Kiricon** [comment]
> Interesting. The open folder option seems to be missing on Mac.

I am having this exact same issue

**Comment by Multishifties** [comment]
@Kiricon What version of the binary are you running?

**Comment by code-asher** [comment]
VS Code displays different options based on OS. We will most likely unify them: https://github.com/codercom/code-server/issues/501
