### ISSUE TITLE
more secure default setup

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#25]
The default usage for code-server should be a command to ssh into a server and setup the code-server and open a reverse ssh tunnel from code-server to a local host port that the user can access code-server through.

This way no password.

**Comment by ammario** [comment]
Another idea we had was oAuth with Google

**Comment by nhooyr** [comment]
What would the advantages of that be?

**Comment by ammario** [comment]
No need to memorize or manage another password

**Comment by sn0n** [comment]
Unless user avoids Google Inc services because tracking and what not... #NotMeButSomeone

**Comment by ammario** [comment]
Well, eventually we could support multiple providers.

This would also make it easier to share access to a dev environment.

**Comment by sr229** [comment]
This seems just adding more complexity fwiw, I don't like this approach and most IDEs don't do it as well (Theia for instance doesn't have Auth, but they plan to have a basic one soon, Theia with Auth is basically in Che 7). Use a OAuth provider or a Basic auth strategy instead (Passport.js preferred since we can just plug a new auth strategy with Passport).

**Comment by nhooyr** [comment]
@sr229 thats fine for some deployments but you could want a quick and easy setup which is what this accomplishes.

@ammario that seems fine to me, I'd prefer we go with `Github` as the default provider though just cause it fits the domain better.

**Comment by kylecarbs** [comment]
We introduce a configuration when adding OAuth providers.

We'll need to have a discussion on the best way to provide this.

**Comment by mxplusb** [comment]
I have a use case where I'd definitely want to lock code-server behind an [OpenID-compliant authentication system](https://login.gov), so this is very valuable for me.

**Comment by nhooyr** [comment]
Btw, this issue has been solved with `sshcode`.

**Comment by nhooyr** [comment]
I think its best for OAuth providers and stuff to be behind a reverse proxy, there are quite a few options and Cloudflare also has support.

@mxplusb Could you open a new issue with details on what you'd like? Its not clear to me why you can't already lock code-server behind an OpenID compliant authentication system.

**Comment by boardfish** [comment]
I'd still really like generic OAuth support as a feature. OpenID Connect support would also cover most use cases. It's worth checking out [CodiMD's implementation](https://github.com/hackmdio/codimd/blob/4e596d724dcb1a5a19ab1e75df250767334ebfc9/lib/web/auth/openid/index.js) for inspiration.
