### ISSUE TITLE
Setting icon theme to none doesn't work

### ISSUE THREAD

**Issue by PassTheMayo** [codercom/code-server#251]
- `code-server` version: 1.32.0-275
- OS Version: Ubuntu 16.04.6 LTS

## Description

Setting the icon theme to None using the `File > Preferences > File Icon Theme` doesn't work at all, nothing changes. It doesn't seem to be applying, because it goes to the last option upon reloading.

## Steps to Reproduce

1. File > Preferences > File Icon Theme > None

**Comment by PassTheMayo** [comment]
@kylecarbs Why was this closed? It's still an active issue

**Comment by kylecarbs** [comment]
Oops. Accidentally tagged the incorrect issue.

**Comment by nol166** [comment]
For some reason, this doesn't seem to get set in local storage, unlike color theme data. Will fix.

**Comment by kylecarbs** [comment]
Seems like this should be fixed in the latest release!
