### ISSUE TITLE
Debugging Go does not work

### ISSUE THREAD

**Issue by iptaylortechnical** [codercom/code-server#252]
- `code-server` version: 
```bash
$ code-server --version
server/development linux-x64 node-v8.15.0
```
- OS Version: 
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
...
```

## Description

Cannot debug Go. It stays in a loop for a while, cannot find any log failures.

## Steps to Reproduce

1. Start the server and log in
2. Write a go file
3. Add a breakpoint somewhere
4. Click "debug"
5. Hit "run"

**Comment by kylecarbs** [comment]
Will fix ASAP!

**Comment by davefinster** [comment]
This seems similar to #210 - at least from my experience in attempting Go debugging.

**Comment by Rakiah** [comment]
I have the same problem with trying to debug an application in .NET Core 2.1 inside a container

**Comment by Rakiah** [comment]
Any update on how this can be fixed ?
This prevents our adoption of code-server in our company

**Comment by kylecarbs** [comment]
Will be fixed within a few hours.

**Comment by kylecarbs** [comment]
Fixed with the latest release [1.32.0-310](https://github.com/codercom/code-server/releases/tag/1.32.0-310)!

**Comment by Rakiah** [comment]
That's great, will try asap
Just to know: I can just run ```git pull && docker built -t codercom/code-server .```
to use the docker version of code-server with the available fix ?

**Comment by kylecarbs** [comment]
Yup that's correct. I'm updating the image on docker hub right now.

**Comment by iptaylortechnical** [comment]
I appreciate the quick work on this. Sorry for my delay. The environment that I am working on has a kernel that is too old to support Ubuntu 18, so I had to fork this repo and back port to Ubuntu 16. I'll try to merge these changes soon and let you know if it fixed it for me.
