### ISSUE TITLE
Drag and drop action leads to cannot parse time error

### ISSUE THREAD

**Issue by ihainan** [codercom/code-server#253]
- `code-server` version: 1.31.0-20-x86_64-linux
- OS Version: Ubuntu 18.04.1 LTS
- Client Info: macOS 10.14.3  + Chrome 72.0.3626.121

## Description

Drag n' drop action leads to `Cannot parse time` error:

![image](https://user-images.githubusercontent.com/3169221/54410947-7a70fd80-4728-11e9-89e9-79b4ca41b5be.png)

## Steps to Reproduce

Drag a file and drop it to another directory.

I've recorded [a video](https://youtu.be/bmQ6t6nLPes).

**Comment by nol166** [comment]
Thank you for reporting this, looking into it now
