### ISSUE TITLE
password needs to be securely generated

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#26]
See https://github.com/codercom/code-server/pull/5/files#r262790187

**Comment by nhooyr** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Comment by NGTmeaty** [comment]
Oops sorry, I brought up the same concerns here: https://github.com/codercom/code-server/issues/4#issuecomment-470154386

**Comment by Multishifties** [comment]
@nhooyr Given this is in the CLI, I don't believe the `window` scope may be accessible. However we may be able to use https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_randomfillsync_buffer_offset_size instead. It's similar in that according to the docs it also generates cryptographically strong pseudo-random data.
