### ISSUE TITLE
Cannot find module when BUILD:DEFAULT-EXTENSIONS on centos7

### ISSUE THREAD

**Issue by seuliang** [codercom/code-server#263]
Cannot find module when BUILD:DEFAULT-EXTENSIONS on centos7.
There is no file in folder code-server/lib/vscode-default-extensions/build/lib.
Maybe there are mistakes in build/tasks.ts.

**Comment by sr229** [comment]
have you tried running a Submodule update and init?

**Comment by foresthoffman** [comment]
Hello @seuliang,

You'll have to run `build:server:binary` first. That will generate the default extensions.

Thanks,
Forest

**Comment by seuliang** [comment]
Thank you
It seems default extensions are copy from vscode. 
I'd like to know what is default extensions, why we need that

**Comment by Aaaaash** [comment]
@seuliang Default extensions is builtin in vscode bundle, vscode need default extensions to provide basic language support.

**Comment by foresthoffman** [comment]
It sounds like this has been dealt with, so i'll be closing this. Thanks!
