### ISSUE TITLE
[Feature Request] Remove/Disable Telemetry like VS Codium

### ISSUE THREAD

**Issue by 4oo4** [codercom/code-server#268]
Hey there, first wanted to say that this is awesome! I had been using Theia up until I found this, really happy with how much easier this is to build and how much smaller the docker image ends up being, with a better UX overall.

However, I wanted to ask if it could be possible to disable telemetry, similar to how VS Codium does? Judging by [this](https://github.com/VSCodium/vscodium/blob/master/undo_telemetry.sh) it looks pretty simple to do, I know that you can disable telemetry in settings, but with how invasive Microsoft is, it would make me feel a lot safer to just not include it in the first place.

Cheers

**Comment by NGTmeaty** [comment]
Personally, while I see the reason to remove it entirely, I don't think we should remove it entirely. I imagine there would be other privacy implications from Microsoft with not actually disabling telemetry after hitting the setting.

**Comment by kylecarbs** [comment]
We don't send telemetry at all.

**Comment by 4oo4** [comment]
@kylecarbs I know you guys don't, I'm just making sure there's nothing left over from Microsoft's code that would do that. Looking a little bit deeper at the VS Codium readme, it looks like the telemetry endpoints are disabled in the product.json if you're just pulling code from them, but they also mention a build flag that disables it. Is that what you happen to do also?

**Comment by kylecarbs** [comment]
Yeah, we don't include the telemetry URL. No reqs _should_ be made to Microsoft.

**Comment by 4oo4** [comment]
@kylecarbs Awesome, I'll close this for now unless someone can see it actually making telemetry requests. Thanks!

**Comment by TomFreudenberg** [comment]
Hi @kylecarbs @4oo4 

Is this still true?

> Yeah, we don't include the telemetry URL. No reqs should be made to Microsoft.

In my default settings "Telemetry is enabled" in the IDE settings.

If I got it right - "No Telemetry is send either what is the setting" ?

Thanks for another clarification.

And thanks for the work at all !!!

**Comment by nhooyr** [comment]
@TomFreudenberg We collect telemetry instead of sending it to Microsoft.

See https://github.com/cdr/code-server/blob/v3.5.0/doc/FAQ.md#how-can-i-disable-telemetry
