### ISSUE TITLE
discord badge in README.md doesn't support high resolution displays

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#27]
<img width="1630" alt="screen shot 2019-03-05 at 11 57 54 pm" src="https://user-images.githubusercontent.com/10180857/53856994-8af3dc00-3fa2-11e9-98f8-57db5d73091f.png">

Noticeably more fuzzy than the others.

**Comment by kylecarbs** [comment]
cc: @coadler

**Comment by coadler** [comment]
Yea I noticed that a bit earlier. Will see if there is a higher res version in the morning

**Comment by NGTmeaty** [comment]
From what I can see, Discord doesn't really provide any other resolutions, they do provide different styles. 

https://discordapp.com/developers/docs/resources/guild#get-guild-widget-image

**Comment by NGTmeaty** [comment]
#364 merged. Recommending close.
