### ISSUE TITLE
How to use coder.com external ip?

### ISSUE THREAD

**Issue by eladcandroid** [codercom/code-server#270]
I tried to enable my express.js app port with "ufw" but it doesn't work..
![Screen Shot 2019-03-17 at 8 25 14](https://user-images.githubusercontent.com/13297000/54486243-3bf55300-488e-11e9-938e-09913d3b1feb.png)

**Comment by sr229** [comment]
There is a cdr.co provided per user @eladcandroid, you need to ask the support team for yours since getting links via the IDE is not yet available.

**Comment by eladcandroid** [comment]
@sr229 Where can i ask it? (I'm in a free account)

**Comment by sr229** [comment]
Feel free to open a support ticket or ask in the Discord server @eladcandroid.

**Comment by foresthoffman** [comment]
Thanks, @sr229! Going to close this then.
