### ISSUE TITLE
[UriError] Scheme contains illegal characters

### ISSUE THREAD

**Issue by sa7mon** [codercom/code-server#275]
- `code-server` version: Latest Docker: `sha256:067d044e8d977e2149997421a3893dd51eaf037b21fc841955c6d378ab664bd6`
- OS Version
  * Server: Ubuntu Server 18.04.2 LTS
  * Client: MacOS 10.13.6 with Firefox 65.0.1 (x64) and Chrome 67.0.3396.99 (x64)

## Description

Trying to access the IDE in Firefox results in a blank black screen and no IDE. 

## Steps to Reproduce

1. Create new Docker instance with: `docker run -t -p 0.0.0.0:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http`
1. Access `dockerip:8443` in Firefox 
1. Observe a blank black screen
1. Access `dockerip:8443` in Chrome
1. Observe that the IDE loads just fine

Here's a screenshot of the console. My guess is that the code has some ES6 syntax that isn't being transpiled correctly to work with Firefox.

![code-server-no-worky](https://user-images.githubusercontent.com/3712226/54492958-09048c80-4899-11e9-9fac-c52538e65131.png)

![stacktrace](https://user-images.githubusercontent.com/3712226/54492965-0f930400-4899-11e9-8410-93ab92972bde.png)

And here's what it looks like in Chrome (works fine)

![Screen Shot 2019-03-17 at 09 57 47](https://user-images.githubusercontent.com/3712226/54493218-4d912780-489b-11e9-8241-70613590b50d.png)

**Comment by sa7mon** [comment]
Also experiencing a 404 on __webpack_hmr like in #141 but I think that's unrelated.

**Comment by kylecarbs** [comment]
You can remove the `workspace` key from localstorage to temp fix. We'll be pushing a fix soon!

**Comment by sa7mon** [comment]
> You can remove the `workspace` key from localstorage to temp fix. We'll be pushing a fix soon!

Thanks for the temp fix. Worked like a charm! I'll make sure to re-create the container once the fix is pushed.
