### ISSUE TITLE
Debug Python doesn't work 

### ISSUE THREAD

**Issue by Technik-J** [codercom/code-server#276]
- `code-server` version:
```
server/1.32.0-282 linux-x64 node-v8.15.0
```
- OS Version: 
```
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
```

## Description
Debug for Python doesn't work. Stays in a loop forever.

![Screenshot from 2019-03-18 00-44-12](https://user-images.githubusercontent.com/17809291/54497046-e9f90f80-4917-11e9-955e-09cf4b8e6b8f.png)
## Steps to Reproduce

1. Debug python file.

**Comment by davefinster** [comment]
This seems similar to #210

**Comment by sr229** [comment]
Confirmed duplicate of Issue #210.

**Comment by foresthoffman** [comment]
Closing in favor of #210, we'll track the issue there.
