### ISSUE TITLE
How to preview a file

### ISSUE THREAD

**Issue by danleighton** [codercom/code-server#279]
## Description

It appears that, before recent changes, each instance had an associated URL which, presumably, could then be used as a preview of any files.

How is that possible on the new version? I can't find any place within the coder.com hosted version where I can find that unique URL... and therefore can't work out how to see a preview of the files without doing a push to another server.

On my local machine, I use Live Server, not sure how to do that on the hosted version!

Any help appreciated :-)

**Comment by foresthoffman** [comment]
Hello @danleighton,

Since you're using our hosted version, please open a support ticket or drop a comment in the Support channel of our Discord.

Thanks!

**Comment by danleighton** [comment]
Happily will. Can't immediately find your Discord channel. Please let me have the link if possible! 

Many thanks

d.

**Comment by danleighton** [comment]
Ah!

Very well hidden behind a tiny little icon at the bottom of the page:
https://discordapp.com/invite/jvZN2kZ

Thank you!
