### ISSUE TITLE
Do I need GDPR policy for my self-hosted code server?

### ISSUE THREAD

**Issue by Arsaev** [codercom/code-server#281]
I want to have self-hosted codeserver with my domain name connected to it, only for my personal use. But I´m afraid of GDPR. Will I get under some law case if will host it for my self without policy? Sounds  as a dumb question. But, I could not google any reasonable answer for that.

**Comment by coadler** [comment]
I'm not a lawyer but I don't believe GDPR will affect personal use of `code-server`.

**Comment by NGTmeaty** [comment]
I'm not a lawyer and this isn't legal advice, but [Article 2 section 2(c)](https://gdpr-info.eu/art-2-gdpr/) says if it's processing personal data for purely personal activity, GDPR doesn't apply to it.

**Comment by coadler** [comment]
Thanks @NGTmeaty! In my *non-lawyer* opinion, this seems to answer the question.

@Arsaev feel free to reopen if you have more questions
