### ISSUE TITLE
A BIG THANKS AND CONGRATS !!!

### ISSUE THREAD

**Issue by jrpub** [codercom/code-server#283]
Behind this spammy title (sorry for that), I just wanted to share my feedback about code-server. It is just fantastic!

Personally, it changed my way of working. No more git commits just to copy my repository between my various computers, leading to a clear process.

I find the product very stable, and when I work with it, I forgot totally that I am on a webpage. It is fast, it is practical, it is not perfect but honestly, we are not so far. This is probably (already) the best cloud-IDE. 

I regularly test all of them, even vim to see if I can beat my current productivity and process. It is a bit ironic, because I discovered code-server randomly, without any hope, and after a few days of working with it, this is just a "waouh, it rocks". It is already a mandatory product in my very short list. 

So, this post is not an issue or a question - sorry to pollute -  but just one word: congrats to the whole team and to contributors, hoping that a lot of people will join me to this...

### BIG THANK YOU
 
(Feel free to remove this post if needed, I posted it there because you don't even have a contact form on your website :))

**Comment by Multishifties** [comment]
@jrpub I have a PR open that'll re-add the feedback form to our hosted IDE. So that should be taken care of soon. 🙂 

And thank you so much! It means a lot to us that people share our vision of how a cloud IDE should be. Fast, simple, powerful, and predictable.

From the collective CoderHQ team, thank you for testing and using our product!

**Comment by rachel-coder** [comment]
Yay!! Big thank you to you for being on this ride with us! :) the project is still young but we are excited where it is going :) if you need anything we are on our discord to chat <3  ( discord invite link: https://discord.gg/6AmUx9b  )

**Comment by therealkenc** [comment]
Absolutely outstanding. I can confirm that self hosted `code-server` works out of the box on [WSL](https://github.com/Microsoft/WSL). I spun up the [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools) plugin and that works as well. 10,036 github stars as of this writing. Simply an amazing accomplishment. 💯
