### ISSUE TITLE
Setting password with command line parameter makes it visible in ps aux

### ISSUE THREAD

**Issue by kykc** [codercom/code-server#286]
- `code-server` version: 1.32.0-275-linux-x64
- OS Version: Ubuntu 18.04
## Description

Setting password with command line parameter makes it visible in `ps aux`

## Steps to Reproduce
```
./code-server --password=supersecret $CODE_SERVER_ROOT
ps aux
```

## Possible solution

Seems that there's some possible ways to hide it mentioned [here](http://broken-by.me/node-js-change-visible-process-name/)

**Comment by coadler** [comment]
cc @kylecarbs @code-asher

**Comment by kykc** [comment]
Maybe it's also a good idea not to output password into code-server stdout when it's been explicitly set by startup parameter. Should I create a separate issue for that?

**Comment by NGTmeaty** [comment]
We can probably keep it in here because it's related.

**Comment by Multishifties** [comment]
UPDATE: I have a PR for this https://github.com/codercom/code-server/pull/365

**Comment by code-asher** [comment]
The recommended way now to set a password is by using the `PASSWORD` environment variable, which will prevent the password from displaying in the process listing.

https://github.com/codercom/code-server/commit/a3ac4567e39133e736e7e74365f10e9b97861621 also makes it so the password is only logged when it was generated.
