### ISSUE TITLE
How to change password?

### ISSUE THREAD

**Issue by realzhaorong** [codercom/code-server#287]
I deployed code-server on docker, it runs well, but I don't know how to change password, the default is so long. thx.

**Comment by NGTmeaty** [comment]
With the default Docker, I don't believe we have a manual way. But you could use the Dockerfile to manually add a -password argument with a custom password.

**Comment by realzhaorong** [comment]
> With the default Docker, I don't believe we have a manual way. But you could use the Dockerfile to manually add a -password argument with a custom password.

I run docker by add -e password=mypwd arg, it doesn't work.

**Comment by NGTmeaty** [comment]
As I've said above, you currently cannot add in arguments. You'll have to create a Dockerfile and Docker compose to add in a custom password, or run the binary.

**Comment by macdja38** [comment]
You can override the default entry point and add the --password=supersecret flag to it. 

An example basic docker-compose file (without custom DorkerFile is.

```
  code-server:
    image: codercom/code-server:1.621
    command: --password=supersecret
```
(note that this docker-compose won't work out of the box, you'll need the volume / expose / whatever else.)

**Comment by lucacasonato** [comment]
AFAIK question has been answered. Issue should be closed.
