### ISSUE TITLE
[Chrome] Selection is resulting in copy/clipboard.

### ISSUE THREAD

**Issue by avodo** [codercom/code-server#292]
- `code-server` version: 1.30 to 1.32.0-282
- OS Version: Ubuntu/Windows => Chrome

## Description

In Chrome: Selecting anything in the editor will copy the text to clipboard.
In Firefox: Selecting anything in the editor will **not** copy the text to clipboard. (like expected)

Tested on Ubuntu 18.04 with chromium-browser and also tunneled to Windows with Chrome.

## Steps to Reproduce

1. Select some text in the editor.
2. The selected word will be in your clipboard (Ctrl+V).
Expected (in default): your clipboard should not be overwritten by selection.

I'm not sure if it is a bug in the actual meaning or even in the code-server.
However, it is annoying and maybe someone knows a solution.
Thanks!

####
I would like give thanks for the development of code-server. I'm looking quite some time for a solution like that. And finally there is one that is actual usable! :)

**Comment by kylecarbs** [comment]
Will fix. Thanks for the report!

**Comment by Fluidbyte** [comment]
Adding the following to my settings.json fixed for me:

```json
    "editor.emptySelectionClipboard": false,
    "editor.selectionClipboard": false
```

**Comment by Muruloki** [comment]
Have the same issue, adding the lines above doesn't help in my case.

**Comment by kylecarbs** [comment]
Fixed with the [latest release](https://github.com/codercom/code-server/releases/tag/1.408-vsc1.32.0).
