### ISSUE TITLE
waiting for v8 protocol on stdin/stdout

### ISSUE THREAD

**Issue by exepirit** [codercom/code-server#293]
- `code-server` version: docker container codercom/code-server
- Extension: vector-of-bool.cmake-tools + ms-vscode.cpptools in vscode

## Description

When I try to debug an application written in C using GDB I get `waiting for the v8 protocol on stdin / stdout` in output. My launch.json:

```
{
    "name": "(gdb) Launch",
    "type": "cppdbg",
    "request": "launch",
    "program": "{workspaceFolder}/build/exec",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${workspaceFolder}",
    "environment": [],
    "externalConsole": false,
    "MIMode": "gdb",
    "setupCommands": [
        {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
        }
    ]
}
```

## Steps to Reproduce

1. Run `code-server` in Docker
2. Install `gcc`, `gdb`, write simple "Hello World" app
3. Run debug with default `launch.json`

**Comment by kylecarbs** [comment]
Might be fixed with the build that was just released. [1.32.0-310](https://github.com/codercom/code-server/releases/tag/1.32.0-310)

**Comment by exepirit** [comment]
Version `code-server v1.32.0-310` still same error

**Comment by kylecarbs** [comment]
Found the issue. Fixing now!
