### ISSUE TITLE
Binary seems to open at root directory of user directory (macOS)

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#295]
- `code-server` version: code-server-1.32.0-310-darwin-x64
- OS Version: 10.14.3 (18D109)

## Description

The binary seems to open at the root of the user folder with no working directory specified. It seems as though the default behavior should be for the binary to open in the directory that it resides in.

Watching all of these files also seems to dramatically reduce responsiveness.

**Additional Info**
Nothing stored in local storage besides an entry for `colorThemeData`
![Screen Shot 2019-03-19 at 2 03 36 PM](https://user-images.githubusercontent.com/5651438/54634258-d3ee6a80-4a4f-11e9-8477-de138efd644d.png)

## Steps to Reproduce

1. Download binary
2. Right click on binary - open
3. Observe file tree

**Comment by nol166** [comment]
Has anyone noticed this behavior on any other platforms?

**Comment by code-asher** [comment]
The default at the moment is to use the current working directory, so it should default to wherever you are when you run the command.

**Comment by MalikBrown** [comment]
Don't forget to specify location on the binary/run script
`code-server <initial directory to open>`
