### ISSUE TITLE
The IDE is not opening

### ISSUE THREAD

**Issue by akashgurava** [codercom/code-server#3]
I go to the login page, sign in with my github. Then i get redirected to ide.coder.com but then the page is unresponsive.

**Comment by nol166** [comment]
Hey @akashgurava, are you seeing a white page with `{ }`?

**Comment by serapth** [comment]
I am having the same problem at ide.coder.com.  It's getting path the auth process.  In the developer console, you get about 6 503 bad gateway errors, then finally just a black screen.

**Comment by nol166** [comment]
Hey @akashgurava we are currently working on this and have an internal ticket. Closing this one out in favor of that one.

**Comment by nol166** [comment]
https://github.com/codercom/bugs/issues/343
