### ISSUE TITLE
--no-auth flag also disables SSL

### ISSUE THREAD

**Issue by mdp** [codercom/code-server#300]
Not sure if this was intentional, but when you disable auth with the `--no-auth` flag on the CLI, [SSL is also disabled](https://github.com/codercom/code-server/blob/21690453775629a97627d37ee8703ab5718ebe35/packages/server/src/server.ts#L135).

It's a bit confusing. In order to get SSL working, you need to use a password. When you don't have a password, you have to use the site/app via plain ol' HTTP.

Maybe there's some logic that I'm missing, but this had me stumped until I dug into the code.

**Comment by kylecarbs** [comment]
Definitely a bug. Will fix.
