### ISSUE TITLE
fix terminal and preview running url

### ISSUE THREAD

**Issue by syntaxhacker** [codercom/code-server#302]
I dont know why after making this open source code-server lost functionality in previewing url where the app is running in the container and bash terminal lost its color . when they will be available again??
![image](https://user-images.githubusercontent.com/30970495/54664655-e083c900-4b0a-11e9-8b7c-6dae92ebfa25.png)

**Comment by kylecarbs** [comment]
This is a coder.com issue. 

https://github.com/codercom/bugs/issues/359
https://github.com/codercom/bugs/issues/361

These issues will have accurate tracking data :)
