### ISSUE TITLE
Executing docker startup error 

### ISSUE THREAD

**Issue by Super-Ps** [codercom/code-server#306]
- `code-server` version: 
- OS Version: 

## Description

ubuntu 18.4
## Steps to Reproduce

1. 
docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth

1. 
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/root/.local/share/code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/root/.local/share/code-server/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27625), <anonymous>:56921:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}

**Comment by coadler** [comment]
We're tracking that bug here: https://github.com/codercom/code-server/issues/121
