### ISSUE TITLE
Add file and directory upload feature

### ISSUE THREAD

**Issue by xuanyuanaosheng** [codercom/code-server#31]

**Comment by nhooyr** [comment]
You can use `scp` to do this easily. We can definitely add a UI for scp though.

**Comment by xuanyuanaosheng** [comment]
> You can use `scp` to do this easily. We can definitely add a UI for scp though.

Well。 Use scp  command  is not a good way for windows.   The UI scp is a good way.  The  other way is to  use plugin solve  this. Please think about this:

https://github.com/liximomo/vscode-sftp

https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs

https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-remote-workspace

**Comment by PhilsLab** [comment]
Nextcloud has a nice way of handling this. You can just drag&drop the folder in place, and it uploads accordingly. A seperate "upload file here" button would also be nice.

Not sure if this is the right issue to address this, but i'd also like to see a download button for individual files, as well as folders/the project as zip.

**Comment by kylecarbs** [comment]
I believe we have this 🤔 

cc: @coderasher

**Comment by coderasher** [comment]
We do support drag and drop for uploading both files and directories.

You can drag into the main area of the editor (which will upload to the workspace root) or into the file tree (which will upload into whatever directory you dropped it on).

I think adding a button (and command) for uploading would be a good move, especially to make it more accessible from the keyboard.

We don't support downloading directories and files through the UI yet, but we want to eventually.

**Comment by jgbradley1** [comment]
Hello I just found out about this project. The Theia project recently implemented this [exact same issue](https://github.com/theia-ide/theia/issues/4088) in case you want to check out their implementation.

**Comment by kylecarbs** [comment]
Closing in favor of https://github.com/codercom/code-server/issues/233

**Comment by achirkin** [comment]
I am sorry to resurrect this discussion, but it looks like the upload feature is not cross-platform.
I am hosting code-server on linux;

  * Drag-n-drop on a linux machine works like a charm
  * On chrome OS it says "Cannot read property 'isFile' of null"
  * On windows it tries to copy a file into a path with backslashes instead of normal slashes. I get something like "Cannot copy '/\\home\username\bluh-bluh': access denied"

**Comment by sr229** [comment]
Please bring this up on #233. I'll be locking this thread.
