### ISSUE TITLE
Failure to build docker image (default extensions)

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#318]
- `code-server` docker image
- OS Version: MacOS

## Description

The user attempts to build code-server from the docker command and the process fails at the building of the built-in extension

## GIST
https://gist.github.com/jrussellsmyth/8e07e6b1d6bc117f8db073d92458c2b7

**Comment by nol166** [comment]
@nhooyr

**Comment by NGTmeaty** [comment]
[Hastebin from earlier](https://hastebin.com/mumesejopa.cs).

**Comment by code-asher** [comment]
We pre-build the default extensions now, and the build process downloads them so this won't be an issue going forward.
