### ISSUE TITLE
no need for the close/minimize/maximize buttons

### ISSUE THREAD

**Issue by shi-yan** [codercom/code-server#320]
- `code-server` version:  top of tree
- OS Version: ubuntu 18.04 for both host and docker

## Description

code-server still has the minimize, maximize and close window button on the top right corner. they are not functioning and should be removed.

**Comment by nol166** [comment]
@shi-yan Can you send a screenshot when you get a chance?

**Comment by shi-yan** [comment]
![Selection_004](https://user-images.githubusercontent.com/326807/54945484-2669d400-4ef3-11e9-8e4c-4c10b5795679.png)

this is only a problem on linux, I don't see the same buttons on mac. (not sure about windows)

**Comment by nol166** [comment]
@shi-yan Interesting. Thank you for sharing this

**Comment by shi-yan** [comment]
![Screenshot from 2019-03-25 11-44-11](https://user-images.githubusercontent.com/326807/54946016-6c736780-4ef4-11e9-8f76-c0bc65c21ea7.png)

you know, the other side of this bug is, on mac, you can't find the preference /setting menu. I don't have a mac at hand, so I can't show you the mac screenshot. but on linux, under the file menu, there is a preference /setting menu. this is not shown on mac. (so that I have no idea how to config preference.)

I guess the electron replacement layer shows different UIs on different client platforms. it tries to look native, that's why we see the close button on linux and no preference menu on mac.

**Comment by nol166** [comment]
If you use the command pallet does it let you get to the settings that way, either UI or JSON?
