### ISSUE TITLE
implement code -r (reuse window)

### ISSUE THREAD

**Issue by shi-yan** [codercom/code-server#325]
vscode has this command line 

code -r filename

This command will open the file with an existing vscode window. 

Having this command is convenient, because I can open any file from vscode's built-in terminal.

I wish code-server has something similar.

basically, within the code-server's built-in terminal, if I type code-server -r filename, the file will be opened by code-server in the same browser window.

**Comment by avelino** [comment]
Duplicate: https://github.com/codercom/code-server/issues/164
