### ISSUE TITLE
Installing packages with pip gives locale.Error: unsupported locale setting (Python2.7)

### ISSUE THREAD

**Issue by JimiPedros** [codercom/code-server#326]
- Code-Server version: 1.32

- OS Version: Windows 10

## Description
Installing a package with pip produces an error 'locale.Error: unsupported locale setting'

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

## Steps to Reproduce

1. Open ide.coder.com
2. Open the terminal
3. Install python and pip 
4. Install a package using pip

**Comment by nol166** [comment]
Try running `export LC_ALL=C`

**Comment by nol166** [comment]
Closing since it looks like the dockerfile was merged
