### ISSUE TITLE
Issue: Exposing code-server localhost URL to Internet, through secure tunneling using ngrok

### ISSUE THREAD

**Issue by bahreex** [codercom/code-server#330]
Hello,

How can I expose the local code-server URL to the Public Internet using ngrok secure tunnels?

I tried multiple ways, but unable to achieve the desired outcome.

Let's say I expose the local URL using ngrok as follows:

**`ngrok http 8443`**

I get the following error in the browser when I use the public URL generated by ngrok that maps to my internal URL for code-server:

![image](https://user-images.githubusercontent.com/5578341/54879232-7e093080-4e5c-11e9-9e46-4cc17640eb36.png)

When I Inspect the requests through ngrok public URl using the ngrok Inspector, I get the following info:

![image](https://user-images.githubusercontent.com/5578341/54879251-d17b7e80-4e5c-11e9-8b19-c9ba8ff5fbc1.png)

I searched extensively across the web to see if anyone else encountered such issues, but could not find anything anywhere.

Kindly help with your thoughts/suggestions.

**Comment by CodingPapi** [comment]
using --alow-http to start code-server

**Comment by bahreex** [comment]
Thanks!

**Comment by nol166** [comment]
Is it safe to close this one @bahreex ?

**Comment by bahreex** [comment]
> Is it safe to close this one @bahreex ?

Yes. Definitely :-)
