### ISSUE TITLE
Change name code-server to coder

### ISSUE THREAD

**Issue by avelino** [codercom/code-server#331]
## Description

I Understand that the code-server name is to **coder** with the name of the VSCode.
Thinking in common single name we could exchange code-server for  **coder**, this would help the marketing of the company.

Looking at the case of MongoDB at 10gen (old company name behind MongoDB before turning MongoDB Inc)

What do you think?

## Related Issues

- https://github.com/codercom/code-server/issues/325
- https://github.com/codercom/code-server/issues/164

**Comment by pokemonlover1234** [comment]
I think that would cause confusion between the oss project of code-server and the coder website.

**Comment by sr229** [comment]
@avelino I don't think this should be called `coder`. Coder is the company, `code-server` is the upstream project, and it should stay that way.

**Comment by Multishifties** [comment]
I don't believe our team has any plans to rename this repository at any time in the near future. We're also in the process of creating enterprise-level hosted solutions to stuff. We wouldn't want to cause any confusion between the two should we choose to use the name `coder` on any of our other software.
