### ISSUE TITLE
Error after first started shared process

### ISSUE THREAD

**Issue by Funeoz** [codercom/code-server#332]
- `code-server` version: 1.32.0-310
- OS Version: Kubuntu 18.10

## Description

After that the first shared process has just started, I get this error : 

`ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/home/theo/.local/share/code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/home/theo/.local/share/code-server/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/home/theo/Téléchargements/code-server-1.32.0-310-linux-x64/code-server:468:27684), <anonymous>:52540:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}`

However, I can access code-server in my browser.

## Steps to Reproduce

1. `./code-server`

**Comment by vedantroy** [comment]
This thread has the answer: https://github.com/codercom/code-server/issues/121 However, even if you fix this problem, you'll run into another issue which I don't know how to fix.

Specify ```-d /home/[user]/.code-server``` and manually create ```/home/[user]/.code-server/Backups/workspaces.json```.

**Comment by Funeoz** [comment]
So maybe I will wait a good workaround for this before running these commands.
