### ISSUE TITLE
Always gives me 'Password is incorrect!'

### ISSUE THREAD

**Issue by Ahmeed2m** [codercom/code-server#334]
- `code-server` version: v1.32.0-310
- OS Version: Ubuntu 18.10 (KDE)

## Description

Whenever I run  `code-server \home\ahmed\dev` as example I get the server is running in INFO but I get the error 

> events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE 0.0.0.0:8443
    at u.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

I have no idea if that's related to the issue or not but wherever I go the url and enter the generated password it says 'Password is incorrect!' even if I do `--no-auth` it says the same

## Steps to Reproduce

1. run `code-server any-path`
1. login in http://localhost:8443/

**Comment by nol166** [comment]
It looks like you are running a process on that port already, perhaps another instance of code server. Since the pass is generated for each time you run the code-server, it probably is incorrect
@Ahmeed2m

**Comment by Ahmeed2m** [comment]
> It looks like you are running a process on that port already, perhaps another instance of code server. Since the pass is generated for each time you run the code-server, the password is in fact probably incorrect. I would look for another process running on that port, kill it and start the code-server again
> @Ahmeed2m

that was it actually ! 
thank you, Is there a way it can close other instances when I start new one if no one is connected or something like that

**Comment by nol166** [comment]
@Ahmeed2m if you are running the same port every time you could run this before starting code-server

`kill $(lsof -t -i :8443)`

**Comment by luizfelmach** [comment]
I don't know why, but in my case, I was running code-server with sudo. Running without sudo solved it for me.

**Comment by DaShenZi721** [comment]
I agree with @luizfelmach . When I run code-server with sudo, I encountered the same issue (incorrect password). However, without sudo it worked.

**Comment by iceflamedragon** [comment]
I solved that.It is because that in the root's directory also has a config directory,and you have to check the settings in there
