### ISSUE TITLE
how to run from latest repo

### ISSUE THREAD

**Issue by polymerchm** [codercom/code-server#335]
Want to use without waiting for next binary.  Is there any instruction on how to build the binary on my local machine

**Comment by Multishifties** [comment]
@polymerchm

See https://github.com/codercom/code-server/issues/17

**Comment by nol166** [comment]
@polymerchm You could try:

1. `cd` into `code-server`
2. Run `yarn`
3. Run `yarn task vscode:clone`
4. Run `yarn task vscode:patch`
5. Run `yarn task buld:bootstrap-fork`
6. Finally, `yarn start`

If that doesn't work let me know. I might be missing a step.

**Comment by nol166** [comment]
I believe you will also need a version of node 8. I use `v8.15.0` which seems to work well.

**Comment by polymerchm** [comment]
Get this.   Not sure what to do next.

ERROR VSCODE:INSTALL failed {"exitCode":1,"stdout":"$ node build/npm/preinstall.js\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo vscode-fsevents@0.3.10: The platform \"linux\" is incompatible with this module.\ninfo \"vscode-fsevents@0.3.10\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo fsevents@1.2.7: The platform \"linux\" is incompatible with this module.\ninfo \"fsevents@1.2.7\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo fsevents@1.2.4: The platform \"linux\" is incompatible with this module.\ninfo \"fsevents@1.2.4\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo vscode-windows-registry@1.0.1: The platform \"linux\" is incompatible with this module.\ninfo \"vscode-windows-registry@1.0.1\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo windows-foreground-love@0.1.0: The platform \"linux\" is incompatible with this module.\ninfo \"windows-foreground-love@0.1.0\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo windows-mutex@0.2.1: The platform \"linux\" is incompatible with this module.\ninfo \"windows-mutex@0.2.1\" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo windows-process-tree@0.2.3: The platform \"linux\" is incompatible with this module.\ninfo \"windows-process-tree@0.2.3\" is an optional dependency and failed compatibility check. Excluding it from installation.\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n","stderr":"warning \" > gulp-tsb@2.0.6\" has incorrect peer dependency \"typescript@^2.0.10\".\nerror /usr/local/code-server/lib/vscode/node_modules/native-keymap: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /usr/local/code-server/lib/vscode/node_modules/native-keymap\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.8.0\ngyp info using node@10.10.0 | linux | x64\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/local/code-server/lib/vscode/node_modules/native-keymap/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/spollack/.node-gyp/iojs-3.1.3/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/spollack/.node-gyp/iojs-3.1.3',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/home/spollack/.node-gyp/iojs-3.1.3/<(target_arch)/iojs.lib',\ngyp info spawn args   '-Dmodule_root_dir=/usr/local/code-server/lib/vscode/node_modules/native-keymap',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'x11' found\nPackage xkbfile was not found in the pkg-config search path.\nPerhaps you should add the directory containing `xkbfile.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'xkbfile' found\ngyp: Call to 'pkg-config x11 xkbfile --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)\ngyp ERR! stack     at ChildProcess.emit (events.js:182:13)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)\ngyp ERR! System Linux 4.15.0-46-generic\ngyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /usr/local/code-server/lib/vscode/node_modules/native-keymap\ngyp ERR! node -v v10.10.0\ngyp ERR! node-gyp -v v3.8.0\ngyp ERR! not ok\n"}

ERROR VSCODE:INSTALL Failed: Failed to install vscode dependencies: warning " > gulp-tsb@2.0.6" has incorrect peer dependency "typescript@^2.0.10".
error /usr/local/code-server/lib/vscode/node_modules/native-keymap: Command failed.
Exit code: 1

**Comment by nol166** [comment]
It looks like you are using Mac, try swapping out linux for darwin

`yarn task build:server:binary:darwin`

**Comment by polymerchm** [comment]
No.  Building  in on a linux box. Ubuntu

**Comment by polymerchm** [comment]
How often do binaries come out?

**Comment by Multishifties** [comment]
@polymerchm we release new versions whenever we have meaningful updates ready and tested. We don't have a set release schedule at the moment. Thus far we've been submitting new releases a few times per week.

**Comment by polymerchm** [comment]
Just struggling with installing on a linux box from the "repos".   Yarn, npm and I are not good friends.

**Comment by NavinNavi19** [comment]
@nol166 Even I got the same error using Ubuntu 18.04.

**Comment by nol166** [comment]
What version of node are you guys using when running the yarn build tasks

**Comment by code-asher** [comment]
`Package xkbfile was not found in the pkg-config search path` might be the key. Do you have `libxkbfile-dev` installed? Running `pkg-config x11 xkbfile --libs` should give you something like `-lX11 -lxkbfile`.

**Comment by code-asher** [comment]
Closing in favor of #417.
