### ISSUE TITLE
installing angular 

### ISSUE THREAD

**Issue by Malaka22p** [codercom/code-server#337]
## Description

 I am new to coder and just started learning angluar, i look into some tutorials and  coder does not need node or npm install in local machine. but when i run coder and run commands for npm-v ng-v and node-v commands not working. is there any documentation on tutorials to follow on setting up angular on coder

here's a terminal screenshot

![commands](https://user-images.githubusercontent.com/23239235/54966325-048e5100-4fc8-11e9-9588-4ef193340258.PNG)

**Comment by sr229** [comment]
This does not realte to Coder at all, if it was ide.coder.com, we'll have a different story. You simply forgot to install Angular CLI tools.

**Comment by Malaka22p** [comment]
I am not sure, i understand what you are saying, this is about setting up an angular app in ide.coder.com
since ide.coder is a vs code in cloud. any ideas on what am i missing to run those commands

**Comment by sr229** [comment]
You just need to install the required tools I citated above, I am not sure why you are having difficulty understanding that those tools are not yet installed, its clearly stated that `bash` can't find it on `$PATH`.

**Comment by NGTmeaty** [comment]
This is the wrong repo. Coder's hosted IDE bugs should go here: https://github.com/codercom/bugs But it doesn't seem to be a  bug. You'll have to install your tools from the instructions on their websites.

Please close.

**Comment by Dj-jom2x** [comment]
you have to install npm + node .. then angular cli before you do that xD this is not a bug

**Comment by sr229** [comment]
Voting this a closure as this does **NOT** concern this project at all.
