### ISSUE TITLE
VBox with VM Ubuntu 18.10 -  TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by danibudi** [codercom/code-server#34]
- `code-server` version: code-server-1.31.0-20-x86_64-linux
- OS Version: Ubuntu 18.10

#### Steps to Reproduce
`$ /home/dani/code-server-1.31.0-20-x86_64-linux/code-server .
INFO  code-server v1.0.0
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/dani/.code-server","working-dir":".","log-dir":"/home/dani/.code-server/logs/20190306105306352"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO   
INFO  Password: 1QLwbiaSylKW
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO   
INFO  Starting shared process [1/5]...
/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:340
 */var r=/["'&<>]/;e.exports=function(e){var t,n=""+e,i=r.exec(n);if(!i)return n;var o="",a=0,s=0;for(a=i.index;a<n.length;a++){switch(n.charCodeAt(a)){case 34:t="&quot;";break;case 38:t="&amp;";break;case 39:t="&#39;";break;case 60:t="&lt;";break;case 62:t="&gt;";break;default:continue}s!==a&&(o+=n.substring(s,a)),s=a+1,o+=t}return s!==a?o+n.substring(s,a):o}},function(e,t,n){"use strict";e.exports=function(e,t){if(null==t)return function e(t,n){for(var r=0;r<t.length;r++){var i=t[r];Array.isArray(i)?e(i,n):n.push(i)}return n}(e,[]);return function e(t,n,r){for(var i=0;i<t.length;i++){var o=t[i];r>0&&Array.isArray(o)?e(o,n,r-1):n.push(o)}return n}(e,[],t)}},function(e,t){e.exports=function(e,t){if(e&&t)for(var n in t)e[n]=t[n];return e}},function(e,t,n){"use strict";const r=n(677),i=n(191),o=n(199),a=n(92),s=Buffer.from([0,0,255,255]),c=Buffer.from([0]),u=Symbol("permessage-deflate"),l=Symbol("write-in-progress"),p=Symbol("pending-close"),d=Symb

TypeError: Cannot read property 'on' of undefined
    at t.emitLines (/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:340:7474)
    at t.async (/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:716:35103)
    at e.exports (/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:716:34522)
    at e (/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/home/dani/code-server-1.31.0-20-x86_64-linux/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
dani@dani-VirtualBox:~/monitoring_pdxc_api_integration$ 
`

**Comment by bketelsen** [comment]
Same error on 18.10 metal installation.
Worked fine on Chromebook Pixel with Crostini 18.04 installation.

**Comment by Sansumaki** [comment]
Same error on Ubuntu 18.04.1 in VMWare

**Comment by shaform** [comment]
same error on 18.04.1 installed in a laptop.

**Comment by coder3101** [comment]
The Readme says you must spin up a 16.04 LTS. It doesn't works on 18.04 LTS

**Comment by shaform** [comment]
@coder3101 Thanks for pointing out this! But it seems that it's in this document rather than in readme: https://github.com/codercom/code-server/blob/33717b277aa15ff1b24d582316e17ed775efcdf8/doc/admin/install/aws.md

So it's a bit hard to realize this fact.

**Comment by kylecarbs** [comment]
Installing the `net-utils` package will solve this issue. Refer to: https://github.com/codercom/code-server/issues/44#issuecomment-470340649

A fix will be in soon!
