### ISSUE TITLE
Syntax Highlighting not working with Nativefier

### ISSUE THREAD

**Issue by kasplat** [codercom/code-server#340]
- `code-server` version: v1.32.0-282
- OS Version: Mac, server hosted on Ubuntu 18.04.1 LTS

## Description

Synatx highlighting for all files does not work with [Nativefier](https://github.com/jiahaog/nativefier) (which hosts a browser in an electron app). I've had occasional issues using it in the web browser where the syntax highlighting stops working, so this could be related. 

Screenshot of console in a working browser window
![image](https://user-images.githubusercontent.com/4544454/55023626-73fd4400-4fba-11e9-959d-29c9c00400f5.png)

Screenshot of console in the nativefier app
![image](https://user-images.githubusercontent.com/4544454/55023796-d0f8fa00-4fba-11e9-91cc-457f18506706.png)

## Steps to Reproduce

1. Install Nativefier `npm install nativefier -g`
2. Open vs code server with nativefier `nativefier --ignore-certificate https://xx.xx.xx.xx:port` The files do not have syntax highlighting

This was tested with all relevant looking flags (--insecure, --enable-es3-apis, --ignore-certificate, --flash), but none of them got syntax highlighting to work.

**Comment by kasplat** [comment]
After a few minutes, this error showed up in the console. Looks like a file existence error.
![image](https://user-images.githubusercontent.com/4544454/55024018-3fd65300-4fbb-11e9-89ae-c953ee7a2069.png)

**Comment by kasplat** [comment]
Running it as sudo to avoid the previous issue has this issue instead: 
![image](https://user-images.githubusercontent.com/4544454/55024816-dd7e5200-4fbc-11e9-8507-a04958e26400.png)

**Comment by nol166** [comment]
I followed the steps above and syntax highlighting seems to work, unless i am not understanding correctly:

<img width="1392" alt="Screen Shot 2019-03-26 at 1 47 00 PM" src="https://user-images.githubusercontent.com/5651438/55025132-491ceb00-4fce-11e9-8041-50f9bbae6143.png">

**Comment by kasplat** [comment]
Interesting, not sure why it doesn't work on my machine then. Any suggestions for things to report?

![image](https://user-images.githubusercontent.com/4544454/55029748-1a037b00-4fc8-11e9-91b9-26d793705ea6.png)

I did make sure to wait a few minutes to see if it loaded to no avail.

**Comment by nol166** [comment]
@kasplat I built the electron app from a more recent binary that I built from the source. It may be a bug that has since been fixed. We are releasing an "official" new binary later today so that will likely resolve the problem.

**Comment by RyanK1m** [comment]
I tried nativefier with newly released binary, but sadly, syntax highlight doesn't seem to work. 
Maybe I should build electron app without nativefier? 
It's disappointing because nativefier protect me from close code-server tab on chrome by accidentally press ctrl+w to close editor tab. (And more native feel too)

**Comment by RyanK1m** [comment]
--no-auth solve the problem. nativefier app doesn't send cookie with password. 
So... I should somehow solve that puzzle now.

**Comment by Cosby5** [comment]
I was having the same problem. What I did was move the auth to Nginx using basic auth, then added a special case to turn it off. Nativefier can then be set with the password to auto-login. Now the only thing that escapes auth is the .wasm extension.

```
auth_basic_user_file /path/to/.htpasswd;
auth_basic           "Administrator’s Area"

location ~ \.wasm {
  auth_basic off;
  ...
}
location / {
  ...
}
```

**Comment by kasplat** [comment]
@nol166 any chance this can be solved without using nginx in a reasonable amount of time? It probably wouldn't be too bad to set up nginx, but it would be nice if code server supported this out of the box.

**Comment by coadler** [comment]
Isn't this technically a nativefier bug? Or is it the way `code-server` handles cookies

**Comment by kasplat** [comment]
Judging from the comments above, it does seem to be an issue for nativefier, so I'll raise the issue over there. If there's a reasonable way to fix this here though feel free to reopen it. The thread is here https://github.com/jiahaog/nativefier/issues/789.
