### ISSUE TITLE
Error thrown when attempting to paste from clipboard

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#343]
- `code-server` version: manually built binary
- OS Version: MacOS 10.14.3 (18D109)

## Description

After switching focus to the browser and quickly pressing `command v`, this error appears in a notification. Subsequent attempts to paste don't have this problem.

![Screen Shot 2019-03-26 at 3 04 24 PM](https://user-images.githubusercontent.com/5651438/55029764-e715b300-4fd8-11e9-8722-f271f8af6d28.png)

## Steps to Reproduce
1. Run code server, open browser
2. In another (non-browser) window copy some text
3. Quickly `command tab` back to the browser and `command v`

**Comment by Multishifties** [comment]
Am unable to replicate. Testing this on both local machine and our dev network. 🙁

**Comment by foresthoffman** [comment]
What was the context of the selection when you switched back to the IDE? e.g. the window, the file explorer, editor window, etc?

**Comment by Multishifties** [comment]
@foresthoffman I believe just the default selection on initial page load (so, none)

**Comment by nol166** [comment]
@foresthoffman it was the code editor

**Comment by code-asher** [comment]
`readBuffer` was implemented in https://github.com/codercom/code-server/pull/568.
