### ISSUE TITLE
Failed to handle client message

### ISSUE THREAD

**Issue by vimota** [codercom/code-server#350]
- `code-server` version: latest git repo
- OS Version: Linux VM

## Description

I've tried building the latest code into it's own image (`docker build --rm --pull -t "codercom/code-server:beta" -f "Dockerfile" .`) so that I can test the latest changes (and also wanted to build a C# specific version of code-server, with dotnet etc). But when I try running the image I get the following error and am unable to use it:

ERROR Failed to handle client message {"length":2,"exception":{"message":"unknown message type","stack":"Error: unknown message type\n    at t.Server.handleMessage (/src/packages/server/out/cli.js:340:104610)\n    at e.onMessage (/src/packages/server/out/cli.js:340:102979)\n    at b.t.addEventListener.t (/src/packages/server/out/cli.js:340:101131)\n    at b.n (/src/packages/server/out/cli.js:504:28094)\n    at emitOne (events.js:116:13)\n    at b.emit (events.js:211:7)\n    at e.exports.T (/src/packages/server/out/cli.js:259:11285)\n    at emitOne (events.js:116:13)\n    at e.exports.emit (events.js:211:7)\n    at e.exports.dataMessage (/src/packages/server/out/cli.js:259:19691)\n    at e.exports.getData (/src/packages/server/out/cli.js:259:18932)\n    at e.exports.startLoop (/src/packages/server/out/cli.js:259:16321)\n    at e.exports._write (/src/packages/server/out/cli.js:259:15703)\n    at doWrite (_stream_writable.js:396:12)\n    at writeOrBuffer (_stream_writable.js:382:5)\n    at e.exports.Writable.write (_stream_writable.js:290:11)\n    at Socket.P (/src/packages/server/out/cli.js:259:11815)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)"}}

**Comment by kylecarbs** [comment]
You'll likely have to clear your client cache.

**Comment by nol166** [comment]
```docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom:code-server@sha256:a5a8d639e412d91e7caa1df6652dc1696c3cb838cf7afcd064968bd757b8eebc code-server --allow-http --no-auth``` - Try running this

**Comment by vimota** [comment]
Clearing my client cache doesn't resolve it unfortunately.

Running that command fails too :(
```vimota@vimota-vm ~/git % docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom:code-server@sha256:a5a8d639e412d91e7caa1df6652dc1696c3cb838cf7afcd064968bd757b8eebc code-server --allow-http --no-auth
Unable to find image 'codercom:code-server@sha256:a5a8d639e412d91e7caa1df6652dc1696c3cb838cf7afcd064968bd757b8eebc' locally
docker: Error response from daemon: pull access denied for codercom, repository does not exist or may require 'docker login'.
See 'docker run --help'.```

**Comment by vimota** [comment]
Oh it does look like clearing the cache (or some other magic) made it work although I had tried that several times. I think I needed to close all existing sessions AND delete the cache.

**Comment by nol166** [comment]
@vimota that is my fault I had a typo 
```docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server:1.408-vsc1.32.0 code-server --allow-http --no-auth```

**Comment by vimota** [comment]
Thanks for the help!
