### ISSUE TITLE
Command Pallete Shortcut is not being intercepted on Firefox

### ISSUE THREAD

**Issue by sr229** [codercom/code-server#354]
- `code-server` version: 1.32.0-310
- OS Version: CoreOS build 2025

## Description

On Firefox Quantum, Coder does not intercept the command pallete shortcut which is the private browsing shortcut as well on Firefox. Even Alt + KEY refuses to work.

## Steps to Reproduce

1. Open Firefox
2. Hit the command pallete shortcut

**Comment by nol166** [comment]
@sr229 Does F5 work? (should still be fixed for the other one)

**Comment by kylecarbs** [comment]
I don't believe we can override this.

**Comment by sr229** [comment]
I think folks at Theia found a way around this, worth a look.

**Comment by code-asher** [comment]
To be sure I made a small test on an empty webpage binding `keydown` and preventing default and stopping propagation on the event but had no luck.

I searched around Theia's GitHub and didn't find anything except this open issue: https://github.com/theia-ide/theia/issues/1696. As mentioned there, `F1` is a viable workaround, but it doesn't appear possible to override `ctrl+shift+p`.
