### ISSUE TITLE
Implicit JSON Schema Support

### ISSUE THREAD

**Issue by grant** [codercom/code-server#358]
# Expected

Editors like VS Code support JSON schemas out of the box.

This is done via http://schemastore.org/json/

I expect to not have to provide a `$schema` to get autocompletion. Just look up the filename.

Pull from the catalog:
API: http://schemastore.org/api/json/catalog.json
SRC: https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json

[(See VSC bug)](https://github.com/Microsoft/vscode/issues/26289)

# Actual

When you create a `.json` file (i.e. `appsscript.json`), you must explicity specify the schema

![Screen Shot 2019-03-27 at 12 55 53](https://user-images.githubusercontent.com/744973/55107940-b6448500-508f-11e9-9acc-38f823683694.png)

(Notice only one autocompletion result)

i.e.

```json
{
  "$schema": "http://json.schemastore.org/appsscript"
}
```

Then you'll get autocompletion.

![Screen Shot 2019-03-27 at 12 56 45](https://user-images.githubusercontent.com/744973/55107992-d5dbad80-508f-11e9-8349-290df466b102.png)

```json
{
  "$schema": "http://json.schemastore.org/appsscript",
  "timeZone": "America/New_York",
  "dependencies": {
  },
  "exceptionLogging": "STACKDRIVER"
}
```

**Comment by NGTmeaty** [comment]
probably should fix this upstream?

**Comment by grant** [comment]
This should be upstream. I wasn't easily able to find the `Settings` to solve this.

In VSCode, it's this:

```
Code > Preferences > Settings
```

But that will be a different issue.

**Comment by grant** [comment]
I've filed this issue for adding a way to access **Preferences > Settings** via the menu bar: https://github.com/codercom/code-server/issues/359
