### ISSUE TITLE
Missing Application Tab

### ISSUE THREAD

**Issue by grant** [codercom/code-server#359]
Coder is missing an application tab.
I expect a menu tab called **"Coder"** or that the Coder icon be clickable.

# Menu Items

- **About**: Not really needed, OSX app specific
- **Updates**: Not needed.
- **Preferences**: **Needed for Settings.** I can only access this via the hotkey "cmd + ,"
- Others: Not applicable to web application.

# Pictures

## Coder Menu
![Screen Shot 2019-03-27 at 13 35 58](https://user-images.githubusercontent.com/744973/55110452-489b5780-5095-11e9-986a-c2e2c6a08f2d.png)

## VS Code Menu (OSX)
![Screen Shot 2019-03-27 at 13 30 39](https://user-images.githubusercontent.com/744973/55110416-38837800-5095-11e9-9a30-0f8fe6711389.png)

**Comment by nol166** [comment]
You can still access preferences from the command pallet, but I agree it would be nice to have it in the file menu or something

**Comment by code-asher** [comment]
`Preferences` was moved to the `File` menu as part of https://github.com/codercom/code-server/pull/445.
