### ISSUE TITLE
Remove discord from README.md

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#360]
Looks really unprofessional because its low res.

**Comment by NGTmeaty** [comment]
While I agree it's low-res, I think it looks fine and provides users a way to get to our community. 

Honestly in my opinion it looks fine. https://owo.whats-th.is/AADxnLw.png  
Even zoomed into 250% it looks _ok_. https://owo.whats-th.is/4hRewjW.png

**Comment by nhooyr** [comment]
It's only fine for low res monitors. I'm using a 4k 21" monitor. It pretty much looks like a joke to anyone using macOS or on mobile.

**Comment by NGTmeaty** [comment]
~~Just tried it out on two different phones and honestly, it looks fine. I think it provides a bigger utility~~

Turns out Shields does have a discord badge. I'll submit a PR here.

**Comment by NGTmeaty** [comment]
#364 merged. Recommending close.
