### ISSUE TITLE
Terminal Startup Script

### ISSUE THREAD

**Issue by grant** [codercom/code-server#366]
## Description

How do you provide a terminal startup script (i.e. a script that runs for every new coder brower tab)?

I've tried setting `~/.profile`, `/etc/init.d/` scripts, using `update-rc.d`.

Could this be documented?

**Comment by Multishifties** [comment]
@grant I think this may be a duplicate of https://github.com/codercom/features/issues/52

If I understand correctly, this issue also appears to be in regards to the Coder-Hosted services and not the binary itself. Is that correct?

**Comment by grant** [comment]
I don't know about the services/binary question.
In terms of a duplicate, we could probably consolidate to the other repo issue.

**Comment by jeremymoore** [comment]
It looks like the related issue is a dead link now... do we have a new URL that discusses this topic?
