### ISSUE TITLE
Code-service requires a docker list

### ISSUE THREAD

**Issue by JavanTang** [codercom/code-server#367]
Using code-service in docker, we tend to need a variety of environments, like I need GPU, then I need the cuda version of the code-service, of course, there are many other situations, here is not to add a The version of code-service.

At the same time, I have a small problem. Whenever the code-service is updated, how can I update it in docker? I am now building the dockerfile from scratch.

**Comment by JavanTang** [comment]
Attached to the project I have done with cuda, https://github.com/JavanTang/code-server

Docker pull registry.cn-hangzhou.aliyuncs.com/test_tzf/test:0.1.7

**Comment by sr229** [comment]
@JavanTang, @nhooyr explicitly said that they don't need to support every use case - means that you should provide your own stack for your own needs.

**Comment by nhooyr** [comment]
This issue is too unclear to resolve. I'm not sure what you're asking. If you're still having a problem, please open a new issue with a more clear description.
