### ISSUE TITLE
Copy and paste file from sidebar doesn't work with menu or ctrl c

### ISSUE THREAD

**Issue by andreimc** [codercom/code-server#369]
- `code-server` version:  1.408-vsc1.32.0
- OS Version:  Ubuntu

## Description

Can't copy and paste file in sidebar

i.clipboard.writeBuffer is not a function

## Steps to Reproduce

Open sidebar cmd + c on a selected file

**Comment by nol166** [comment]
related #343

**Comment by code-asher** [comment]
Fixed by https://github.com/codercom/code-server/pull/568.
