### ISSUE TITLE
Python not working at all

### ISSUE THREAD

**Issue by anonamause10** [codercom/code-server#370]
- `code-server` version:  version: 1.408-vsc1.32.0
- OS Version:  MacOS Mojave 10.14.1
- Extension:  ms-python.python

## Description

In the bottom left of the coder IDE, there is a loading icon saying python extension loading. It won't stop at all. I cannot run any python scripts, and I think it has to do with the fact that this python extension won't load.

## Steps to Reproduce

1.  Open coder.com ide
1.  icon shows up
1.  using terminal, try `python3 hello.py` which just has `print('hello')` , nothing happens.

**Comment by lsmoura** [comment]
You need to install it inside the code-server docker machine:

```
root@51060d61ec7c:~/project/code-server# python3 --version
bash: python3: command not found
root@51060d61ec7c:~/project/code-server# apt-get install -y python3
[...redacted...]
root@51060d61ec7c:~/project/code-server# python3 --version
Python 3.6.7
root@51060d61ec7c:~/project/code-server#
```

**Comment by anonamause10** [comment]
`python3 --version` doesn't return anything.

I did `apt-get install -y python3`, and out came this
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.5.1-3).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.`

I tried `python3 --version` again anyway, still did nothing.

**Comment by kylecarbs** [comment]
Are you running within docker? There's an open issue for some exts on Mac that's in the works right now.

**Comment by anonamause10** [comment]
I have no idea if I'm running within docker. The only thing I did with coder was start up the ide, make a folder, and the hello.py script. I got the alpha last summer, and it worked fine then. I don't know why it doesn't anymore.

**Comment by NGTmeaty** [comment]
He's using Coder.com. We may want to move this into the other repo.

**Comment by nol166** [comment]
moved https://github.com/codercom/bugs/issues/363

**Comment by sidazhang** [comment]
Can you reopen this issue? There are a lot more issues other than installing python. There is a problem with pylint as well.

But basically, python is not working at all

**Comment by MegaMewtwoY** [comment]
Can you reopen this issue? I meet this problem too. The python extension not work at all. And make the highlight not working~~

**Comment by vinayakpahalwan7** [comment]
> Can you reopen this issue? There are a lot more issues other than installing python. There is a problem with pylint as well.
> 
> But basically, python is not working at all

**I'm facing the same issue.**

**Comment by jumblies** [comment]
I am struggling with this too.  Each time the container is taken down I need to go back in and 
```
sudo apt update && sudo apt install -y python3 python3-venv
```
to get python back.  This works but the python extension doesn't work at all.

**Comment by deansheather** [comment]
If you're experiencing an issue with the python extension I'd recommend opening a new issue, as this one was specifically related to our discontinued cloud offering on ide.coder.com.
