### ISSUE TITLE
Relase assets with different name pattern

### ISSUE THREAD

**Issue by avelino** [codercom/code-server#373]
## Description

Created the files (assets) with different name, we need to keep pattern `-`

My environment is automatically updated by script, today the update has stopped

<img width="1000" alt="Captura de Tela 2019-03-28 às 8 30 35 PM" src="https://user-images.githubusercontent.com/31996/55199462-d7dd6380-5198-11e9-90d4-77065860a622.png">

check @kylecarbs

**Comment by nol166** [comment]
We did update the naming convention but it shouldn't budge moving forward

**Comment by avelino** [comment]
fixed my problem:

```shell
curl -s https://api.github.com/repos/codercom/code-server/releases/latest | grep "linux-x64.tar.gz" | cut -d '"' -f 4 | wget -O /tmp/coder.tar.gz -qi - && \
tar -xvf /tmp/coder.tar.gz --wildcards "*/code-server" --strip-components=1 && \
mv ./code-server /usr/local/bin/code-server
```

> https://github.com/avelino/dockerfiles/blob/0f27357fa9d4902befd34eb27499e399d922d500/coder/Dockerfile#L16:L18
