### ISSUE TITLE
[ide.coder.com] increase starting cpu & memory ram for users

### ISSUE THREAD

**Issue by SHoar** [codercom/code-server#38]
after I downloaded and unzipped the latest node.js 10.15 (see https://github.com/codercom/code-server/issues/37), I touched a hello.js file to write and execute a simple console.log('hello'); it ran after I had aliased the node bin cmd, but I saw that CPU usage went up to 92% and mem maxed out at 1.0/1.0.  Pretty sure that the VSCode GUI is hogging the majority of the resources there, so you may want to keep that in mind.

**Comment by nol166** [comment]
Since this issue pertains to coder.com and the container rather than the open source IDE, I am going to move this to codercom/bugs - https://github.com/codercom/bugs/issues/345
