### ISSUE TITLE
Error: exited with null when starting shared process on latest release version

### ISSUE THREAD

**Issue by adriandarian** [codercom/code-server#384]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: Ubuntu 18.04 x64 , DigitalOcean

## Description

I cannot run the command `code-server myApp`. It throws this error

![image](https://user-images.githubusercontent.com/23567187/55285201-d304e500-533b-11e9-9df2-71d4b7ee8b71.png)

*I followed two tutorials*
+ [https://github.com/codercom/code-server/blob/master/doc/admin/install/digitalocean.md](https://github.com/codercom/code-server/blob/master/doc/admin/install/digitalocean.md)
+ [https://www.youtube.com/watch?v=9Emn2YQNDl0](https://www.youtube.com/watch?v=9Emn2YQNDl0)

## Steps to Reproduce

1. `wget https://github.com/codercom/code-server/releases/download/1.408-vsc1.32.0/code-server1.408-vsc1.32.0-linux-x64.tar.gz`
2. `tar -xvzf code-server1.408-vsc1.32.0-linux-x64.tar.gz`
3. `cd code-server1.408-vsc1.32.0-linux-x64/`
4. `sudo chmod +x code-server`
5. `sudo mv code-server /bin/`
6. `cd ~/`
7. `code-server myApp`
8. Error Appears

**Comment by adriandarian** [comment]
UPDATE: attempted same steps but with an older version and got the same error

**Comment by NGTmeaty** [comment]
This error is a issue with the amount of RAM available on your system. Older versions will be worse, so I really only recommend the latest. Do you know how much RAM the droplet has?

**Comment by adriandarian** [comment]
1GB RAM

**Comment by NGTmeaty** [comment]
I think we recommend atleast 2GB.

**Comment by adriandarian** [comment]
cool it worked
