### ISSUE TITLE
Passwords stored in browser cookies?

### ISSUE THREAD

**Issue by ProgrammerHuang** [codercom/code-server#394]
Passwords stored in browser cookies?
It's not safe!

**Comment by cy91244** [comment]
The cookie will be deleted when the session ended, but surely it's not a good practice to store password in plain text at the client side.

**Comment by kylecarbs** [comment]
Seems to be safe. There are _better_ methods like exchanging the password for a temporary token. The risks seem to be similar to storing any secret in a cookie.

**Comment by nol166** [comment]
I think we are going with cookies for now, but we will revisit more secure methods if we find this method is a more risky than others
