### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by Mohammad-Quanit** [codercom/code-server#397]
- `code-server` version: 
- OS Version: 

## Steps to Reproduce

1. 
1. 

I created my account via phone number and Github authentication but when I try to log in it redirects me to signup page again. I am using this first time and already facing this kind of issues. Could anyone help me why it is happening?

**Comment by nol166** [comment]
Hey @Mohammad-Quanit This repo is for the self-hosted version of code-server rather than coder.com. Go ahead and shoot us an email at contact@coder.com and we can help you out.
