### ISSUE TITLE
Fix password feature

### ISSUE THREAD

**Issue by icebob** [codercom/code-server#4]
First of all, it's an awesome project. Thank you! By the way, do you plan to add fix password feature? Maybe it can be set as CLI argument like `./code-server --password 123456`.

Or can I create a PR with this feature?

Keep up the good work!

**Comment by tvarwig** [comment]
I agree

**Comment by nol166** [comment]
I like that Ide @icebob. I will bring it up to the front end peeps.

**Comment by ddon** [comment]
Wow, this code-server is amazing, thank you for such a great new tool! we will start using it in our agency... Password parameter for sure is important, otherwise user needs to login to ssh first, run the code-editor, copy the password, and only then be able to use it in the browser.

**Comment by kylecarbs** [comment]
@icebob feel free to create a PR for it! We'll also put it on the high-priority list :)

**Comment by icebob** [comment]
Great! I will send it when I'm done.

**Comment by Pitu** [comment]
I'm confused since according [to the docs](https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md) `--password` is a valid flag.

**Comment by ddon** [comment]
$ ./code-server --help
Start your own self-hosted browser-accessible VS Code

USAGE
  $ server [WORKDIR]

ARGUMENTS
  WORKDIR  [default: /home/ddon/code-server-1.31.0-x86_64-linux] Specify working dir

OPTIONS
  -d, --data-dir=data-dir
  -h, --host=host          [default: 0.0.0.0]
  -o, --open               Open in browser on startup
  -p, --port=port          [default: 8443] Port to bind on
  -v, --version            show CLI version
  --allow-http
  --cert=cert
  --cert-key=cert-key
  --help                   show CLI help
  --no-auth

**Comment by Pitu** [comment]
What I meant with my message is that if the flag is in the docs maybe it's a feature not pushed yet but already implemented. I don't know the roadmap, was just pointing that out.

**Comment by icebob** [comment]
Docs updated with #5 https://github.com/icebob/code-server/commit/e1099f0fb4240ac39f9fe788d86a2e1527724b17#diff-3e3c890e38761b2c49f651e11b921f9d
But it's not released yet.

**Comment by NGTmeaty** [comment]
While regular Math.Random is probably fine, we may want to look into using a CSPRNG.

**Comment by sr229** [comment]
why not just use `/dev/urandom`?

Nothing could possibly go wrong using the OS's Random device.

**Comment by NGTmeaty** [comment]
With possibly Windows support coming in the future, I doubt we'd want to use a OS dependent function.
