### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by cliffburdick** [codercom/code-server#400]
- `code-server` version: server/1.32.0-310 linux-x64 node-v8.15.0
- OS Version: Ubuntu 18.04

## Description

Hi, I added a new task for a build using the type "Other". I edit tasks.json, and that appears to go fine. However, when I go back to edit it by click "Tasks->Configure Task" and the name of my task, a dialog in the bottom right says:

Unable to open '.vscode\tasks.json': File not found (file:///home/cburdick/.vscode\tasks.json).

This is a Linux server, so I'm not sure why it's using a windows path delimiter on the last portion.
## Steps to Reproduce

1. Create a new task
2. Try to edit that task

**Comment by kylecarbs** [comment]
Interesting. Are you using a windows client? That could likely cause the `\` in the pathname. If thats the case, we'll definitely fix!

**Comment by cliffburdick** [comment]
Hi @kylecarbs, I'm using Chrome in windows. Is that what you mean?

**Comment by kylecarbs** [comment]
Yup! We'll fix this.

**Comment by code-asher** [comment]
Appears to have been resolved in the latest pre-release.
