### ISSUE TITLE
Switch to an LTS version of Ubuntu (18.04) for the Dockerfile 

### ISSUE THREAD

**Issue by TylerLeonhardt** [codercom/code-server#404]
Today, the Dockerfile points to Ubuntu 18.10. For best compatibility, and for the best support long term, it would be better to use an LTS version of Ubuntu like 18.04 for better support overall.

cc @jaykul

**Comment by kylecarbs** [comment]
cc: @nhooyr

**Comment by nhooyr** [comment]
We can offer both.
