### ISSUE TITLE
Text selection in the editor will be copied to clipboard automatically

### ISSUE THREAD

**Issue by shi-yan** [codercom/code-server#405]
- `code-server` version: top of tree
- OS Version: ubuntu 18.04 / and mac 

I often make a copy of a text (ctrl+c) and then I high-light a piece of another text I want to replace (by selection), and then hit ctrl-v to replace it.

but this doesn't work with code-server, because code-server automatically copy the text being highlighted into clipboard. This is annoying and I don't find a way to turn it off.

**Comment by nol166** [comment]
@shi-yan Is the server Ubuntu and the client is running macOS?

**Comment by cy91244** [comment]
Duplicated of #292

**Comment by shi-yan** [comment]
I run tested it on both ubuntu and mac

**Comment by nol166** [comment]
Closing this one to reduce duplicates. We can discuss in #292
