### ISSUE TITLE
Outline not available for markdown files

### ISSUE THREAD

**Issue by hslabbert** [codercom/code-server#406]
- `code-server` version: docker `codercom/code-server:latest` pulled March 15; can provide image hash if needed
- OS Version: docker 18.09.3

## Description

"Outline" view is not able to display headers/outline for markdown files.  Outline sidebar panel reads "There are no editors open that can provide outline information".  Markdown syntax highlighting is functioning, though.  Markdown file outline information is displayed in native vs code without any markdown extensions required.

## Steps to Reproduce

1. Open a markdown file.
1. Verify that file type is recognized as "Markdown".
1. Expand "Outline" panel in side bar.
1. See message that "There are no editors open that can provide outline information."

**Comment by code-asher** [comment]
Fixed by https://github.com/codercom/code-server/pull/472.
