### ISSUE TITLE
Error: EEXIST: file already exists when use cert

### ISSUE THREAD

**Issue by XiaolongMeng** [codercom/code-server#409]
./code-server --cert=./certs/code_server_certificate.crt --cert-key=./certs/code_server.key

ERROR { Error: EEXIST: file already exists, mkdir '/notebooks/notebook/serving/vs_fold/code-server1.408-vsc1.32.0-linux-x64/certs/code_server_certificate.crt'
  [stack]: 'Error: EEXIST: file already exists, mkdir \'/notebooks/notebook/serving/vs_fold/code-server1.408-vsc1.32.0-linux-x64/certs/code_server_certificate.crt\'',
  [message]: 'EEXIST: file already exists, mkdir \'/notebooks/notebook/serving/vs_fold/code-server1.408-vsc1.32.0-linux-x64/certs/code_server_certificate.crt\'',
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/notebooks/notebook/serving/vs_fold/code-server1.408-vsc1.32.0-linux-x64/certs/code_server_certificate.crt' }
*** Error in `./code-server': free(): invalid pointer: 0x00000000021fb168 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff09390a7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff09391337a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff09391753c]
./code-server(_ZN4node5StartEiPPc+0x3d9)[0x858a89]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ff0938b3830]
./code-server(_start+0x29)[0x81e7b9]

**Comment by liorchamla** [comment]
Same here :-) and an other bug if u use "~/certs" (in case your certs are in your home folder)

**Comment by cy91244** [comment]
Duplicated of #378

**Comment by nol166** [comment]
closing, lets continue discussion on #378
