### ISSUE TITLE
Does not list for Extensions with the "Preview" flag

### ISSUE THREAD

**Issue by bpmct** [codercom/code-server#41]
- `code-server` version: 1.31.0-20
- OS Version: Ubuntu 18.04
- Extension: https://marketplace.visualstudio.com/items?itemName=codecarrot.makerlog or https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream

#### Steps to Reproduce

1. Go to the Extension Marketplace
2. Search "Makerlog"
3. No results appear, unlike in desktop VSCode

I was also unable to install CodeStream via VSIX because of this error... **edit: looks like this is #92 **
![screenshot 2019-03-06 at 7 12 53 am](https://user-images.githubusercontent.com/22407953/53891475-4f2b3780-3fdf-11e9-8b9c-53957ca12311.png)

I'm otherwise loving it so far and I'm sure you guys are swamped... Keep up the great work!

**Comment by kylecarbs** [comment]
Will fix!

cc: @foresthoffman

**Comment by foresthoffman** [comment]
Both of these extensions are a bit unorthodox, so they'll have to be manually packaged. Generally speaking we try not to host extensions that are in Preview mode, because they are potentially unstable. It makes it even more tricky when the maintainers don't open source the project, or open source it on an unusual platform, e.g. GitLab.

**Comment by foresthoffman** [comment]
The `codecarrot.makerlog` extension should be available in about an hour. The CodeStream extension is a bit more involved, i'll get that up in the morning.

**Comment by foresthoffman** [comment]
Alrighty, version 0.35.0 of CodeStream should be available in an hour.

**Comment by foresthoffman** [comment]
@bpmct CodeStream and MarkerLog are up! Going to close this. Let me know if it works!
