### ISSUE TITLE
Improve self-hosted quickstart guide

### ISSUE THREAD

**Issue by AdriBusse** [codercom/code-server#414]
Hello,

I try to install code-server on my ec2 instance. After i starting ist I get this error:

ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/root/.local/share/code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/root/.local/share/code-server/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:52540:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}

Can you help me what it means? If this appear I dont have access to code-server.

Thank you 
Adrian

**Comment by coadler** [comment]
See https://github.com/codercom/code-server/issues/121. The error is more of a warning and doesn't cause any issues

**Comment by nol166** [comment]
try: try running mkdir -p /home/{your_username}/.code-server/User/workspaceStorage
