### ISSUE TITLE
svn-scm is not working

### ISSUE THREAD

**Issue by WengShengyuan** [codercom/code-server#423]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: macOS Mojave 10.14.4
- Extension: svn

## Description
1. Click "+" button, or refresh button ,shows 'svn.repolog.addrepolike' not found, or 'svn.repolog.refresh' not found.
2. SOURCE CONTROL panel shows 'No source control providers registered.'

## Steps to Reproduce
step1. I tried download svn vsix file and install offline or install directly in vscode, and none of those work.
step2. Click "+" button, or refresh button ,shows 'svn.repolog.addrepolike' not found, or 'svn.repolog.refresh' not found.

<img width="1389" alt="屏幕快照 2019-04-04 20 12 41" src="https://user-images.githubusercontent.com/9462331/55556381-0a97d680-571a-11e9-9fdb-1b07c3a5ceee.png">

**Comment by Multishifties** [comment]
Duplicate issue of https://github.com/codercom/code-server/issues/424

**Comment by NewHms** [comment]
hello,I had the same problem，can you tell me how can fix it？ thank you
