### ISSUE TITLE
Select all in right click menu

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#428]
It might be neat to have a select all option available in the right-click menu

![image](https://user-images.githubusercontent.com/5651438/55581970-e9b48e80-56e3-11e9-8536-b6101c92e353.png)

**Comment by Multishifties** [comment]
I mean, `cmd + a` does exactly that. So does clicking and dragging the mouse. And native VSCode doesn't have "select all" as an option. 

Its certainly interesting, but how often do you think a user would use it? Have any users requested this?

**Comment by nol166** [comment]
@Multishifties ah, you are correct. I assumed it did.
