### ISSUE TITLE
extension compatible with current version '1.31.0' of VS Code is not found.

### ISSUE THREAD

**Issue by aiyolo** [codercom/code-server#43]
- `code-server` version: 1.31.0
- OS Version: ubuntu 16.04
- Extension: settings-sync, chinese-language-pack 

#### Steps to Reproduce

1. install settings-sync
2. errors like
Unable to install because, the extension 'shan.code-settings-sync' compatible with current version '1.31.0' of VS Code is not found.

**Comment by nol166** [comment]
@foresthoffman

**Comment by kylecarbs** [comment]
Thanks for the report, we'll fix this asap!

**Comment by foresthoffman** [comment]
Ah, it appears that settings-sync has a rather aggressive version constraint: `^1.31.1`. We're currently providing `1.31.0`, so that explains why it would be failing to install. I've made sure that our version of settings-sync is up to date, so when we update vscode to fulfill that constraint, this should be solved.

**Comment by aiyolo** [comment]
@foresthoffman thank you

_Sent from my MI 8 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by kylecarbs** [comment]
https://github.com/codercom/code-server/pull/45

**Comment by sujunmin** [comment]
I think #45 can not fix this, because I just pull latest docker and it says

Unable to install because, the extension 'ms-ceintl.vscode-language-pack-zh-hant' compatible with current version '1.31.1' of VS Code is not found.

So it seems this extension will check vscode version by using someway.

**Comment by sujunmin** [comment]
I've pull down the newst docker image from docker hub, and there is no error for installing chinese language package, and it also shows the need to restart vscode to apply, but when I restart it will be at disable extension list, so I can not apply this extension.

**Comment by foresthoffman** [comment]
The most recent versions of the Chinese language pack are even more strict (than Settings Sync) with the version of VS Code that they require. Version `1.32.4` appears to require at least VS Code `1.32.0`.

I believe this will be resolved when we update code-server to `1.32.x`.

**Comment by sujunmin** [comment]
> The most recent versions of the Chinese language pack are even more strict (than Settings Sync) with the version of VS Code that they require. Version `1.32.4` appears to require at least VS Code `1.32.0`.
> 
> I believe this will be resolved when we update code-server to `1.32.x`.

Yes, I test from the docker build locally from the latest source code, and install successfully, the extension is displayed at enable list, but the UI still is in English, the extension description show it need to modify `locale.json` to fit this extension, but I can not modify it by the instruction.
```
Once installed, set "locale": "zh-tw" in locale.json to load Chinese (Traditional) Language Pack. To modify locale.json press Ctrl+Shift+P to bring up the Command Palette, start typing "config" to filter the list of available commands, then select the Configure Language command. See Docs for more information.
```
Maybe this issue is another issue, not the version issue.

**Comment by foresthoffman** [comment]
Interesting. Are you getting permission errors when attempting to modify the `locale.json` file?

**Comment by sujunmin** [comment]
Finally I found how to change by inputing "display" in command palette or edit `locale.json` directly from console, the results are the same, nothing happened, like #215 comment.

**Comment by kylecarbs** [comment]
Should be fixed. Locale issue can continue in https://github.com/codercom/code-server/issues/215
