### ISSUE TITLE
Moving file to another folder throws console error

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#434]
- `code-server` version: v1.604-vsc1.32.0
- OS Version: 10.14.4 (18E226)

## Description
Dragging and dropping one file to another results in an error.

`Error: Cannot parse time: [object Object]`

## Steps to Reproduce
1. Click and drag a file from one folder to another

**Comment by Multishifties** [comment]
Duplicate of https://github.com/codercom/code-server/issues/253
