### ISSUE TITLE
Search in folder <-- now working

### ISSUE THREAD

**Issue by peterremote1980** [codercom/code-server#438]
Hi
    "Search in folder" not working, "Go to file", also nothing there.
thanks
From Peter

**Comment by kylecarbs** [comment]
Will fix.

**Comment by andreimc** [comment]
Duplicate of https://github.com/codercom/code-server/issues/392

**Comment by kylecarbs** [comment]
Fixed with the [latest pre-release](https://github.com/codercom/code-server/releases/tag/1.696-vsc1.33.0).
