### ISSUE TITLE
Running Coder in a Docker container would get stuck on waiting for shared process to start

### ISSUE THREAD

**Issue by sr229** [codercom/code-server#44]
`code-server` does not seem to like Docker well or does not like the pseudo-user hacks for it.

Tested with my custom [Coder stack](https://github.com/sr229/code-server-openshift).

- `code-server` version: =< 1.13.0
- OS Version: Debian 9, Google Cloud Platform

Related to #9 

#### Steps to Reproduce

1. Run `chinodesuuu/coder`
2. Notice the logs that its stuck in waiting for shared process to start.

**Comment by frol** [comment]
Is it related to #13?

**Comment by kylecarbs** [comment]
This is interesting. I've used it using `ubuntu` as the base-image and it seems to do fine. Will test!

**Comment by bketelsen** [comment]
for me this seems to boil down to something in 18.10 being the breaking factor.  18.04 works, 18.10 doesn't (inside or out of docker)

**Comment by 0xfd000000** [comment]
just to add another data point: the same issue happens on my Arch Linux install, kernel version 5.0.0

**Comment by frol** [comment]
@0xfd000000 it works fine on my Arch Linux powered laptop. It must be something related to the dependencies...

**Comment by kylecarbs** [comment]
It was mentioned that installing netstat resolved it for someone. Might be
worth a shot.

**Comment by bketelsen** [comment]
confirmed, installing `net-tools` on ubuntu fixed the issue both on bare metal and in Docker.  That's a strange one.

**Comment by kylecarbs** [comment]
Wonderful. We’ll have to throw an error if we see it isn’t installed.

**Comment by 0xfd000000** [comment]
ACK installing net-tools fixed in on Arch, too

**Comment by sr229** [comment]
Thanks for letting me know @bketelsen. Image will be updated !anually soon

**Comment by sr229** [comment]
Alright can confirm Coder requires `net-tools` to work. Do I close this or wait for the commit that throws the error when `net-tools` isn't installed?

**Comment by kylecarbs** [comment]
Let’s wait for the commit. Could be confusing to people in the meantime

**Comment by nhooyr** [comment]
There is also an official docker image now so that should alleviate this.

**Comment by sr229** [comment]
This is now a resolved issue. Closing.
