### ISSUE TITLE
Copy on Selection cannot be disabled

### ISSUE THREAD

**Issue by tjlian616** [codercom/code-server#443]
- `code-server` version: code-server-1.31.1-100-linux-x64
- OS Version: ubuntu 16.04.6 LTS on Google Compute

## Description

The editor default copies any text that is selected. And there is no way to turn this off.  The Copy on Selection is OFF in settings.

## Steps to Reproduce

1. Use mouse to select some text
2. Cmd+V (or Edit-Paste). 
3. The text selected in step 1 is pasted.

**Comment by nol166** [comment]
I would update your version of code-server. It looks like this issue was fixed.

**Comment by kylecarbs** [comment]
Fixed in https://github.com/codercom/code-server/commit/2bc6e1a457b4ca5298f5207d164a3699ec443bfc
