### ISSUE TITLE
Base container with binary only, or url to latest binary to download.

### ISSUE THREAD

**Issue by Zate** [codercom/code-server#447]
I'd like to build some containers customized to individual languages.  It would make this build process much simpler if there was either a single stage base build consisting of the first stage in the dockerfile now, and running via a CI/CD type action to rebuild when master is updated. Something like codercom/code-server-{arch}:latest.  We could then use it as the first FROM statement and copy the binary from it (but not have to build it each time).

OR 

A repeatable way to download the latest code-server binary for linux/OSX as part of an ADD statement in a Dockerfile.

I think either would work, or perhaps there is other options, but really, i just want a consistent way to get the latest code-server binary in an automated fashion.

Bonus points if it's something I can point my own CI/CD to to kick off a rebuild of my container when the binary changes (and I could do that with a base image in docker hub I believe, not sure about just a url to download the binary)

**Comment by kylecarbs** [comment]
Perhaps hosting the latest binary at something like `codesrv.cdr.sh/latest-linux` would be good?

Pulling from `codercom/code-server:latest` should always provide you with the latest image. As for a trigger, I'm not sure the best way to handle that. Any ideas @nhooyr ?

**Comment by nhooyr** [comment]
You can just copy the binary from `codercom/code-server:1.621`. See how the current Dockerfile does it.

**Comment by nhooyr** [comment]
As for the trigger, you can already do that. You can run docker pull periodically (like https://askubuntu.com/a/1074874), curl the latest release and see if the version number changed, I believe you can also subscribe to releases via the github API but I might be wrong.

**Comment by Zate** [comment]
yeah building from codercom/code-server:latest as a base works to grab the binary.  All good, thanks.
