### ISSUE TITLE
Servers down, cannot login

### ISSUE THREAD

**Issue by JPJ98** [codercom/code-server#458]
I cannot login to code on my browser, the servers are down! I am stuck on the loading screen.

![Screenshot (1)](https://user-images.githubusercontent.com/13618065/55697111-85b0f500-5985-11e9-8863-6ef97660def9.png)

**Comment by JPJ98** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/13618065/55697211-eb9d7c80-5985-11e9-8cf7-801c01f4e8d1.png)
![Screenshot (2)](https://user-images.githubusercontent.com/13618065/55697213-ed674000-5985-11e9-8a68-010cdf8cbe53.png)

**Comment by ammario** [comment]
@JPJ98 please reach out to support with your Coder email to have this investigated.

**Comment by nol166** [comment]
@JPJ98 I searched for the email you sent me via the support ticket but there doesn't seem to be an account tied to that email. Is there a another email that you may have used when signing up with Github or Google?

**Comment by JPJ98** [comment]
No I signed up with joshpate98@gmail.com

**Comment by JPJ98** [comment]
How do I open the terminal or get over this issue. And it's associated with
the google account gmail: joshpate98@gmail.com
