### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by Mehran** [codercom/code-server#459]
os Debian 9.0

```docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/home/coder/project\") set in config.json failed: permission denied": unknown.```

**Comment by saadat99** [comment]
same
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/home/coder/project\") set in config.json failed: permission denied": unknown.

**Comment by sr229** [comment]
Workaround is to bind mount to those directories. I'll make a patch to add VOLUME stage so this doesn't happen.

**Comment by vimota** [comment]
Anything we can do to resolve this until it's released?

**Comment by isaacirosado** [comment]
@vimota the workaround is to set group write permissions for $PATH before bind-mounting, e.g.

`chmod g+w $PATH`

That's what the fix implemented by @sr229 is doing, but inside the container after the bind-mount happens (thanks for that BTW, coder is awesome!)
