### ISSUE TITLE
Translate documentation

### ISSUE THREAD

**Issue by Multishifties** [codercom/code-server#47]
It would be nice to have the documentation for this repo available in different languages for non-english speaking users.

This would definitely be a continuous ongoing community-driven effort. This issue will never truly be "complete" as it will have to evolve as our docs are updated, but I believe the efforts will be worthwhile.

- [ ] Turkish 
- [ ] Spanish
- [ ] French
- [ ] German
- [ ] Hebrew
- [ ] Italian
- [ ] Japanese
- [ ] Korean
- [ ] Mandarin
- [ ] Cantonese
- [ ] Arabic
- [ ] Czech
- [ ] Danish
- [ ] Dutch
- [ ] Finnish
- [ ] Greek
- [ ] Hindi
- [ ] Hungarian
- [ ] Indonesian
- [ ] Norwegian
- [ ] Polish
- [ ] Portuguese
- [ ] Romanian
- [ ] Russian
- [ ] Slovak
- [ ] Swedish
- [ ] Thai

**Comment by nol166** [comment]
Added a checklist. Please add any that are not in that list.

**Comment by Multishifties** [comment]
Removed a duplicate from the list. I'll also be adding contributor names next to their contributions.

**Comment by kylecarbs** [comment]
Not certain we should promote this, feels like a lot to maintain. Is there an example of a repo that does it well?

What are your thoughts? cc: @nhooyr @coderasher

**Comment by nhooyr** [comment]
Why don't we just do what vscode does? https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

We don't maintain the translations at all, its a community driven effort to fix/update them. If we can't find a translation for something, we just use the English.

**Comment by kylecarbs** [comment]
This is related to documentation within this repository.

**Comment by nhooyr** [comment]
Ah, I would recommend against it. Putting translation stuff in this repository means we take ownership of it, which we don't want to do. Maybe we could have a wiki with community translated docs like Go.

https://github.com/golang/go/wiki/NonEnglish

**Comment by kylecarbs** [comment]
Going to close for now, as this could be a ton of work to maintain.

If there's enough interest in this, we can bring it back.

**Comment by nhooyr** [comment]
@kylecarbs I think we should document this somewhere in the docs at least.

**Comment by weditor** [comment]
https://github.com/codercom/code-server/pull/50

I would like to close this pull request. 
I'll keep an eye on this project. I may open another pr if you still need document translation in the future,

**Comment by Multishifties** [comment]
Closing in favor of https://github.com/codercom/code-server/issues/401
