### ISSUE TITLE
-bash: ./code-server: Permission denied

### ISSUE THREAD

**Issue by zhengduoru** [codercom/code-server#476]
I don't have the root permission. when I run : ./code-server, it comes the error message blow。
-bash: ./code-server: Permission denied

So can I use code-server without root permission?

**Comment by davea** [comment]
Try `chmod +x code-server` first.

**Comment by sr229** [comment]
@zhengduoru you forgot to set your binary's mode. Use `chmod -R 755 code-server` and it should work.

**Comment by zhengduoru** [comment]
@davea @sr229 thank you! The error message changed after I try chmod.

My system is Centos 7.  And I use code-server1.696-vsc1.33.0-linux-x64. And I don't have the root permission of the system. When I tried again, it came the error below. 

$ ./code-server .
Segmentation fault

**Comment by nol166** [comment]
@zhengduoru Can you make a new issue about the segmentation fault with the info about what version you are running and the OS?
