### ISSUE TITLE
Add back SSH popup

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#48]
It would be nice to provide users quick access to their public IP, port and SSH password via a small popup in the bottom right of the IDE

**Comment by Multishifties** [comment]
@nol166 Why was this closed? Does this functionality already exist? Are we planning on making this a coder-hosted option only?

**Comment by nol166** [comment]
It doesn't relate to the open source binary, only the ide.coder.com hosted version. TLDR: wrong repo
