### ISSUE TITLE
Empty selection clipboard

### ISSUE THREAD

**Issue by nrlulz** [codercom/code-server#487]
- `code-server` version: 1.604-vsc1.32.0 binary
- OS Version: Ubuntu 16.04, AWS

## Description

After updating 1.604, the "Empty Selection Clipboard" setting does not seem to work anymore. Confirmed it works as expected in 1.408, does not work in 1.604, 1.691 or 1.696.

## Steps to Reproduce

1. Launch code-server
1. Create new file, enter text on multiple lines
1. Place cursor in the middle of a line with no text selected
1. ctrl+x to cut line
1. line is removed and copied to clipboard as expected on 1.408, nothing happens on 1.604 onward

**Comment by nol166** [comment]
Thank you for reporting this!

**Comment by nol166** [comment]
@nrlulz just to clarify, the line doesn't get removed from the editor nor copied to the clipboard in v1.604?

**Comment by nrlulz** [comment]
@nol166 correct. the same applies for copying with an empty selection, it would copy the line without removing it but it does not get copied to the clipboard anymore.

**Comment by jrpub** [comment]
Might be related to #443, #376 and many others. 
I think this must be solved as this is subject to many bug reports.

**Comment by lamnguyen95** [comment]
I can confirm that this is the real issue in current version of code-server.

**Comment by kylecarbs** [comment]
Should be fixed with https://github.com/codercom/code-server/commit/2bc6e1a457b4ca5298f5207d164a3699ec443bfc. Release coming out soon!

**Comment by imtoanle** [comment]
- code-server version: 3.11.1
- OS Version: Ubuntu 18.04

I still got this issue. Any one can confirm this ?
Thanks

**Comment by jsjoeio** [comment]
@imtoanle please open a bug report!
