### ISSUE TITLE
Icons missing from Source Control Changes bar

### ISSUE THREAD

**Issue by jrowen** [codercom/code-server#489]
- `code-server` version: 1.696-vsc1.33.0
- OS Version: Debian GNU/Linux 9 \n \l (Docker container)

## Description

On the Source Control view, the Changes bar is missing icons.  If I mouse over the bar, I see the hint text appear where the icons should be.  As far as I can tell, similar bars within other views are showing icons.

**Comment by sr229** [comment]
Can you show a screenshot? It might be your cache so try a hard reload with empty cache (Ctrl + Shift + R in Chrome)

**Comment by jrowen** [comment]
The hard reload fixed it.  Thanks.
