### ISSUE TITLE
Run code-server on OrangePi

### ISSUE THREAD

**Issue by afonsosantos** [codercom/code-server#492]
## Description

Can I run code-server on Orange Pi Zero? Here's a link for the board: [http://bit.ly/2X8akb1](url). It has 512 MB of RAM and ARM Cortex-A7 Quad-core 1.2 GHz.

![image](https://user-images.githubusercontent.com/46262740/56039309-eb0d3900-5d2b-11e9-8930-041ecaf8e007.png)

**Comment by sr229** [comment]
It’s not possible with that specs. However we’re discussing the potential vectors to reduce memory usage so you can use it to your SBC.

**Comment by afonsosantos** [comment]
Thanks for the reply!

And what about this one, also from Orange Pi family?

![image](https://user-images.githubusercontent.com/46262740/56043907-041ae780-5d36-11e9-917d-fc1e2693000f.png)

**Comment by sr229** [comment]
I recommend something that has at least 2GB RAM since code-server eats 1GB currently.

**Comment by afonsosantos** [comment]
Ok, thanks!
