### ISSUE TITLE
Make Asset Paths Relative

### ISSUE THREAD

**Issue by srsgores** [codercom/code-server#497]
Deploying code-server to a nested URL such as `/code` will result in assets being requested from `/`, when they should be `/code`.

The HTML source code references root-level assets:

```
<script type="text/javascript" src="main.js"></script>
```

We should, instead, allow users to specify if they are hosting on a nested URL like `/code`, thus appending the host to the HTML:

```
./code-server --host=0.0.0.0/code
```

```
<script type="text/javascript" src="/code/main.js"></script>
```

## Reproduction Steps
1. Deploy to a URL like `/code`, or `/johhny/codes`
2. Start code server
3. Visit the URL, and observe that assets are not requested from the desired URL (`code`), but instead, are requested from the root `/` URL

**Comment by RyanEwen** [comment]
Came here to report the same thing when reverse proxying with NGINX to /code

**Comment by code-asher** [comment]
Paths are relative now.

**Comment by RyanEwen** [comment]
Awesome. How do we specify the URL?

**Comment by code-asher** [comment]
It's relative, so you don't need to specify anything. If code server is available at `/code`, resource requests will go to `/code/resource`, for example.

**Comment by RyanEwen** [comment]
I just wanted to report that this does work, however I sometimes get redirected away from my /code to /login which doesn't exist (should be /code/login)
