### ISSUE TITLE
 scandir '/home/ubuntu/.local/share/code-server/User/workspaceStorage'

### ISSUE THREAD

**Issue by Lin-boy** [codercom/code-server#499]
Ubuntu 18.04. The binary  1.791,vsc1.33.1.I tried to deploy on AWS ec2 but:
<img width="886" alt="d4c2a5dbf97cd0fd022be4d40a2b799" src="https://user-images.githubusercontent.com/43169067/56102307-d664b700-5f5e-11e9-90e3-3d2295aa67c1.png">

**Comment by fnoopv** [comment]
same error

**Comment by llorentegerman** [comment]
@Lin-boy have you been able to fix it?

**Comment by nol166** [comment]
I received this message using the 1.792 pre-release but it didn't occur the second time I ran code-server. I believe it is checking for that file before it actually gets created.

**Comment by dominicseung** [comment]
Same error on Centos 7 using the docker.

**Comment by MrBLJ** [comment]
Same here as well, on debian 9.

**Comment by nol166** [comment]
Re-opening as this issue appears to still valid

**Comment by nol166** [comment]
![image](https://user-images.githubusercontent.com/5651438/56222278-58251500-6031-11e9-9d9e-34694c8e01b1.png)

**Comment by Lin-boy** [comment]
I created a folder path : .../User/workspaceStorage ,It works.After I created the path, it shows insufficient memory，so I also  improved the memory of the server.It works well.I don't know why.

**Comment by nol166** [comment]
@Lin-boy likewise. I will still leave this open until it is fixed.
