### ISSUE TITLE
About service

### ISSUE THREAD

**Issue by 1035311527** [codercom/code-server#500]
Is that possible to run a GUI project on the service?

**Comment by Multishifties** [comment]
@1035311527 I'm not certain I understand, can you be a little more specific please?

**Comment by Vap0r1ze** [comment]
He wants a GUI

**Comment by foresthoffman** [comment]
I believe the question is if it would be possible to run a headful application via code-server. Is that correct @1035311527? Do you already have a particular setup in mind that can be achieved with the official VSCode?
