### ISSUE TITLE
Can't Install from .vsix

### ISSUE THREAD

**Issue by tecosaur** [codercom/code-server#508]
- Code-server version: `1.792-vsc1.33.1`
- OS Version: Debian 9.8

## Description

I cannot see how to install an extension from a `.vsix`, the files seem greyed out.

![image](https://user-images.githubusercontent.com/20903656/56275635-ad494f80-6133-11e9-8264-7d001ae42742.png)

## Steps to Reproduce

1. Install code-server binary
2. Download `.vsix` to /tmp
3. `chmod 777 <filename>.vsix`
4. Try to install `.vsix`

**Comment by patrickstjohn** [comment]
If you do the equivalent of this in your Dockerfile they install properly. This is what we've been doing and it seems to work pretty well.

```
RUN mkdir -p /home/coder/.code-server/extensions
RUN curl -JL https://github.com/mhutchie/vscode-git-graph/releases/download/v1.4.5/git-graph-1.4.5.vsix | bsdtar -xvf - extension
RUN mv extension /home/coder/.code-server/extensions/git-graph-1.4.5
```

**Comment by tecosaur** [comment]
Thanks! That worked for me. Still an issue that you can't install from a `.vsix` though.

**Comment by VirtualL** [comment]
I have the same issue, on the latest version.
