### ISSUE TITLE
Connect to jupyterlab from code-server in docker

### ISSUE THREAD

**Issue by vnijs** [codercom/code-server#524]
- `code-server` version: 1.854-vsc1.33.1
- OS Version: Docker with Ubuntu 18.04 on macOS

## Description

I can now connect to a running Jupyter (python) kernel but code sent to the `Python Interactive Window` throws bash errors. I don't think this is an extension issue as this works fine when running desktop vscode and the microsoft python extension. 

![Screen Shot 2019-04-17 at 4 16 36 PM](https://user-images.githubusercontent.com/2998956/56326966-0b266900-612d-11e9-936d-471d878bfcfd.png)

## Steps to Reproduce

You can run a docker image at vnijs/rsm-editors or run a bash script through the command below and press 3 when the menu shows up. Jupyter lab will be accessible through localhost on port 8989

`
source <(curl -s https://raw.githubusercontent.com/radiant-rstats/docker/master/launch-rsm-editors.sh)
`

Install the Microsoft python extension since I haven't figured out how to include that in the image:

https://marketplace.visualstudio.com/itemdetails?itemName=ms-python.python

Use the command palette to get to "Python: Specify Jupyter server Url" and enter

`http://localhost:8989/?token=jupyter`

Finally, try to send python code to the `Python Interactive Window` by right clicking in a python source code file and then the same errors should show up.

**Comment by vnijs** [comment]
I'm now thinking it might be a vscode on linux issue since I replicated it from Desktop vscode on linux. See issue linked below. Let me know if you want me to close the current issue

https://github.com/Microsoft/vscode-python/issues/5357

**Comment by Multishifties** [comment]
I suspect you may also have this issue, https://github.com/codercom/code-server/issues/220

**Comment by vnijs** [comment]
Perhaps @Multishifties. But then I would have expected the connection to fail which is not the case.

**Comment by vnijs** [comment]
Seems this is issue is resolved in the development version of vscode-python mentioned in the link below. I also changed two settings for jupyter:

![image](https://user-images.githubusercontent.com/2998956/56466436-26aca080-63c7-11e9-95fa-987762b042e4.png)

https://github.com/Microsoft/vscode-python/issues/5314
