### ISSUE TITLE
Enter key not working, `n is null` Notification.

### ISSUE THREAD

**Issue by nbsdx** [codercom/code-server#525]
- `code-server` version: 1.604-vsc1.32.0
- OS Version: Gentoo
- Browser Version: Firefox 66.0.3 (Windows 10)

## Description

Occasionally the enter key will stop working in `code-server`, and a Notification will pop up with the contents `n is null`. 

## Steps to Reproduce

Reproduction steps are unknown, as it happens sporadically. Refreshing the browser fixes it.

## Other Notes

I do have the Rust RLS Extension installed (manually via the `vsix` file), so it might be that, but I haven't see any bug reports with "n is null" in them.

No logs at all are generated when this happen - not in the browser console or from the `code-server` app itself.

**Comment by kylecarbs** [comment]
Could you try on the latest version?

**Comment by nbsdx** [comment]
Sure, report back if it's still present.

**Comment by nol166** [comment]
@nbsdx Any update on this one?

**Comment by nbsdx** [comment]
@nol166 I haven't seen it again, I'll close this for now. If it happens again I'll reopen the issue (hopefully with more information :/)

**Comment by danog** [comment]
Hmm, I'm encountering this issue too with the latest version

**Comment by jsjoeio** [comment]
Very strange. I've never seen this before 🤔 Can you share more about your environment @danog?

**Comment by danog** [comment]
I'm using https://github.com/filips123/PWAsForFirefox/ on pure wayland, no xwayland.

**Comment by jsjoeio** [comment]
Hmm...i'm not familiar with that. Well if it keeps happening and you want to provide steps to reproduce, let me know and I can look into it.
