### ISSUE TITLE
Blank Screen on iOS - Self Hosted

### ISSUE THREAD

**Issue by marcmaceira** [codercom/code-server#530]
After successfully logging in, the IDE does not load. Logs indicate it's starting and loosing connection to socket continuously.

iOS Version: 12.2
Cloud Provider: DigitalOcean
Host OS: Ubuntu 18.10

Log image:
![image](https://user-images.githubusercontent.com/22581906/56373316-ad4a5d80-61ce-11e9-85b0-1595a3daab72.png)

**Comment by nol166** [comment]
Existing discussion: https://github.com/codercom/code-server/issues/89
