### ISSUE TITLE
Ctrl+x not working properly

### ISSUE THREAD

**Issue by toreskogp** [codercom/code-server#533]
- `code-server` version: 1.868-vsc1.33.1
- OS Version: Ubuntu 16.04.4 LTS

## Description

Ctrl+x seems not to work like in vs code. When nothing is selected the whole line gets cut in vs code. In code server, it seems like nothing happens unless some code is marked.

## Steps to Reproduce

1. Set the cursor somewhere in the editor
1. Press Ctrl+x

**Comment by nol166** [comment]
Let's pick up the conversion in https://github.com/codercom/code-server/issues/487
