### ISSUE TITLE
Can't open files via File->Open

### ISSUE THREAD

**Issue by Timmmm** [codercom/code-server#535]
- `code-server` version: 1.868-vsc1.33.1
- OS Version: 18.04

## Description

If I click File->Open I can't actually select any files. They are all greyed out and cannot be selected. I also cannot click "open".

## Steps to Reproduce

1. File->Open...
2. Try to select a file.

**Comment by foresthoffman** [comment]
Related #490

**Comment by Timmmm** [comment]
That was fast, thanks!

**Comment by code-asher** [comment]
We'll have a release soon that you can download with the fix, we'll also push a new Docker image up soon.
