### ISSUE TITLE
Unable to run, `Read Only Filesystem`

### ISSUE THREAD

**Issue by Merith-TK** [codercom/code-server#540]
- `code-server` version: Docker:Latest
- OS Version: Ubuntu server 18.04, Self Hosted 4gb ram, Core Duo

## Description
```
root@merith-tk:/opt/VSCODE# docker run -it -p 127.0.0.1:8443:8443 -v "/opt/VSCODE:/opt/VSCODE" codercom/code-server -e /opt/V
SCODE/extensions/ -d /opt/VSCODE/data/ -H -P Novakir1
docker: Error response from daemon: error while creating mount source path '/opt/VSCODE': mkdir /opt/VSCODE: read-only file system.
```
## Steps to Reproduce
Copy setup above

**Comment by nol166** [comment]
Did you install docker with something called snap? It seems other docker users have reported the same problem when docker was installed that way.

It will show up in the list after running `sudo snap list`

**Comment by Merith-TK** [comment]
Yeah, thats how it was installed

**Comment by nol166** [comment]
The snap version of Docker is no longer maintained so I suspect that uninstalling (`sudo snap remove`) that one and installing the latest will do the trick.
