### ISSUE TITLE
AWS Student Free Tier -EC2 Server?

### ISSUE THREAD

**Issue by Knoir** [codercom/code-server#553]
## Description
I searched and couldn't find the question on here. Being new to AWS, I'm unsure which kind of server I'm able to run this on. the EC2 server structure I have access too are CLI over SSH only. Are those simply for DBs and deployment? If so, which kind of server should I use, and if not, will this still work when I connect to the server's port?

## Related Issues
Which distro should I use as far as what AWS offers?

**Comment by Lin-boy** [comment]
attention memory of server at least 2G.you can click here to konw offical description https://github.com/codercom/code-server/blob/master/doc/admin/install/aws.md
<img width="733" alt="5f0e15673873d4468b3733afb0da936" src="https://user-images.githubusercontent.com/43169067/56455798-d5d08400-6395-11e9-9062-9dd73d378096.png">

**Comment by Knoir** [comment]
Thanks man! It’s pretty much the same steps as anything else I’ve done! Just glade it’ll work regardless!
