### ISSUE TITLE
Docker image does not respond (windows)

### ISSUE THREAD

**Issue by sbcgua** [codercom/code-server#558]
- `code-server` version: 1.868
- OS Version: Windows 7 + Virtualbox + docker

## Description

Docker image starts but does not respond

## Steps to Reproduce

1. run `docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth`
2. It starts properly (log below) ...
3. ...But does not respond to localhost:8443 (http and https)

### Log

```
$ docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
(node:5) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server development
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/coder/.local/share/code-server","extensions-dir":"/home/coder/.local/share/code-server/extensions","working-dir":"/home/coder/project","log-dir":"/home/coder/.cache/code-server/logs/20190421212533617"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/codercom/code-server/blob/master/doc/security/ssl.md
WARN  Launched without authentication.
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
WARN  stderr {"data":"(node:20) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
```

## Attempts to solve:

- `netstat -tan` inside docker machine shows listening app at 127.0.0.1:8443, so I forwarded this port from virtualbox to host - didn't help
- `curl 127.0.0.1:8443` inside docker machine outputs html `... Not found...` whereas log shows `Error: ENOENT: no such file or directory, open '/src/packages/server/build/web/index.html'` after this

**Comment by nol166** [comment]
I am not a docker expert, but what if you remove 127.0.0.1 from the beginning of the port flag?
`-p 8443:8443`

**Comment by sbcgua** [comment]
seems like the comment was deleted ... but the `docker run -it -p 8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth` (no IP in port param) helped. Although localhost still does not work - I had to put docker IP in browser (192.168.99.100 in my case)

**Comment by yyynnn** [comment]
This should be in the docs.

e.g. Jira's docs provide this command (could be used as an example):

`docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira:latest`

translating to: 

### Execute in your base env:
```bash
docker run --detach --publish 8443:8443 -v ${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
```
### Then find your docker container external IP with: 

```bash
ip address show
```

### Then navigate to this in your browser:

`http://dockerip:8443/`

Easy peasy
