### ISSUE TITLE
Microsoft's cpptools extension is not able to start its language server

### ISSUE THREAD

**Issue by coder3101** [codercom/code-server#56]
- `code-server` version: 1.31 (latest)
- OS Version: 16.04, on Google Cloud

#### Steps to Reproduce

1. Install C++ extension
2. Open any C++ File 

The following Error message is displayed

>Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError: Path must be a string. Received undefined

**Comment by kylecarbs** [comment]
cc: @foresthoffman

**Comment by kylecarbs** [comment]
I believe this is fixed.
