### ISSUE TITLE
Make a tuto to build it

### ISSUE THREAD

**Issue by clintnetwork** [codercom/code-server#566]
Hi,

please make a simple tuto to rrun code-server without downloading binary

thx

**Comment by nol166** [comment]
Should have build steps soon in the docs. Linked a PR that has the build steps in a file called `build.md`

**Comment by oonqt** [comment]
Basic build instructions:
git clone git://github.com/codercom/code-server.git
cd code-server
npm install
scripts/build.sh

then your build will be saved in -> packages/server/cli-linux-(arch)

**Comment by clintnetwork** [comment]
Ha nice, thanks, but it crash:

```C:\Users\me\temp\code-server\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\me\temp\code-server\node_modules\node-pty
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-04-24T10_07_36_401Z-debug.log```

**Comment by oonqt** [comment]
> Ha nice, thanks, but npm crash:
> 
> ```
> gyp ERR! UNCAUGHT EXCEPTION
> gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
> gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
> gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\me\temp\code-server\node_modules\node-pty
> gyp ERR! node -v v10.13.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 7
> npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
> npm ERR! Exit status 7
> npm ERR!
> npm ERR! Failed at the node-pty@0.8.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-04-24T10_07_36_401Z-debug.log```
> ```

Try to update node-gyp using ```npm install -g node-gyp@latest```

**Comment by clintnetwork** [comment]
Don't work, I will kill the creator of npm

```
npm ERR! node-pty@0.8.1 install: `node scripts/install.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-pty@0.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-04-24T20_53_14_968Z-debug.log```

**Comment by oonqt** [comment]
https://github.com/nodejs/node-gyp/issues I would make an issue thread to get it resolved, this shouldn't be happening

**Comment by code-asher** [comment]
Closing in favor of #417.
