### ISSUE TITLE
how to run code-server on debian armhf?

### ISSUE THREAD

**Issue by weixinya** [codercom/code-server#571]

**Comment by weixinya** [comment]
I deploy debian armhf on Android 8.0 with linuxdeploy.

**Comment by nol166** [comment]
@weixinya We are still working on getting the arm binaries to work properly. Shouldn't be much longer before we have a proper release for it.

**Comment by weixinya** [comment]
@nol166 Thank you very much!

**Comment by sr229** [comment]
Should be closed in favor of the ARM issue we already have.

**Comment by nol166** [comment]
#35 closing
