### ISSUE TITLE
Missing extensions

### ISSUE THREAD

**Issue by resure** [codercom/code-server#577]
- code-server version: `1.903-vsc1.33.1`
- OS Version: Ubuntu 18.04 on Yandex.Cloud, Ubuntu 18.04 on Linode, Ubuntu 18.04 on colocated server.

## Description

Strangely, it's not possible to find some extensions in CodeServer, while they are available in regular VSCode. 

## Steps to Reproduce

For example, let's take a look at search results for theme that I've used on my local VSCode, `Monokai Pro`:

<img width="304" alt="vscode" src="https://user-images.githubusercontent.com/168296/56618100-3f68c080-662a-11e9-8837-f9bc6eeffefa.png">

Second result. And now same search, but on codeserver:

<img width="369" alt="codeserver" src="https://user-images.githubusercontent.com/168296/56618099-3f68c080-662a-11e9-895b-6e441c8cb1eb.png">

It's missing sought extension and also results are generally looking pretty incomplete.

**Comment by foresthoffman** [comment]
Hi, @resure. Yes, there are extensions that are in the Official VS Code Extension Marketplace, that are not in the Code extension marketplace. This is due to the Official Marketplace API being closed to the public.

Please list the IDs (<author>.<id>) for any extensions/themes that you'd like to see on the Coder Marketplace and I'll see what I can do.

**Comment by resure** [comment]
Ah, understood. I don't have any extensions that I'm lacking right now, just wanted to know, why it works that way. Thank you for clarifying.

Sometimes it doesn't load any results, is that server issue on your side?

![2019-04-24_11-51-55](https://user-images.githubusercontent.com/168296/56646006-60133380-6687-11e9-983a-c6912fab910c.png)

Maybe it also would be nice to have some formalized way to propose adding missing extensions to Coder Marketplace.

**Comment by foresthoffman** [comment]
@resure Glad to hear it, i'll close this then.

The current formalized way to propose new extensions for the Coder Marketplace is to create an issue for it using the "Extension Bug" issue template, and then filling out all the information requested for each extension desired.

**Comment by ruslanguns** [comment]
Thanks..

**Comment by JayXon** [comment]
Hi, can I request these extensions to be supported? I wasn't able to find the "Extension Bug" issue template.

https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode
https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
https://marketplace.visualstudio.com/items?itemName=rust-lang.rust
https://marketplace.visualstudio.com/items?itemName=npclaudiu.vscode-gn

**Comment by sr229** [comment]
@JayXon unfortunately I don't think they can add IntelliCode since it violates Microsoft's ToS. You might wanna try something else instead or run your own registry.

**Comment by nhooyr** [comment]
@JayXon I've filed a new issue for you.

https://github.com/cdr/code-server/issues/1427

**Comment by dvelopin** [comment]
Thank you for this project! This is really cool! I just got a new Ubuntu Server setup for development and put this on there. I hope to do more coding from my iPad Pro.

Is it possible for the following extensions be supported?

https://marketplace.visualstudio.com/items?itemName=liximomo.sftp
https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs

**Comment by nhooyr** [comment]
@dvelopin Please open a new issue.

**Comment by dvelopin** [comment]
You got it.

**Comment by dineufeld** [comment]
Please add https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc, its a important one for Flutter development and I need to use it constantly.

**Comment by jsjoeio** [comment]
Hi @dineufeld - we're no longer adding new extensions because we're switching to OpenVSX. Please see docs [here](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#how-can-i-request-a-missing-extension) for how to get that extension in code-server right now.
