### ISSUE TITLE
Install vscode extension on building binary from source

### ISSUE THREAD

**Issue by nishantbhat** [codercom/code-server#580]

**Comment by nishantbhat** [comment]
how can I install some of the vscode extensions into the app when we building the binary from a source. Is there any way to add extensions that comes with default binary

**Comment by foresthoffman** [comment]
@nishantbhat Please update to the most recent stable [release](https://github.com/codercom/code-server/releases/latest), which includes an `--install-extension <value>` CLI option. All of the CLI options can be viewed by running your built binary with the `--help` option.

Thank you!

**Comment by foresthoffman** [comment]
If there are any extensions that you'd like to see in the Coder Extension Marketplace, please open an issue for those extensions using the `Extension Bug` issue template.
