### ISSUE TITLE
Save window session

### ISSUE THREAD

**Issue by infogulch** [codercom/code-server#581]

**Comment by infogulch** [comment]
Oh no I accidentally opened an issue before I was ready to write it.  Apparently if you hit enter anywhere in the new issue editor, including the title, it instantly posts it.  (sorry)

**Comment by NickKartha** [comment]
You should remove this from being visible since it is not relevant to the project.

**Comment by infogulch** [comment]
Yeah feel free to delete or archive or whatever, I don't see any option to do that unfortunately.
