### ISSUE TITLE
List of known API paths

### ISSUE THREAD

**Issue by infogulch** [codercom/code-server#583]
I noted in a [couple](https://github.com/codercom/code-server/issues/512#issuecomment-485334173) [comments](https://github.com/codercom/code-server/issues/555#issuecomment-486084985) that if there was a reasonably well-known list of uri paths that the coder app uses when connecting to the backing server, one could configure their frontend proxy to route some of the unused paths to different ports in the container.  This would allow the user to build and create a web app in the app, run it, and then view it directly in the browser at the same domain as the IDE.

For example, if you host your coder instance at `ide.mydomain.com/` where requests are normally routed to the container's port 8443, you could configure your proxy to route requests to `ide.mydomain.com/web/` to port 8080 in the container, which could be served by a web server running in the coder terminal.

The problem is I don't know what paths are available. (Or even if any paths are available at all -- all paths might be potentially meaningful to vscode internals, I don't even know that much.)  A (semi-)official list of used or open paths would be really helpful.

Here are some of the paths I've noticed that coder definitely *does* use just by interacting with the app:
* `/`, root obviously, converted into a websocket
* Direct assets like `/file.png`, `/git.svg`, `/service-worker.js`, etc
* I think I saw some requests to `/Resources/*`, but I can't seem to reproduce it.

Are there *any* available paths that coder will never use?  If so, is the list above exhaustive, or are there additional paths that coder uses?

**Comment by code-asher** [comment]
At the moment there is no *guarantee* that `code-server` won't use certain paths. The safest thing would be to always give the IDE its own sub-domain or sub-directory.

With that said, I believe this is an exhaustive list as it currently stands:

- `/`
- `/<asset>`
- `/resource/<path to resource>`
- `/login`
- `/login/<asset>`
- `/tunnel`
- `/ports`
- `/ping`
- `/lib/vscode/<path to asset>`
- `/packages/ide/src/fill/webview.html`

**Comment by infogulch** [comment]
Perfect, thank you for this list!

**Comment by kylecarbs** [comment]
Closing for now. Would be good to document the above at some point.
