### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by jishnutv** [codercom/code-server#585]
#### OS : Manjaro 18.0.4 Illyria

![DeepinScreenshot_select-area_20190424231138](https://user-images.githubusercontent.com/40197322/56681196-697fb880-66e6-11e9-983c-665c127c2088.png)
![DeepinScreenshot_select-area_20190424231208](https://user-images.githubusercontent.com/40197322/56681206-71d7f380-66e6-11e9-856f-65611257de6e.png)

**Comment by kylecarbs** [comment]
You can try modifying the port. Not sure what'd cause this issue.

**Comment by MinchinWeb** [comment]
I think I'm getting a similar issue. I'm on Docker, using a `docker-compose.yaml` file, and when I try and run in without authentication (using the `--no-auth` command line option), Firefox displays a similar error. mine reads:

> Secure Connection Failed
>
> An error occurred during a connection to <<hostname>>:<<port>>. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by nol166** [comment]
I think the `--no-auth` flagged is bugged in some of the releases. It basically turns off https currently. It should be fixed in an upcoming release. Not sure if that was the cause of this issue, but I figured I would at least mention it.

**Comment by jishnutv** [comment]
> I think I'm getting a similar issue. I'm on Docker, using a `docker-compose.yaml` file, and when I try and run in without authentication (using the `--no-auth` command line option), Firefox displays a similar error. mine reads:
> 
> > Secure Connection Failed
> > An error occurred during a connection to <hostname>:<port>. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP
> 
> It works fine if authentication is required.

I removed the  `--no-auth` and it works fine, Thank you all.
