### ISSUE TITLE
On Arch Linux server password param doesn't work, and ENOENT error on diretory that's not working directory

### ISSUE THREAD

**Issue by leetNightshade** [codercom/code-server#62]
#### Problems
1. ~~Server password param doesn't work~~
2. ENOENT error on working directory, trying to access subfolder that doesn't exist.
3. Website is a blank screen after login, probably related to problem 2 directly above.
4. Output version is 0.0.0 instead of 1.31.1-100. 

#### Info
- `code-server` version: server/0.0.0 linux-x64 node-v8.9.3   I had downloaded 1.31.1-100 from code-server-1.31.1-100-linux-x64.tar.gz
- OS Version: Linux archlinux 4.20.12-arch1-1-ARCH #1 SMP PREEMPT Sat Feb 23 15:11:34 UTC 2019 x86_64 GNU/Linux on Linode
- Setup is running code-server in a webdirectory through nginx.

#### Steps to Reproduce

1. Setup systemd ide.service to run code-server as a user, in my case http, same as web user process for php and mysql. 
2. ~~Run code-server --password=testing
Notice when trying to enter password the generated one is what works, not the passed in one.~~
2. ENOENT on /working/directory/here/plus/Backups/workspace.json. It seems to be looking for a Backups folder in my working directory, and a workspace file that doesn't yet exist. 
3. When running code-server --version for  this bug, it output 0.0.0 for the server version.

**Comment by kylecarbs** [comment]
There's a caching issue with the assets since files are named the same on the password-prompt and IDE bundles. You can try clearing your cache.

**Comment by code-asher** [comment]
All asset names and paths are unique now so this should be solved.
