### ISSUE TITLE
Code Spell Checker extension crashes

### ISSUE THREAD

**Issue by ymmt2005** [codercom/code-server#63]
- `code-server` version: 1.31.0-20
- OS Version: Ubuntu 18.04
- Extension: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

#### Steps to Reproduce

1. Download vsix file of the extension.
2. Unzip vsix and copy `extension` directory under `~/.code-server/extensions/streetsidesoftware.code-spell-checker-1.6.10`
3. Enable the extension in `code-server`.
4. The extension crashes with the following error message:

```console
Error: Cannot find module 'vscode-languageserver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at Module.r.require.e [as require] (/usr/local/bin/code-server:468:26234)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ymmt/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js:4:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
[Info  - 10:44:40] Connection to server got closed. Server will restart.
```

**Comment by Littlejd1997** [comment]
Same issue with TSLint.

**Comment by ymmt2005** [comment]
Same issue with https://github.com/codercom/code-server/issues/200#issuecomment-472239389

**Comment by schrej** [comment]
It doesn't work for me either, ESLint outputs the follwing in the `Output` tab when selcting `ESLint` on the right:
```
[Info  - 15:44:10] ESLint server stopped.
[Info  - 15:44:12] ESLint server running in node v8.15.0
[Info  - 15:44:12] ESLint server is running.
 ›   Error: Unexpected arguments: var p = 
 ›   process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else 
 ›   if(m.c==='rs'){try{var 
 ›   r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r
 ›   ',s:false});}}});, 
 ›   See more help with --help
```

**Comment by zigego** [comment]
@schrej Change the version of node, Eslint work with build-in node by default.
 Open settings，then set eslint.runtime to your local node. It works to me both Debian and Mac.

**Comment by schrej** [comment]
@zigego Thank you!
After setting `"eslint.runtime": "/usr/bin/node"` ESLint works fine and shows issues in the editor.

**Comment by foresthoffman** [comment]
@ymmt2005 It appears that the current version of [Code Spell Checker](https://github.com/Jason-Rev/vscode-spell-checker/releases/tag/1.6.10) is quite outdated and using some invalid dependencies, which means that it is unpackageable. I'm seeing the same errors as the current [failing build](https://travis-ci.org/Jason-Rev/vscode-spell-checker/jobs/510564965).

I've created an issue on the extension's repo: https://github.com/Jason-Rev/vscode-spell-checker/issues/318

**Comment by ymmt2005** [comment]
@foresthoffman 
Thank you very much for your investigation.

I'm going to close this issue.  Code spell checker is a must have for me so I hope
someday it is packaged for code-server.

code-server is simply great.  Thank you, and keep going!

**Comment by foresthoffman** [comment]
https://github.com/Jason-Rev/vscode-spell-checker/issues/318 was merged this morning, so now the build works properly. I've got a PR up that should allow the spell checker build to be automated properly.
