### ISSUE TITLE
read VSCode settings as default

### ISSUE THREAD

**Issue by kaijajan** [codercom/code-server#66]
1. If system has vscode installed previously, code-server read installed vscode's settings/extensions
2. provide a option to loads system vscode settings/extensions

Thanks so much

**Comment by kylecarbs** [comment]
Not certain how I feel about this. Maybe we display a notification to optionally inherit the existing vscode installation?

**Comment by fand** [comment]
Adding CLI option like `code-server --use-local-settings` might be also useful.

**Comment by zk-g** [comment]
You can try with the extension [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) meanwhile

**Comment by kaijajan** [comment]
settings sync unable to install - https://github.com/codercom/code-server/issues/43 (1.31.0-20)
haven't tried the latest one yet

**Comment by jeasonstudio** [comment]
Great idea.

**Comment by kylecarbs** [comment]
[sshcode](https://github.com/codercom/sshcode) can be used to make this seamless :smile:  closing
