### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by zk-g** [codercom/code-server#73]
In the top-right corner keep just a button to toggle fullscreen mode

**Comment by lucacasonato** [comment]
Use the already existing window maximize button. We should also make the X close the tab while we are at it.

**Comment by zk-g** [comment]
What? the maximize button in windows  it's not for fullscreen mode, in the post I also wrote to Keep just 1 button to toggle the fullscreen mode (F11), others are useless

**Comment by kylecarbs** [comment]
Feels kinda weird to add this. I believe the fullscreen command doesn't work atm. Might work to just fix that.

**Comment by code-asher** [comment]
We decided to remove the buttons in the top-right corner. You can still use `F11` and on Chrome you can also use the command palette.

**Comment by maxfi** [comment]
@kylecarbs I couldn't find an issue for fullscreen not working. When pressing `F11` the following error occurs:

```
ERR Document not active: TypeError: Document not active
    at t.setFullScreen (http://127.0.0.1:10162/ide.main.92c1f4.js:38:75836)
    at e.toggleFullScreen (http://127.0.0.1:10162/ide.main.92c1f4.js:60:1645872)
    at t.toggleFullScreen (http://127.0.0.1:10162/ide.main.92c1f4.js:60:6355817)
    at t.run (http://127.0.0.1:10162/ide.main.92c1f4.js:60:1591193)
    at http://127.0.0.1:10162/ide.main.92c1f4.js:23:101901
```

**Comment by cnfatal** [comment]
Command Palette >:View: Toggle Full Screen.  works
