### ISSUE TITLE
How can I Install Another Version Extension

### ISSUE THREAD

**Issue by pollenjp** [codercom/code-server#77]
- `code-server` version: 1.31.1-100
- OS Version: Ubuntu16.04
- Extension: all (example [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim))

#### Steps to Reproduce

1. I try to downgrade vim plugin to v1.0.8, but there is no selections without v1.1.0 when I click "Install Another Version..." (Fig1).

Fig1
![image](https://user-images.githubusercontent.com/33354327/53945741-9d3a5b00-4105-11e9-9b7d-70b1b2694ee7.png)

I want to downgrade vim because I am hitting https://github.com/codercom/code-server/issues/61 problem.

My local VSCode can choose another version (Fig2).
Fig2
![image](https://user-images.githubusercontent.com/33354327/53945714-8a278b00-4105-11e9-9fc2-87e2a99ed341.png)

This behavior is seen in other extensions (like Python or C++). I don't know whether this is a bug or not because I am not familiar with VSCode.

**Comment by pollenjp** [comment]
I tried to install from VSIX, but got an error "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"

example: [vim-1.0.8.vsix](https://github.com/VSCodeVim/Vim/releases)

**Comment by nhooyr** [comment]
Related to #92 maybe?

**Comment by pollenjp** [comment]
Maybe

**Comment by foresthoffman** [comment]
Manual installation of VSIXs should be fixed via #245.
