### ISSUE TITLE
Extension is not enabled after restart

### ISSUE THREAD

**Issue by wwbmmm** [codercom/code-server#78]
- `code-server` version:  v1.31.1-100
- OS Version: Ubuntu 18.10

#### Steps to Reproduce

1. Install one extension
2. restart code-server, then you can see all extensions is disabled, and can't be enabled again.

![image](https://user-images.githubusercontent.com/3894631/53948676-50558500-4103-11e9-839f-47d78d30b736.png)

**Comment by kylecarbs** [comment]
Will investigate. Is this using the docker command?

**Comment by wwbmmm** [comment]
> Will investigate. Is this using the docker command?

Yes, I use docker command, and use -d option to specify data directory to a docker volumn. So when I rerun docker command, the old data will be used.

**Comment by nhooyr** [comment]
@kylecarbs should we modify the one-liner to also mount a data directory?

**Comment by kylecarbs** [comment]
That's probably a good idea.

**Comment by nhooyr** [comment]
So in order to fix this, `code-server` needs to stop putting binaries into the data directory and reusing them as it'll screw with things on macOS for example. Best to use a temp dir or name the binaries with their OS and arch.

**Comment by fedelemantuano** [comment]
I have the same issue in

```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```

With binary version:

```
server/0.0.0 linux-x64 node-v8.9.3
1.31.1-100
```

I use server without root permission.

**Comment by kylecarbs** [comment]
@nhooyr the only binary we unpack is ripgrep. That shouldn't prevent any loads though.

**Comment by nhooyr** [comment]
There is some pty.node binary in .code-server.

**Comment by fedelemantuano** [comment]
Yes. My data folder is in `/var/lib/vscode` and `pty.node` is in `/var/lib/vscode/dependencies`.

**Comment by kylecarbs** [comment]
It's probably best if we keep data in one place, and move temporary unpacked items to another folder. I suppose we could just keep them in `<tmpdir>/code-server/`

**Comment by fedelemantuano** [comment]
Hi,
I run the server with this code:

```
/opt/vscode/code-server -d /var/lib/vscode --cert=fullchain.pem --cert-key=privkey.pem development
```

Can you explain me what I have to change?

**Comment by krazyito65** [comment]
Same issue to me, extensions are disabled on restart and if i change folders they become disabled.  the only way for me to re-enable is to uninstall / install again

**Comment by guyuxiang** [comment]
When refreshing the browser, the file `user-data-dir/CachedExtensions/user` will be regenerated. However it cannot be generated correctly. 

It is always like following:
`{ "input": { "ourVersion": "1.32.0", "locale": "en", "devMode": false, "absoluteFolderPath": "/root/.local/share/.code-server/extensions", "isBuiltin": false, "isUnderDevelopment": false, "tanslations": {} }, "result": [] }`

`"result": []` is always empty, including no information of installed extensions.

**Comment by fedelemantuano** [comment]
With [this release 1.32.0-245](https://github.com/codercom/code-server/releases/tag/1.32.0-245) my issue is solved. Now the extensions are enabled also after restart.

**Comment by foresthoffman** [comment]
@wwbmmm did release 1.32.0-245 fix the issue for you as well?

**Comment by krazyito65** [comment]
I can say based on my testing with #209 I have seen the issue come up on CentOS 7, I happened when i would use 'open folder' and then i would try to disable the extensions all together and then Enable (workspace), when I swap folders around my python extension was unable to work for me (I could not re-enable it).

**Comment by parimanur** [comment]
Seeing this issue with the latest release (code-server1.696-vsc1.33.0-linux-x64 ). Any workaround for the issue?

**Comment by kylecarbs** [comment]
Should be fixed with latest versions.
