### ISSUE TITLE
Can't install any Extension.

### ISSUE THREAD

**Issue by painhardcore** [codercom/code-server#82]
- `code-server` version:  code-server v1.31.1-100
- OS Version: Linux ubuntu 4.15.0-46-generic
- Extension:  alll 

tested on 2 different hosts. Binary and docker version
#### Steps to Reproduce

1. run code-server
2. try to install any extension

Even manual download response error
example
https://v1.extapi.coder.com/publishers/ms-vscode/vsextensions/Go/0.9.0/vspackage =>Cannot GET /publishers/ms-vscode/vsextensions/Go/0.9.0/vspackage

**Comment by gerroon** [comment]
I cant even install .vsix, it complaints about tar header. I tried https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by haydennyyy** [comment]
Might wanna have a look at my PR #113

**Comment by haydennyyy** [comment]
Actually, ignore that. ms-python is open source.

**Comment by kylecarbs** [comment]
Will take a look.

**Comment by foresthoffman** [comment]
Hello @haydennyyy, can you please check the Popular Extensions list? You can view it by opening the Extensions View, click on the ellipses (`...`), then select "Show Popular Extensions". Python should be at the top of the list.

Hello @gerroon, we have an issue regarding installing from `.vsix` files: https://github.com/codercom/code-server/issues/92.

**Comment by gerroon** [comment]
@foresthoffman  awesome, thanks for the follow up.

**Comment by kylecarbs** [comment]
For some reason the python ext doesn't appear to come up when searching `python` 😕

**Comment by gerroon** [comment]
yeah, that is why I decided to download the extension and install that way.

**Comment by foresthoffman** [comment]
@gerroon The extension API has been updated to support sorting, so Python should be discoverable outside of the popular extensions list.

The original issue has also been dealt with.
