### ISSUE TITLE
Locales are not available in local docker image

### ISSUE THREAD

**Issue by xMrWhite** [codercom/code-server#83]
- `code-server` version: master
- OS Version:  4.20.8-arch1-1-ARCH

not having locales can cause unexpected behaviour when working with text that is utf-8 encoded

#### Steps to Reproduce

1. docker run -p 8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
2. open terminal and type `locale -a` see `en_US.UTF-8 is` missing

**Comment by nhooyr** [comment]
@xMrWhite What issue are you seeing with this. I can output UTF-8 text fine. Do certain apps disable/enable UTF-8 based on the locale?

**Comment by nhooyr** [comment]
Ah it seems they do.
