### ISSUE TITLE
Multi-User support: SAML / OpenID Auth

### ISSUE THREAD

**Issue by PhilsLab** [codercom/code-server#85]
I'd like to see multi-user support in a future release.

Integrating authentication with SAML or OpenID would be ideal,
as it is easy to provide such a service via IdPs like Keycloak. (Maybe even Keycloak integration?)

Helpful resources:
Keycloak IdP project: [keycloak/keycloak](https://github.com/keycloak/keycloak)
Keycloak NodeJS integration: [keycloak/keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect)

Different projects could be individually assigned to registered users, and editor handling could be similar to word online:
![word online](https://user-images.githubusercontent.com/15452526/53963221-22fddc80-40ed-11e9-8baa-2030ca6d7960.png)

Thanks in advance.

**Comment by foresthoffman** [comment]
Hello @PhilsLab,

Thank you for making this request. We have an existing issue open for this: https://github.com/codercom/code-server/issues/33. To keep things organized we'll keep track of the multi-user support discussion there. If you would drop a comment with those resources, into the discussion, that would be helpful.

Thanks,
Forest

**Comment by PhilsLab** [comment]
Thanks for letting me know, seems like i overlooked that one.
