### ISSUE TITLE
Docker container to try out Coder.

### ISSUE THREAD

**Issue by hortinstein** [codercom/code-server#9]
I think you should add a docker container deployment one liner to your landing page similar to https://www.theia-ide.org/

Should be simple enough to create the image and add to your CI and keep an official one with Docker Hub...with docker for windows this also *sorta* meets your windows goals

**Comment by kylecarbs** [comment]
We’ll do this!

**Comment by foresthoffman** [comment]
I can't assign this to myself, but i'm looking into it.

**Comment by grikomsn** [comment]
I'd like to work on this, currently building locally using Ubuntu as the base image. ✨

**Comment by sakanamax** [comment]
I try to run code-server-1.31.0-20-x86_64-linux in docker.
I already publish the port 80
But when I open the browser to connect http://localhost:80
I get timeout

That mean I can't run it in docker, right?

Here is the message I run in the docker
4d5d5deee7e0:/code-server-1.31.0-20-x86_64-linux # ./code-server -p 80
INFO  code-server v1.0.0
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.code-server","working-dir":"/code-server-1.31.0-20-x86_64-linux","log-dir":"/root/.code-server/logs/20190306151336507"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":80}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO   
INFO  Password: UbVvGNdLNkWI
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:80/
INFO

**Comment by kylecarbs** [comment]
Are you exposing the port on your host? [Ref](https://docs.docker.com/config/containers/container-networking/#published-ports)

**Comment by sr229** [comment]
I already made my own Flavor of this [Issue](https://github.com/sr229/code-server-openshift)

Enjoy.

**Comment by sakanamax** [comment]
> @sakanamax Are you exposing the port on your host? [Ref](https://docs.docker.com/config/containers/container-networking/#published-ports)

Yes, I already expose the port on  my host

**Comment by frol** [comment]
@sr229 Does it work for you? It just hangs when I open the link. Here are the logs:

![image](https://user-images.githubusercontent.com/304265/53893714-685fd280-4037-11e9-9532-10d0807af3f0.png)

**Comment by sr229** [comment]
@frol I believe this is a bug within Coder. Opening issue.

**Comment by nhooyr** [comment]
I'm working on this issue.

**Comment by andrewwakeling** [comment]
@kylecarbs It looks like this is no longer on the landing page. I noticed it disappeared in the last few months.
I personally found it very very useful and I'm not a big fan of the "Request Demo" form that now appears.

Is this really the best thing for Coder? I'm concerned that people who want to trial the software have to somehow land on https://github.com/cdr/code-server to find the same Docker commands that used to be on the website.

**Comment by sr229** [comment]
@andrewwakeling I wrote a little Katacoda playground if you wanna try out code-server. I'll let the Coder team link it as well since it might be useful.
