### ISSUE TITLE
[coder.com] What is Boost?

### ISSUE THREAD

**Issue by cheapsteak** [codercom/code-server#91]
#### Description
![image](https://user-images.githubusercontent.com/743976/53974800-6a766f80-40d1-11e9-8d12-c7375da5104e.png)

What is this lightning button on the sidebar? Hovering over says "Boost"
What happens when you click it / turn it on?
Surprisingly a search for "boost" didn't turn up anything in this repo

**Comment by kylecarbs** [comment]
We'll add some documentation for this!

**Comment by jhalek90** [comment]
while we wait for documentation:
Boost on coder.com allows your container to  use more resources, for intense tasks.

**Comment by nhooyr** [comment]
@nol166

**Comment by nol166** [comment]
Moved to: https://github.com/codercom/features/issues/201

I will work on docs
