### ISSUE TITLE
Auth redirect does not work under cloudflare universal SSL

### ISSUE THREAD

**Issue by ICEFIR** [codercom/code-server#93]
- `code-server` version: 1.0.0
- OS Version: Debian 9, using docker

#### Steps to Reproduce

1. Setup Cloudflare with universal SSL ( Which basically turns on their proxy service )
2. That's it. The auth redirect somehow does not work! Doesn't matter what password I use, it just redirects to the same login page, with no useful indication in either client or server console

If I either drop down Cloudflare SSL and use plain HTTP, or disable auth and directly run with --no-auth option, both work just fine....

**Comment by kylecarbs** [comment]
What level is your SSL set to?

https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean-

**Comment by ICEFIR** [comment]
Currently Flexible, and on my server, I have not deployed any certs to the subdomain code server use

**Comment by kylecarbs** [comment]
Ah kk. Could you try updating to `Full SSL` and seeing if it works? Could just be the way we redirect.

**Comment by ICEFIR** [comment]
Sure :) I will test it out
On a side note, i do have nginx setup, with the following script...
Dont think that will cause the redirect though? 
```

server {
    listen 80;
    listen [::]:80;
    server_name vscode.icyns.com;
    location ~/ {
       proxy_pass http://localhost:8443;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection upgrade;
    }
}
```

**Comment by ICEFIR** [comment]
Sure :) I will test it out
On a side note, i do have nginx setup, with the following script...
Dont think that will cause the redirect though?

```

server {
    listen 80;
    listen [::]:80;
    server_name something.something.com;
    location ~/ {
       proxy_pass http://localhost:8443;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection upgrade;
    }
}
```

**Comment by kylecarbs** [comment]
Hm. This will almost definitely work by adding the `--allow-http` flag.

**Comment by ICEFIR** [comment]
--allow-http has always been specified in the docker-compose command ;)
The service works fine with --no-auth option, after all.

**Comment by kylecarbs** [comment]
Will still look into this for ya. Something funky must be going on!

**Comment by ICEFIR** [comment]
Thx! And yes I have confirmed (at least from my limited testing) Full  SLL does not work, either.
Drop their SSL and use self-signed one works, tho.

**Comment by Pitu** [comment]
I'm not using the docker image, but I am running the code-server through CloudFlare with SSL set to `Full (Strict)`, `Universal SSL` and `Always use HTTPS` and it works just fine.

If you want I can give you my nginx config to check.

**Comment by ICEFIR** [comment]
@Pitu Thx! Though I have tried it out yet still not working
Deployed Letsencrypt SSL on the server, direct connection works fine. 
With CloudFlare SSL set to Full (Strict), Universal SSL and Always use HTTPS, along with your nginx proxy config, still, no way to log in. 

This is a wired one...

**Comment by Pitu** [comment]
That's pretty weird indeed. And yeah, the SSL config shouldn't matter unless your connection is getting drop which doesn't seem the case, otherwise you wouldn't be able to access the login page at all. 

Just for the sake of curiosity could you stop code-server, start it again so it generates a new password and then with DevTools open and the setting `Disable cache (while DevTools is open)` turned on, hard refresh with `CTRL + R` try getting in with the new password?

**Comment by ICEFIR** [comment]
@Pitu  Wow apparently that worked! 
Upon further testing, the only thing that's mattered was `Disable cache (while DevTools is open)` option... But how does this make any sense tho? (scratching my head trying to figure out what went wrong....)
All local cache was clear before any kind of testing, Cloudfare cache was bypassed (Development Mode), multiple browsers and devices have been tested...

**Comment by ICEFIR** [comment]
Also, irrelevant to the option mentioned above, apparently if I smash the Ctrl-R enough times, it does let me in, somehow?

So, basically, from a normal login page
![image](https://user-images.githubusercontent.com/6231162/54008299-0948ad80-415e-11e9-9eae-eb9a3785e31f.png)

To whatever this is, with console showing `GET https://yourdomain.com/main.js net::ERR_ABORTED 404`
![image](https://user-images.githubusercontent.com/6231162/54008329-2a110300-415e-11e9-8450-8c117b3004a1.png)

And now just smash that Ctrl-R. like, 10+ times or so, i am in?
![image](https://user-images.githubusercontent.com/6231162/54008376-5d539200-415e-11e9-9547-fa604f17c886.png)

**Comment by Pitu** [comment]
Yeah this project has something interesting going on with cache, I haven't had the time yet to put my finger on it, but I had the same issue happen to me so I'm glad I was able to help someone out with it.

**Comment by Pitu** [comment]
At the same time, I'm in favor of ditching the login page entirely and just relying on .htpasswd for my own personal use, so that should help with the cache probably and it's something I'll implement tonight.

**Comment by kylecarbs** [comment]
We use the same filenames in both the authed and unauthed bundle so your browser is caching them. This will be fixed soon!

**Comment by ICEFIR** [comment]
Great! Was thinking about using .htpasswd as well, but I guess now I just need to wait a bit :)

**Comment by Briguns** [comment]
Same problem here, but weirdly logging in works on iPad no problem. Glad to here a fix is in the works!

**Comment by Vap0r1ze** [comment]
This happens for me too. I have cloudflare as a proxy and have SSL on Flexible. It works on https, but on http it doesn't. On my host I use nginx, and this is the nginx file for my code-server:
```
server {
    listen 80;
    server_name ide.website.com;

    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Connection upgrade;
        proxy_set_header   Host $http_host;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_pass         "http://127.0.0.1:8443";
    }
}
```

I've noticed that on http, no matter what I put as the password, it always sets the password cookie to my HOSTS ip, not the cloudflare proxy but my hosts public ip.

**Comment by allan-walpy** [comment]
I had same issue and after reading thread had an idea of possible workaround:
```nginx
add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
```
[googled in here: disable caching in nginx for js files](https://stackoverflow.com/a/45285696/6256541)

so mine nginx configuration (apart other project I host) became smth this:
```nginx
upstream vscode {
	server 127.0.0.1:1234;
}

server {
        listen *:443 ssl;

	server_name code.example.com vscode.example.com;

	location / {
		proxy_pass        https://vscode;
		proxy_http_version 1.1;
		proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection upgrade;
                proxy_set_header   Host $host;
                proxy_cache_bypass $http_upgrade;
		proxy_redirect off;
		proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
		add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
	}
        ssl on;
        ssl_certificate /etc/ssl/domain/certificate.pem;
        ssl_certificate_key /etc/ssl/domain/private.key;
}
```

and issue was resolved for me

P.S. used GithubReleases version `code-server-1.32.0-282-linux-x64.tar.gz`

Launch command smth like this:
```shell
./code-server --port 1234 --cert=/etc/ssl/domain/certificate.pem --cert-key=/etc/ssl/domain/private.key --password=vscode.password /home/walpy/some/working/dir
```

but not sure I haven't broke smth

**Comment by gijo-varghese** [comment]
using CF flexible SSL. Same issue, unable to set the password and make it work. Works pretty well if I use `--no-auth`.

**Comment by kylecarbs** [comment]
Self-signed certificates should work with cloudflare. Closing
