### ISSUE TITLE
add install script to automatically download binary into /usr/local/bin/code-server

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#94]

**Comment by robertpeteuil** [comment]
You might be able to leverage this [installation script](https://github.com/robertpeteuil/terraform-installer) that I created for Terraform.

It can provide a base as it has a lot of error checks, parameter options, and logic for:
- finds the latest release from the GitHub API 
- determines OS and architecture and creates the download URL
- downloading, extracting and copying to binary directory

**Comment by kylecarbs** [comment]
Fixed with [sshcode](https://github.com/codercom/sshcode) :confetti_ball:
