### ISSUE TITLE
[coder.com] cdr.co button missing 

### ISSUE THREAD

**Issue by lawaltijani** [codercom/code-server#96]
#### Description
In the previous version of coder, I could open up my express server in the browser, now in the new version, the port icon is not even available to open

![port](https://user-images.githubusercontent.com/47070912/53976501-c7235b80-40cc-11e9-851d-ea27142c85f2.PNG)

**Comment by coadler** [comment]
@lawaltijani the cdr.co button was removed temporarily removed from the coder hosted version during Monday's update. If you send an email to `cadler@coder.com` from the email you signed up with I can send you your cdr.co url!

**Comment by lawaltijani** [comment]
Thank you my good sir

**Comment by pjoe** [comment]
Having the same issue, why is this closed? Is there any automatic way to retrieve crd.co url?

**Comment by coadler** [comment]
@pjoe I believe we already talked over email, but the cdr.co button was removed in our move to open source and should be reimplemented in the next few days. The only way to get it currently is to email me or support. Apologies for the inconvenience!

**Comment by pjoe** [comment]
@coadler no worries, can't really complain about a free service, but would suggest to keep this issue open until fully resolved (for others to see).

Btw. awesome idea with the boost mode :) Kind of curious as to how it is implemented (guessing dynamically adjusting cgroup limits)

**Comment by coadler** [comment]
I agree, but I'm trying to keep issues about our service off of this repo and on the [coder.com bugs](https://github.com/codercom/bugs/issues) repo.

I thought there already was an issue tracking the button over there but I was mistaken. I went ahead and made one: https://github.com/codercom/bugs/issues/359
