### ISSUE TITLE
packaging: remove windows/macOS support in favour of using docker

### ISSUE THREAD

**Issue by nhooyr** [codercom/code-server#97]
Will make our CI/testing/code simpler.

Docker should be enough for pretty much every use case I can think of anyway, aside from developing windows apps or macOS apps which code-server doesn't really have good support for anyway.

Not 100% convinced this is the way to go, opening for thoughts.

@kylecarbs @coderasher

**Comment by PhilsLab** [comment]
I like this idea. This kind of application has most potential when deployed in a container, also opening a lot of possibilities for Kubernetes.

**Comment by Omeryl** [comment]
I'm iffy on this because Docker on Mac can be really weird sometimes, how much code would be removable if you removed macOS support?

**Comment by kylecarbs** [comment]
Not much. All the code is pretty generalized.

**Comment by orzFly** [comment]
Docker on Windows is also really weird.

By the way, installing Docker for Windows enables Hyper-V, which prevents you from being able to use VMWare Workstation or Player. (Although there may be some workarounds, it's weird.

**Comment by kylecarbs** [comment]
This seems to be a split response.

I love the idea of removing platforms in favor of using Docker. I suppose an issue is that `code-server` wasn't really designed with containment in mind.

**Comment by NGTmeaty** [comment]
Personally, I would much rather more platform support. Docker is annoying to setup on windows and imo shouldn't be forced. If we can compile a binary for it, we might as well.

**Comment by fmichaleczek** [comment]
I prefer more plateform support.

**Comment by nhooyr** [comment]
Closing, doesn't take much effort to support all platforms.
